### ISSUE TITLE
questions about which port is the website in and how to install this plugin

### ISSUE THREAD

**Issue by panfu28** [BlueMap-Minecraft/BlueMap#1]
i dont understand how to install this plugin? like, i put the BlueMap.jar in my plugins folder but nothing happens when i launch my server, like, no messages in the console and no folders or config files created in my plugins folder.
and also if its supposed to not have a config file in which port is the website by default?

**Comment by mikroskeem** [comment]
What server platform?

**Comment by TBlueF** [comment]
Did you build your .jar from this Project or the actual [BlueMap-Sponge](https://github.com/BlueMap-Minecraft/BlueMap-Sponge) Project? This is only the core that has all the platform independent code in it.
[BlueMap-Sponge](https://github.com/BlueMap-Minecraft/BlueMap-Sponge) is the actual plugin for Sponge, which also has a configuration that is generated for you with the first start :)
