### ISSUE TITLE
Web Server not working.

### ISSUE THREAD

**Issue by Osprey4444** [BlueMap-Minecraft/BlueMap#1]
Everything loads up fine but the web server doesn't seem to load, I'm testing this on a VPS before adding it to my Dedicated Server array.

**Comment by TBlueF** [comment]
You are using the Sponge Plugin, right?
Are you getting any response in your browser like a 4xx or 5xx or just a "This site can’t be reached"?
If you start the Server or type `/bluemap reload`, does it say "WebServer started." in the console?
What is your configuration? Is the IP and the port correct and is the port open/accessible on your VPS?

**Comment by TBlueF** [comment]
Closing this for now, please reopen if you still have issues with this :)

**Comment by EsserGaming** [comment]
Was this before the discord? Cause this is funny 😏
