### ISSUE TITLE
Rescaling the web window breaks rendering

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#10]
If the viewport in any way changes shape after the page has loaded, the map becomes distorted.

**Comment by TBlueF** [comment]
What browser are you on?

**Comment by Katrix** [comment]
Firefox Nightly 74.0a1 (2020-01-13) (64-bit)

**Comment by TBlueF** [comment]
I was able to reproduce this with Firefox Nightly
It works fine with the Stable Firefox build and Chrome though.

**Comment by Katrix** [comment]
No longer seeing this issue
