### ISSUE TITLE
Please Support spigot 1.11.2 ^^

### ISSUE THREAD

**Issue by EnderGriefeur99** [BlueMap-Minecraft/BlueMap#104]
Please Support spigot 1.11.2 ^^

**Comment by TBlueF** [comment]
I will not support any Minecraft Version below 1.12.2
sorry :)

**Comment by EnderGriefeur99** [comment]
okay ;(

**Comment by TBlueF** [comment]
The reason behind this is that lower versions of minecraft have an other (worse) resource-management and world-storage that BlueMap is not designed to work with, meaning it would be very time-consuming to implement support for those versions.
1.12 already has only limited support and has the luck that sponge requires 1.12. (Otherwise i would not have supported 1.12 either) BlueMap's core works best with 1.13 and above :)

**Comment by EnderGriefeur99** [comment]
at this moment, you have a solution to tell me how i do add this support manually (btw i know java) or it's a big work if i want to implements that ? if you need we can talk by msg on discord ^^

**Comment by TBlueF** [comment]
As i said: "it would be very time-consuming to implement support for those versions"
If it would just be a quick fix i'd do it ^^'

**Comment by EnderGriefeur99** [comment]
okay you think when you finished the todo list in the future you can get the time to implement that ?

**Comment by TBlueF** [comment]
To be honest I currently don't think i will ever come back to older minecraft-versions ... things move forward, there is no reason to invest time in outdated versions. There will be new Minecraft-Versions and focus will always be keeping BlueMap up to date with the latest versions. Maybe even dropping support for the older versions.

So.. If you really want to give it a go, here would be the places to look:
- Make a chunk-loader that is compatible with 1.11 world-chunks (https://github.com/BlueMap-Minecraft/BlueMap/tree/master/BlueMapCore/src/main/java/de/bluecolored/bluemap/core/mca)
- Make resources and resource-extensions compliant with 1.11 (https://github.com/BlueMap-Minecraft/BlueMap/tree/master/BlueMapCore/src/main/resourceExtensions, https://github.com/BlueMap-Minecraft/BlueMap/tree/master/BlueMapCore/src/main/resources/de/bluecolored/bluemap)
- Introduce 1.11 here (https://github.com/BlueMap-Minecraft/BlueMap/blob/master/BlueMapCore/src/main/java/de/bluecolored/bluemap/core/MinecraftVersion.java)
- Downgrade the spigot plugin to 1.11 (https://github.com/BlueMap-Minecraft/BlueMap/tree/master/implementations/spigot)
- Probably other things that i forgot right now
