### ISSUE TITLE
Free-flight controls for the webapp

### ISSUE THREAD

**Issue by GriffinCodes** [BlueMap-Minecraft/BlueMap#108]
I would like to be able to adjust the camera to a more level angle a couple dozen blocks in the air, for example when viewing [this build](https://bluemap.bnn.gg/#legacy:454:1082:0.02:75.94:0.86:85), I can barely see the town unless I zoom out to the point where details start to blur.

**Comment by TBlueF** [comment]
I think this will be resolved with the introduction of the (switchable) free-flight controls that are planned pretty soon, wouldn't it?
With those you can have every angle you want :D

**Comment by TBlueF** [comment]
Additional request (#119) for free-flight:
Entering freeflight-controls while being locked on a player should enter and follow the view of that player (only updating in 1s intervals for now).

**Comment by ChloeDawn** [comment]
Just adding to this, it would be nice to see toggleable no-clip when free-flight is implemented

**Comment by TBlueF** [comment]
@ChloeDawn The problem with this is, that the rendered-model does not contain any colision-boxes .. which means the only thing i could do to implement collisions is either add collision-boxes which would not only inflate the size of the rendered map and the render-time, but also be a huge change to how things work currently, or do collision-detection by raytracing to the model, which is not only prone to be laggy and buggy, but you'll also get stuck on every tall-grass or on the water-surface..
And that's the reason i decided to not do anything that depends on collisions ^^'

**Comment by ChloeDawn** [comment]
Could you not have it collide with the model bounds? It wouldn't be entirely accurate to the game but I think it'd be fine. I assumed this is how you handled the current surface tracking? There could be a block properties flag to mark said block as having no collision too 

I fully understand if any of this is too expensive to compute for the mod though... do you think it would be achievable with a plugin if I were to look into making one?

**Comment by TBlueF** [comment]
There are no individual "blocks" and block-properties for the web-app, as they are pre-combined by the plugin to one big model for each map-tile (32x256x32 blocks), so the model bounds is not useful at all ^^'
The surface-tracking is done via raytracing from camera and target positions downwards, which works well for that case but is very costly and unpractical to do (high-precision & high-frequency) collision-detections, i think..

**Comment by TBlueF** [comment]
Free-flight got implemented in 1.4.0.

This:
> Entering freeflight-controls while being locked on a player should enter and follow the view of that player (only updating in 1s intervals for now).

got moved to its own ticket: #175
