### ISSUE TITLE
Changing worlds doesn't work

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#11]
I'm unable to use the dropdown to change the currently selected world. Navigating to it by address works.

I guess it has something to do with checking the wrong variable here.
https://github.com/BlueMap-Minecraft/BlueMap/blob/master/BlueMapCore/src/main/webroot/js/libs/bluemap.js#L982

**Comment by TBlueF** [comment]
This will be fixed when merging #6

**Comment by TBlueF** [comment]
Fixed with fa0d13f48f40ddd2939776f8e46ca69feb633b49
