### ISSUE TITLE
Large bodies of water appear with 'phantom artifacts' in both render distances

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#110]
**BlueMap Version:**
1.2.0-snap on 1.16.3 Fabric 

I am using:
- [ ] mods (on the rendered world)
- [ ] resourcepacks (in bluemaps `config/resourcepack` folder)

**Description:**
Rendered Oceans and large bodies of deep water occasionally have an almost grid-like pattern of a few low resolution polygons dipping down into the world. My guess would be rendering the Y value of these didn't quite go right. On top of this, zooming in to load the higher resolution version does not remove this artifact, which explains my naming for this.
I've attempted a re-render thrice, with the results being the same.

Attached below is a screenshot from the rendered map, with the first showing the distance and variety of them in ocean biomes, and the second showing the refusal to disappear when zoomed in.

![bug1](https://user-images.githubusercontent.com/23224476/97070849-2505ff00-15a1-11eb-9f21-c02fc100009a.png)
![bug2](https://user-images.githubusercontent.com/23224476/97070847-233c3b80-15a1-11eb-93a5-8a8cfedb83ba.png)

**Comment by TBlueF** [comment]
This issue exists since the first version and i already managed to reduce the number of these "artifacts" a lot.
I think this is a synchronization issue when updating the lowres tiles on multiple render-threads ..
You can sometimes remove the artifacts by rendering that region again.
At some point, I will look over this again, and try to fully fix it.

**Comment by ghost** [comment]
As of the latest release (1.4.2 on 1.16.5 Paper MC), I can no longer see this occurring at all. I'm not sure if this was a fabric specific issue, but I just switched my server to using Paper and updated the plugin and am unable to see any of these artifacts or anything wrong at all. Everything seems to be rendering just fine.

**Comment by ghost** [comment]
Had a situation with the map (on my account, not the plugins) where I needed to reset all the maps and rerender. The rerender seems to have these artifacts again. I also noticed how they aren't just restricted to the water anymore, and now appear on land as well. Figured I should update.

**Comment by TBlueF** [comment]
This got fixed in 3.0
