### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by kajikaferus** [BlueMap-Minecraft/BlueMap#115]
it says that it's missing resources but it doesnt tell me what. i added the api, i've accepted the core thing and i dont know what im missing

**Comment by TBlueF** [comment]
Hey,

the message you are referring to is only showing when you have not changed `accept-download: false` to `true` in your `core.conf`.
You said you did that already? Then please double check you saved the config correctly :)

For more support, please visit our [discord](https://discord.gg/zmkyJa3)! We can help you much better there.
