### ISSUE TITLE
Custom or Minecraft icons for markers

### ISSUE THREAD

**Issue by MrFreasy** [BlueMap-Minecraft/BlueMap#116]
I'd like to customize the marker positioned on the map. For example, I have a world where there are located castles to conquere, locations where there are boss to fight, mining areas and so on. In this case I'd like to set different icons to see it clearer.

It would also be interessant that players shows their skin!

**Comment by TBlueF** [comment]
All this is already possible with BlueMap! :)
For support on how to use these features, please visit our [discord](https://discord.gg/zmkyJa3)!
