### ISSUE TITLE
Bluemap does not register Multiverse Loaded worlds

### ISSUE THREAD

**Issue by GoldenGamerLP** [BlueMap-Minecraft/BlueMap#117]
![image](https://user-images.githubusercontent.com/65727384/97906610-448cec80-1d44-11eb-9d38-391fadd78dbc.png)
If i wanna load a world that was loaded through Multiverse, then bluemap says that the map is existing.. The picture shows it

I use PurPur latest version from Jenkins

**Comment by TBlueF** [comment]
You need to add a map with your world in the `render.conf`.
Please visit our [discord](https://discord.gg/zmkyJa3) for support! :)

**Comment by GoldenGamerLP** [comment]
Thank you ^^ I leave a good review for the support here :D
