### ISSUE TITLE
Portal block Hud enhancement.

### ISSUE THREAD

**Issue by dogdie233** [BlueMap-Minecraft/BlueMap#118]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When I select a portal block, I can view the target location of the portal, and click the Teleport button to teleport the camera to the corresponding world and location.

![image](https://user-images.githubusercontent.com/42267840/98456606-b2a93780-21ba-11eb-90fe-cbeeaee585e1.png)
*Looks like this (Just modified the DOM)*

**Comment by TBlueF** [comment]
The idea is interesting, but i see some issues with implementing this:

- We can calculate the theoretical position of the portals just multiplying / dividing the coordinates by 8 ... but the actual portal will not always be at that exact position in the other world. Searching for the portal-structure (like minecraft does it) is very hard and complicated to implement and would mean extra data somewhere either in the model or in an extra file that the browser has to fetch..

- BlueMap currently does not really know the Dimension-Type of a map (overworld/nether/end). It just knows the folder-path of the region-files and the sky-color ... nothing more is needed. But for this feature that information would be needed, which makes everything (configuration and handling with maps) more complicated..

- There can be multiple maps of a world in theory.. how do we know to which map it should teleport in that case?

I think this is too small of an improvement for the amount of effort that is needed to implement it. **Also it would be totally possible to create a similar feature by making a plugin** that uses BlueMap's API to create a marker on each portal that teleports you to the other side of the portal when you click on it. So i think that would be the preferred way :)

**Comment by Sch1nken** [comment]
Additionally, Portals can teleport to and from more than one portal at once and I belive even when correctly implementing the minecraft formular for portal calculation that there would be one big issue left:
When entering a portal it does matter on which block you're standing (imagine a basic 2 wide portal), both blocks could in theory teleport you to a different portal. Also you could only stand in half way (from either side) and that could give you 4 more portal locations.

It's a bit hardish to explain clearly, so take a look over here: https://www.youtube.com/watch?v=eBYmcfWAbm8

I know this is probably an edge case, but yeah. I really like the plugin idea as that would eliminate a lot of problems.

**Comment by TBlueF** [comment]
Closing this with the conclusion that it should be a feature implemented by a plugin rather than bluemap itself.
