### ISSUE TITLE
Can you add a first perspective 能不能加个第一视角

### ISSUE THREAD

**Issue by msj20080623** [BlueMap-Minecraft/BlueMap#119]
English：
1. I hope to develop a first view. You can press WASD, or press space and shift to move. Because the current version of the mine and roofed buildings can't get in.
2. Hope to develop a follower, which can enter the player's perspective like the bystander mode, and follow their movement and movement perspective.
Chinese：
1.希望能开发一个第一视角，可以按wasd，还可以按空格和shift移动。因为现在的版本矿洞和有屋顶的建筑进不去。
2.希望能开发一个跟随，可以像旁观者模式一样进入玩家视角，跟随他们运动和移动视角。

**Comment by msj20080623** [comment]
Don't forget how players follow in and out of other worlds (dimensions)

**Comment by TBlueF** [comment]
1. What you mean are probably free-flight-controls. They are already on the [TODO-List](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true) (Issue #108)

2. I can add this, but it will only update about every second for now. More frequent updates to a player-position are not feasible with the current method.

I added a note for the 2. bullet to #108 and i see if this can be added with that :)
