### ISSUE TITLE
Hide Players in Light Levels

### ISSUE THREAD

**Issue by Brickgard** [BlueMap-Minecraft/BlueMap#120]
In Dynmap (I'm sure you're sick of the comparisons, my apologies) there is an option to "hide a player from appearing on the map if they are in a sky-light level less than: [integer]" allowing shadows, overhangs and underground.
For servers with a PvP focus or players concerned about stealth/privacy, this has been an excellent feature.

It would be greatly appreciated to be able to set a "sky light" level required for players to appear on the map, so when indoors or under cover their location isn't revealed.
Many thanks for your time and consideration!

**Comment by TBlueF** [comment]
Implemented in 3.4
