### ISSUE TITLE
Floating objects render with lowres non existant body under

### ISSUE THREAD

**Issue by MaybeJulien** [BlueMap-Minecraft/BlueMap#127]
BlueMap Version: 1.3.0
git-paper-386 1.16.4-R0.1-SNAPSHOT

I am using:
Nothing but the raw settings

**Description:**
Basically, if you have a floating body, it doesn't want to render it empty under and actually just makes a sorta weird thing under. Just look at this https://imgur.com/a/ZCdLK8i

**Comment by TBlueF** [comment]
Duplicate of #13 :)
