### ISSUE TITLE
Overhang causes weird artifact

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#13]
(Not sure if you're taking rendering bugs yet, so here's an early one in case you do. I got more to report if you do take them.)
Big overhangs of blocks seem to cause some sort of artifact where it looks like the low res map is being rendered in some way even though it shouldn't be.

Here's an example.

![image](https://user-images.githubusercontent.com/11007080/72460455-bc455700-37c4-11ea-988e-4b09aeb981f2.png)

There is not high terrain that could cause that lowres patch behind the tree, and it rotates as I rotate around the view.

**Comment by TBlueF** [comment]
This is a known issue:
Basically the hires-model is rendered "over" the lowres-model, so everywhere where there is no hires-model you can see the lowres-model.. 
I think i can clip the lowres-model where the hires is loaded to resolve this issue, but i need to learn how to use shaders to do that xD
This is further back in the TODO currently..

**Comment by ewized** [comment]
Would like to add a few more screen shots...

One issue is void maps where the ground is not at zero.

The other is overhangs that are over structures.

![overhang-rendering-bug](https://user-images.githubusercontent.com/1458852/72623607-52c76480-38fa-11ea-812f-8f8e75b04c85.PNG)
![void-rendering-bug](https://user-images.githubusercontent.com/1458852/72623608-535ffb00-38fa-11ea-8dd0-ff58bf312ade.PNG)

**Comment by MaybeJulien** [comment]
Any idea on when this issue will be resolved?

**Comment by TBlueF** [comment]
@MaybeJulien I am not doing ETA's but very likely with the next bigger release, since this ticket is already in the `In progress` column: https://github.com/BlueMap-Minecraft/BlueMap/projects/1#card-47810763

**Comment by TBlueF** [comment]
Fixed in 1.4.0 :)
