### ISSUE TITLE
Ability to customise HTML / CSS

### ISSUE THREAD

**Issue by OskarZyg** [BlueMap-Minecraft/BlueMap#131]
**Is your feature request related to a problem? Please describe.**
I would like an option to customise CSS/HTML.

**Describe the solution you'd like**
Some servers would like to customise their BlueMap website to fit their style/theme. There should be a simple way to customise text / certain widgets with the power of HTML and CSS.

**Comment by TBlueF** [comment]
Summarizing the discussion from discord for everyone:
You can easily edit/add to the css in the webroot.
If you need to change more of the web-app, cloning the repo and compiling your own version is the way to go :)

**Comment by VityaSchel** [comment]
I'm changing "styles": [] in settings.json but it gets overwritten after `bluemap reload light`
upd: figured it out, I needed to change config/bluemap/webapp.conf not bluemap/web/settings.json

**Comment by TechnicJelle** [comment]
This is already possible!
I have written a guide for it here: https://bluemap.bluecolored.de/community/Customisation.html

BlueMap does not use JSON files for configuration. Only for implementation details. Files you should never manually touch.
BlueMap's config files are .conf (HOCON) files. And they are located in BlueMap's config folder. Here is a guide on where to find those: https://bluemap.bluecolored.de/wiki/getting-started/Installation.html#the-config-files

Also, please do not comment on an issue that has been closed for years.
You can ask for help setting up BlueMap in [our Discord server](https://discord.gg/zmkyJa3).
