### ISSUE TITLE
Reverse Proxy Support

### ISSUE THREAD

**Issue by DaniGTA** [BlueMap-Minecraft/BlueMap#134]
**BlueMap Version: BlueMap-1.3.0-spigot**

I am using:
- [ ] mods (on the rendered world)
- [ ] resourcepacks (in bluemaps `config/resourcepack` folder)

**Description:**
*Current State:*

Use a Reverse proxy like Nginx:

nginx.conf

```
server {
	listen 80;

	location ^~ /mc/bluemap {
		rewrite ^/mc/bluemap/(.*) /$1 break;
		proxy_pass http://127.0.0.1:8100;
	}
}
```

Bluemap response:

```
404 - Not Found
BlueMap v1.3.0
```

**Comment by TBlueF** [comment]
Hey, this is not an issue with bluemap but an issue with your nginx configuration, since there are multiple servers that are already using BlueMap with a reverse-proxy successfully.

Maybe try it like this:
```nginx
location ~/mc/bluemap(.*)$ {
    proxy_pass http://localhost:8100$1;
}
```
