### ISSUE TITLE
Feature request: add medium res

### ISSUE THREAD

**Issue by supsm** [BlueMap-Minecraft/BlueMap#137]
**Is your feature request related to a problem? Please describe.**
I think the transition between lowres and highres is a bit harsh, and it looks a bit weird, especially when I'm zoomed in, and the chunks are still rendering.

**Describe the solution you'd like**
Add a medium res to act as an in between for highres and lowres, so it looks a bit better.

**Comment by TBlueF** [comment]
Can you please elaborate how you'd expect the medium-res to work? 
How would the model look like exactly?

**Comment by supsm** [comment]
Probably a more detailed version of the low res (more triangles ig), which would be rendered before the low res. Kinda imagine like zooming out in the high-res, then pretend that's the medium res...

**Comment by TBlueF** [comment]
You can already change the resolution of the lowres model by adding some configuration (https://github.com/BlueMap-Minecraft/BlueMap/wiki/Configuration/5a662579381d8fc67ff023c864609de798b3aa58#advanced) 
This will not add a second layer though.
There is already improvements planned on the TODO that should improve the look of the lowres-model without adding an additional layer. So i think we should stick to that plan.
*(It's further down on the TODO though)*

**Comment by supsm** [comment]
ok, that works.
