### ISSUE TITLE
Reorganize file-structure for maps and markers

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#138]
This change intends to make maps more portable and separate from each other. Enabling things like merging multiple maps from multiple systems onto one web-app.

- [x] Give each map its own `settings.json`
- [x] Give each map its own `textures.json`
- [x] The original `settings.json` is only for listing all maps and web-app settings like cookies
- [x] Move the live-api to the map-"folders" as well to have an interface per map to makes live markers with multi-server environments possible
- [x] Give each map its own `markers.json`
- [x] Add wrapper around the tile-geometry to be able to add metadata in the future, like sign-texts and generated extra-textures

**Comment by DreiMu** [comment]
isn't this `module: webapp` too?

**Comment by TBlueF** [comment]
Implemented in 2.0
