### ISSUE TITLE
Client Visual Bugs IOS Chrome

### ISSUE THREAD

**Issue by EsserGaming** [BlueMap-Minecraft/BlueMap#139]
**BlueMap Version:**
Not my server so idk

I am using:
- IOS
- Chrome
**Description:**
*When I opened the worlds drop down (it had 5 options) there would be "invisible" lines in front of the map, and it was intruding the map too. Picture below*![Uploading 105297785...]

**Comment by TBlueF** [comment]
@EsserGaming I don't see a picture, which would be very helpful here ^^

**Comment by EsserGaming** [comment]
Oh, I thought it didn't publish. Cause the app crashed when I posted it. Here ya go ![image](https://user-images.githubusercontent.com/36900138/105434764-ca248800-5c21-11eb-8614-2985bc6f21a4.jpeg)

**Comment by TBlueF** [comment]
Those are the the css shadow effect around the menu that your browser fails to repaint when the menu moves up..
I am very certain this is your browser being weird.
I am closing this now, because the web-app rewrite i am currently working on should fix that :)
