### ISSUE TITLE
[CLI] Incremental update

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#14]
Currently it looks like the CLI will rerender the whole world if it didn't finish previously, or something has changed. It would be great if it could instead detect what hasn't changed since the last render of a specific tile.

**Comment by TBlueF** [comment]
So if you let the render run completely, the next time you run it it will already only render chunks with a newer timestamp than the previous render. But this timestamp is only saved if the render has completed. 

I might add a feature that saves the render process in a certain interval so if it crashes or you cancel the render, you can choose to continue from the last saved render-state.

**Comment by TBlueF** [comment]
Added with b7db58461fb4334d07afc91c7f6803528cf461a1
