### ISSUE TITLE
Custom resource pack folder

### ISSUE THREAD

**Issue by ErythroCraft** [BlueMap-Minecraft/BlueMap#141]
Hello

How I can setup an custom resource pack folder?

e.g. 
./xx/xx/pack.zip
or
http://..../pack.zip

**Comment by TBlueF** [comment]
https://github.com/BlueMap-Minecraft/BlueMap/wiki/Installing-resource-packs
Please consider using our discord to get support for BlueMap instead of the github-tickets :)
