### ISSUE TITLE
Polished Blackstone sides do not render when behind a Polished Blackstone Slab [bottom] 1.3.0-fabric-1.16.4

### ISSUE THREAD

**Issue by RossosHEX** [BlueMap-Minecraft/BlueMap#144]
**BlueMap Version:**
BlueMap-1.3.0-fabric-1.16.4.jar
Server on 1.16.3

**Description:**

Polished Blackstone sides do not render when behind a Polished Blackstone Slab [bottom]

![2021-01-25_17 52 23](https://user-images.githubusercontent.com/8318353/106335153-e913c180-6294-11eb-9f4d-06736f9712b2.jpg)
![snap003070](https://user-images.githubusercontent.com/8318353/106335165-f0d36600-6294-11eb-80ef-c28defc11a56.jpg)
![snap003071](https://user-images.githubusercontent.com/8318353/106335177-f335c000-6294-11eb-894a-c6aaa1bd71cc.jpg)

**Comment by TBlueF** [comment]
Unfortunately i can not reproduce this issue..
![image](https://user-images.githubusercontent.com/10765470/106341422-8bd03e00-629d-11eb-9e8e-5c8b6e99ecaf.png)
If you want me to give it another try, you can send me the region-file of your world that is including that building and your `render.conf` :)

You can find the region-file using bluemaps debug option in the webapp menu, then clicking on the building and it displays the region-files name -> `<worldfolder>/region/<regionfile>.mca`

**Comment by RossosHEX** [comment]
I have requested the config and mca files from the server admin.

![snap003109](https://user-images.githubusercontent.com/8318353/106400479-522b3e80-6427-11eb-94fb-2a2730fd14e7.jpg)

![2021-02-01_00 44 53](https://user-images.githubusercontent.com/8318353/106400497-63744b00-6427-11eb-822a-516dcdf9108a.png)

![2021-02-01_00 41 25](https://user-images.githubusercontent.com/8318353/106400519-8999eb00-6427-11eb-85c0-4f82e82046a7.png)

**Comment by RossosHEX** [comment]
After a few Client Side re-render triggers it fixed itself

![snap003110](https://user-images.githubusercontent.com/8318353/106717957-0fc15780-6609-11eb-9e1f-d339b70c8fb3.jpg)
