### ISSUE TITLE
Ignore unresolved texture references if they are unused by the model

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#147]
**Is your feature request related to a problem? Please describe.**
If an unresolved texture reference is found, but unused by the model, ignore it rather than erroring

**Describe the solution you'd like**
An example of this being a problem is in Mekanism, where a model parents `minecraft:cube_all` but replaces the model elements: https://github.com/mekanism/Mekanism/blob/654ff10e62004344a55265fc9f2b261f42ad2a15/src/main/resources/assets/mekanism/models/block/chemical_tank/base.json#L3
This works fine in Minecraft, but BlueMap errors when it cannot resolve `#all` from `cube_all`, resulting in the model itself to fail loading, which results in the blockstate variant to fail loading, which results in the block being invisible on the map.

I know this is technically an issue in Mekanism, however, it would be expected for the BlueMap model loader to treat these cases similarly to Minecraft's model loader, imo.

**Comment by TBlueF** [comment]
I agree, it definitely should not fail loading a resource because of an unused texture, it should be a small change so i might be able to sneak this in somewhere :)
