### ISSUE TITLE
Models are missing face shading

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#148]
**BlueMap Version:**
`1.3.0-forge-1.16.2`

**Description:**
Models rendered on the map lack directional shading on faces like is applied in Minecraft, sides being darker than the top, west/east being darker than north/south, and down being darker still.

![In-game screenshot](https://i.imgur.com/ncLaZvd.png)
![Map screenshot](https://i.imgur.com/uglZyjy.png)

**Comment by TBlueF** [comment]
I'll test around with adding some directional shades, if i manage to make something that looks good, i'll add it :)

**Comment by TBlueF** [comment]
One problem with adding those lights is blocks like tall grass.. 
if i add a directional light, tall-grass-blocks start looking very dark and not like ingame at all on bluemap:

left with directional-light, right current lighting
![image](https://user-images.githubusercontent.com/10765470/107057492-d1c45f00-67d3-11eb-8368-217e7a2859cc.png)

**Comment by ChloeDawn** [comment]
Model elements have a "shade" flag that defaults to true when absent, stuff like the grass cross model and torches set it to false. Possibly you could parse that?

**Comment by TBlueF** [comment]
Well, that however means that this is a breaking change that needs model-changes ... so it's not going to happen as soon as i thought ^^
