### ISSUE TITLE
Web-app does not load if live data is inaccessible

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#149]
**BlueMap Version:**
`1.3.0-forge-1.16.2`

I am using:
- [x] [mods (on the rendered world)](https://gist.github.com/ChloeDawn/c40f003a4347445f705f2ae4ffa81ec2)
- [x] [resourcepacks (in bluemaps `config/resourcepack` folder)](https://gist.github.com/ChloeDawn/668cf746d5cf54c84a9ccae13da6c78f)

**Description:**
When the internal server is down (proxy cannot resolve it), the web-app does not load at all, even though it theoretically has all of the tile data needed to render "offline". My goal with hosting it on my own web server like this is to have 100% up-time of the map during game server restarts/outages, yet this apparent dependency on live data makes this impossible.

Nginx snippet:
```nginx
location /map {
	alias /srv/map;
	index index.html;

	try_files $uri $uri/ =404;

	location ~/data/ {
		gzip_static always;
	}

	location ~/live/ {
		rewrite ^/map/?(.*)$ /$1 break;
		proxy_pass http://localhost:8100;
	}

	add_header Last-Modified $date_gmt;
	add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
	if_modified_since off;
	expires off;
	etag off;
	proxy_no_cache 1;
	proxy_cache_bypass 1;
}
```
Current test case (will keep offline for troubleshooting): https://mc.disaster.gay/map/

**Comment by ChloeDawn** [comment]
Update: It seems to work *sometimes*???

**Comment by TBlueF** [comment]
Looks to me like cloudflare is messing with you there... Sending a 502 for a file in the `data` folder ^^
![image](https://user-images.githubusercontent.com/10765470/106391371-4ae73f00-63ed-11eb-8db4-f8db600b8bc0.png)

**Edit:** I should add that the web-app is definitely not dependent on the live-data. I have had a lot of cases where live was not accessible but the map is working fine ... bluemaps [demo-map](https://bluecolored.de/bluemap/) is an example :)

**Comment by ChloeDawn** [comment]
Interesting... it works fine when the internal server is online, so I wonder if CloudFlare is doing some sort of compensation when it encounters a 502 from the proxy.

**Comment by ChloeDawn** [comment]
I explicitly defined `try_files $uri $uri/ =404;` for the `~/live/` location and now it seems to be working. Might be placebo though and I just fixed it by side effect. I'm not super experienced with web stuff heh.

**Comment by TBlueF** [comment]
I have no experience with cloudflare at all, so i can't really give any more info on that ^^'
I'll close this issue for now, since it seems to not be an issue with the web-app :)
