### ISSUE TITLE
Make it easier to render other dimensions

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#15]
Currently it's a bit unintuitive how to render other dimensions.

I have a world, that only contains a Nether map. This is not picked up. Instead what I have to do is copy the `level.dat` into the `DIM-1` folder, and point BlueMap towards that.

**Comment by TBlueF** [comment]
Ah yes, i missed that probably because i only tested other dimensions with sponge and sponge organizes its dimensions as individual worlds *(i think?)*

**Comment by TBlueF** [comment]
@Katrix
So with ee384322d748e8938e4daabb901d5240c3e00acb it will now search in the parent folder for the level.dat if it doesn't find one in the world folder, so you don't have to copy that.
You will still need to configure the `world/DIM-1` folder.
I think that is a cleaner and more flexible solution than making a "dimension" configuration or something.
What do you think? Is it easy enough that way?

**Comment by Katrix** [comment]
Yeah, seems like a good solution, so closing this issue.
