### ISSUE TITLE
Block model offset definitions

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#150]
**Is your feature request related to a problem? Please describe.**
Some mods offset their models during rendering, to allow a 3x3x3 cube model to render at an offset to the origin (A trick to work around model bound constraints). An example of this can be seen in Mekanism, with its advanced solar generator, which uses a standard blockstate and model, but programmatically offsets the model during rendering to allow a 3x3x3 cube model rendered at the floor to be offset upwards by one block.

![Screenshot](https://i.imgur.com/jnfVK2T.jpg)

**Describe the solution you'd like**
A way to define a position offset for a block's model

**Comment by TBlueF** [comment]
As already discussed in discord, it is possible to offset a model by defining a new model with the offset baked into the models elements directly, since bluemap does not care about model bound constraints.
Closing, since this should be sufficient enough for now :)
