### ISSUE TITLE
Absence of light occlusion

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#151]
I will preface by saying **I do not expect this to be fixed in the short term**, I am merely documenting it as a recognized lack of parity with the game engine's rendering.

**BlueMap Version:**
`1.3.0-forge-1.16.2`

I am using:
- [x] [mods (on the rendered world)](https://gist.github.com/ChloeDawn/c40f003a4347445f705f2ae4ffa81ec2)
- [x] [resourcepacks (in bluemaps `config/resourcepack` folder)](https://gist.github.com/ChloeDawn/668cf746d5cf54c84a9ccae13da6c78f)

**Description:**
There is an absence of light occlusion for blocks that would otherwise "cast a shadow" on terrain below, as can be seen in the below two comparison screenshots of a forested environment (using models from Better End).

![Game screenshot](https://i.imgur.com/CYJRDD5.jpg)
![Map screenshot](https://i.imgur.com/niJhHos.jpg)

**Comment by TBlueF** [comment]
Can you please specify what you exactly think is missing?

BlueMap already uses and displays light-data that is calculated and saved by minecraft:
![image](https://user-images.githubusercontent.com/10765470/106758877-55dee100-6632-11eb-871f-5af9056d9588.png)
That is for sunlight and block-light, and i believe minecraft is not adding much to that.

Note that your example images are from an end-dimension, which usually has no sunlight. Also it has an `ambientLight: 0.6` setting by default in bluemap: Ambient-Light greatly lightens up shadows, which might contribute to the difference you are seeing in your comparison. *(Next to missing smooth-lighting and the "emissive textures" you described in #152)*

**Comment by TBlueF** [comment]
I'll close that for now. Feel free to reopen it when you can provide the requested information (see my comment above) :)
