### ISSUE TITLE
Emissive model support (as a block property?)

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#152]
**Is your feature request related to a problem? Please describe.**
Some blocks in modded Minecraft use emissive textures. Whilst some use emissive *overlays*, I imagine layering like this would be quite a pain to implement an API for, so all I ask for is support for making an entire model emissive. An example of emissive models can be seen in #151

**Describe the solution you'd like**
A way to define a block/model as being emissive (full-bright)

**Comment by TBlueF** [comment]
How are those emissive properties usually declared by mods? Is this hardcoded or is there something we could read from a blockstate/model-file?

The easiest way to implement this in bluemap would be to somehow declare a specific texture as emissive in the maps `texture.json` .. the question would be how that declaration gets there.. Does it have to be manually configured?

**Comment by ChloeDawn** [comment]
I don't think there would be a good way to infer it from the block, I know for a fact OptiFine and the CTM mod have unique implementations. It would just be nice to have a block/texture property for it that can be manually set when making resource pack support.

**Comment by TBlueF** [comment]
Minecraft snapshot 24w33a introduced a vanilla way for emissive textures that was really easy to implement.
So that's how BlueMap will support emissive textures as well from now on (next release) :)

Implemented in bca6647670a8127b6fe74e5b2ca66a825066f8c8
