### ISSUE TITLE
I have multiple spigot servers How should i set it up

### ISSUE THREAD

**Issue by betwowt** [BlueMap-Minecraft/BlueMap#153]
For example, I want to set the map rendered by each spigot to be different, and finally view it on a web site

**Comment by TBlueF** [comment]
Support for multi-server setups will be added with this ticket: https://github.com/BlueMap-Minecraft/BlueMap/issues/138
Currently this is not possible without some major trickery..

*(Please consider using our discord for support in the future, githubs ticket system is a bad place for this :) )*
