### ISSUE TITLE
Support for custom biome colors added in 1.16.2

### ISSUE THREAD

**Issue by Orthestral** [BlueMap-Minecraft/BlueMap#156]
**Is your feature request related to a problem? Please describe.**
True custom data-driven biomes have been added in 1.16.2, utilized by a few plugins and datapacks. These biomes displayed on Bluemap get their custom tints replaced with a default green (Probably plains)

**Describe the solution you'd like**
Colors from custom biomes should be displayed properly in the render

**Comment by TBlueF** [comment]
A precondition to implement this is that this custom biome-info is somehow saved with the world. E.g. in the level.dat or within the chunk-files itself.

**Comment by Orthestral** [comment]
> A precondition to implement this is that this custom biome-info is somehow saved with the world. E.g. in the level.dat or within the chunk-files itself.

Biome id mapping is stored in level.dat
Biome borders are stored in chunk data
Custom biome data is stored in datapacks

**Comment by FrostBird347** [comment]
> Custom biome data is stored in datapacks

If it's difficult to obtain the biome data from the datapacks, then a temporary solution could be to allow users to manually specify the biome data through the world config.

**Comment by PortableGames** [comment]
I found this can be used as a temporary solution: https://github.com/StrangeOne101/Datapack-Bluemap-Generator

**Comment by TBlueF** [comment]
Implemented in 2.0
