### ISSUE TITLE
Support for Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by srnyx** [BlueMap-Minecraft/BlueMap#159]
Would be great if you could add support for https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric

That way I don't just see this: https://imgur.com/a/H70aH7v lol

**Comment by TBlueF** [comment]
See: https://github.com/BlueMap-Minecraft/BlueMap/wiki/Configuring-mods
