### ISSUE TITLE
Prevent sending information about players in disabled world

### ISSUE THREAD

**Issue by raywave** [BlueMap-Minecraft/BlueMap#163]
**Is your feature request related to a problem? Please describe.**
Currently, you can GET `/live/players`  to get all players' coordinates in all worlds (including disabled in config worlds), so everyone, who knows the basics of HTTP requests can write a simple script, that can, for example, get information about users in UHC world or just track all admins' actions. 

**Describe the solution you'd like**
It would be better if the server won't send any other players except players in enabled worlds.

**Comment by MRLokop** [comment]
up

**Comment by BRA1L0R** [comment]
also about players outside of world render limits

**Comment by TBlueF** [comment]
Implemented in 2.0
