### ISSUE TITLE
Skip existing tiles for rendering

### ISSUE THREAD

**Issue by Tarakesh83** [BlueMap-Minecraft/BlueMap#164]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Why do you want this feature

/bluemap render world always renders the full world including already existing tiles

**Describe the solution you'd like**

/bluemap render world should get an option to skip already existing tiles to speed up map generation if you have to cancel and restart a render

**Comment by TBlueF** [comment]
This now works in a similar way in the latest version :)
