### ISSUE TITLE
Republish plugin

### ISSUE THREAD

**Issue by Song-Xin233** [BlueMap-Minecraft/BlueMap#165]
Hi, I am a Minecraft server player in China. I like this plugin very much and it works very well on my server!
Can I republish this plugin to the largest Chinese game community: MCBBS.NET? I will follow your open source agreement and translate the relevant configuration files and Wiki of the plugin to Chinese. I will declare that this plugin belongs to you and indicate links to GitHub and Releases.
Looking forward to your reply! best wishes!

**Comment by TBlueF** [comment]
Hi, please make sure it's clear that your post/publish is not official, then you are good to go :)

**Comment by Song-Xin233** [comment]
very thx!
It's not an official website, it's a community of players!
