### ISSUE TITLE
Mouse scroll wheel behavior unusable for scaling the map

### ISSUE THREAD

**Issue by archonsd** [BlueMap-Minecraft/BlueMap#169]
**BlueMap Version:**
The one in the demo on your Github page

I am using:
None.  It's your demo server.

**Description:**
When I open the demo server you provide at https://bluecolored.de/bluemap/ the map is beautiful, but when I use the middle mouse button/scroll wheel (or a trackpad scroll gesture) it jumps from minimum height to maximum height, with nothing in between..  making scroll zoom useless.  If it's a setting, please indicate that in the docs.

**Comment by TBlueF** [comment]
Yes, that's an issue with some mice, especially smooth-scrolling mice.
I am currently re-writing the webapp, it should be fixed once that update releases :)

**Comment by TBlueF** [comment]
This should be fixed with 1.4.0 (demo map will update soon).
I'll close this, please reopen if the issue persists :)

**Comment by archonsd** [comment]
Thank you! I got tired of hearing from other players, "It works fine for me, it must be you." Lol

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
