### ISSUE TITLE
Config option to turn off automatic resumption after a server restart.

### ISSUE THREAD

**Issue by OJS05** [BlueMap-Minecraft/BlueMap#171]
Upon server restart, BlueMap renders resume and causes the server to lag to the point of crashing.

A config option to toggle whether on not BlueMap resumes after a restart.

**Comment by TBlueF** [comment]
If your servers lag or even crash during rendering, turn down the `renderThreadCount` in bluemaps `core.conf`!
E.g. set them to 1: `renderThreadCount: 1`.
That should fix your issue :)

About that config option: there is already a ticket that will add this: #126
So i will close this, as it is a duplicate :)
