### ISSUE TITLE
PNGs misnamed

### ISSUE THREAD

**Issue by SlimeDog** [BlueMap-Minecraft/BlueMap#172]
**BlueMap Version:** `BlueMap-1.3.1-spigot` on Spigot 1.16.5-3019 (and previous)

I am using:
- [ ] mods (on the rendered world)
- [ ] resourcepacks (in bluemaps `config/resourcepack` folder)

**Description:**
PNGs names are incorrect (or anyway, weird): *.png.png.
```
$ tree bluemap/
bluemap/
├── minecraft-client-1.16.jar
├── resourceExtensions.zip
├── rmstate
└── web
    ├── assets
    │   ├── burger.svg
    │   ├── compass.svg
    │   ├── night.svg
    │   ├── playerheads
    │   ├── poi.svg
    │   └── steve.png
    ├── data
    │   ├── images
    │   │   └── icons
    │   │       ├── cmiportal.png.png
    │   │       ├── cmiprison.png.png
    │   │       ├── factionhome.png.png
    │   │       ├── netherportal.png.png
    │   │       ├── townjail.png.png
    │   │       └── townspawn.png.png
```

**Comment by TBlueF** [comment]
That's an issue with the plugin that is adding those images / markers, not with bluemap itself :)

**Comment by TBlueF** [comment]
I'll close this, because its not a bluemap issue, but the author of `MCG Bluemap Essentials` is already notified ;)

**Comment by SlimeDog** [comment]
Thanks.
