### ISSUE TITLE
Bluemap behind Apache ReverseProxy

### ISSUE THREAD

**Issue by jannis6023** [BlueMap-Minecraft/BlueMap#178]
Hi together,
today I installed another Apache VHost as Reverse Proxy for our Bluemap. But there's one Problem: The site isn't loaded :/ but I can reach other sites on the Host as e.g. the Favicon or the 404 / Errorpages => The Connection is working...
But: I can't reach my Bluemap!
It's installed as a Spigot-Plugin. Directly connecting to port 8100 it's working pretty fine, but not using the Proxy...
Here's my VHost-Config:
```
<VirtualHost *:80>
ServerAdmin webmaster@localhost
ServerName map.myserver.eu
ProxyPreserveHost On
DocumentRoot /var/www/html
ProxyPass /.well-known !
ProxyPass / http://XXX.XXX.XXX.XXX:8100//
ProxyPassReverse / http://XXX.XXX.XXX.XXX:8100//
</VirtualHost>
```

Hope, anyone can help :)

**Comment by TBlueF** [comment]
Hey,
i don't know much about Apache tbh, so i'll have a hard time helping here..
Also this is a bad place for support, you'll get the most help for bluemap in our [discord](https://bluecolo.red/map-discord).
For apache config problems you might be even more successful asking in one of the many apache-communities out there :)
