### ISSUE TITLE
Suggestion - Chat Box

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#179]
I would like to suggest a chat-box.
I would _try_ and do this myself, but I do not know Java.
This could be similar to an in-game chatbox or one like Dynmap.
I think that this one feature would make this a super-amazing mod instead of just an amazing mod. As I said, I know it is possible as Dynmap does it. I believe that if you keep track of the IP's of the users on the server(along with their IGN/UUID), you can detect their IP on the website and put their username in the chat when they send messages. Of course with a VPN or multiple people on the same IP that would be an issue. But it would work most of the time.

Also, maybe make it so that you can see the messages sent in-game as little bubbles above the user on the map. There could be an option to turn this off in the config files as well as the chat box.

**Comment by TBlueF** [comment]
The chat feature has been discussed multiple times in discord:

I think a web-chat (sending chat messages from the web) is completely out-of-scope for a web-map plugin/mod. Also it would introduce A TON of problems starting with storing/logging/exposing ip's of users and ending with login/security features (which won't be added to bluemap: #105 & #132). That's why such a feature will not be added.

The only thing that i might add at some point in the far future is showing ingame-chat on the map.

Sorry, I hope this is not too bad news for you :)

**Comment by ghost** [comment]
Sorry, I am not in your Discord so I didn't know that it had already been discussed/rejected.
I also didn't see it on the Todo list.
The only reason I was asking is because I knew it was possible.
I feel like it would make this mod a bit better, but it is still one of my favourite mods.
And it isn't hard opening Dynmap as we have got chat enabled on that.
Maybe I will try and do this when I learn Java in the future and keep it as a private mod or do a PR.

**Comment by TBlueF** [comment]
No need to be sorry, you did nothing wrong! :D
It wasn't on the todo-list so you could not have seen it. I was just trying to explain why i am closing this so fast, and why i didn't want to start a new discussion about this ^^

**Comment by ghost** [comment]
I understand your reasons, but I would just like to ask, ___**IF**___ I make a working chatbox for it in the future, would you want me to keep that as a private copy?

**Comment by TBlueF** [comment]
I have absolutely nothing against bluemap forks / addons or anything like that, so no need to keep it private :)
However i will very likely **not** accept a pull-request that is adding a web-to-server chat-box to this "official" repo, for the same reasons as above ^^

**Comment by EsserGaming** [comment]
Having it at a plugin would be amazing :D
