### ISSUE TITLE
Create markers using signs

### ISSUE THREAD

**Issue by harrisbright** [BlueMap-Minecraft/BlueMap#180]
Similar to dynmap, enable players to create markers using signs. 

A player with the permission `bluemap.signs` can create a marker by placing a sign with the first line being `[bluemap]` and the following lines being the marker's label. When the sign is broken/destroyed the marker is also deleted.

**Comment by TBlueF** [comment]
Such a feature will not be added to bluemap itself, because it's a very server and implementation-specific feature, **but**:
Its totally possible for any developer to make an addon-plugin using [BlueMaps API](https://github.com/BlueMap-Minecraft/BlueMapAPI) that adds this feature! :)
