### ISSUE TITLE
Suggestion - List of Markers/Players

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#181]
This is another suggestion.
It would be nice if, on the list where you change dimensions, it showed the markers and the players.
Then when you click one, you get tped to that player(or whatever the relevant terms are for a web-map).
Maybe there could be an option in the config file as well to disable/enable this feature.
And yes, I am aware that if you click a player's head zoomed out or a marker, you go to them.

**Comment by TBlueF** [comment]
This already exists! :D A player-list and marker-list have both been added with the latest snapshot :) (Version 1.4.0)
Currently still on a test-demo but will soon release as a stable version: https://bluecolored.de/bluemap-test/ *(you cant see the player-list in that demo, but it is there if you install version 1.4.1 on your server)*

**Comment by ghost** [comment]
Oh. I didn't know that 🤦🏻
