### ISSUE TITLE
Feature request: Include default configuration files in the JAR

### ISSUE THREAD

**Issue by SlimeDog** [BlueMap-Minecraft/BlueMap#182]
**Is your feature request related to a problem? Please describe.**
Our typical workflow for a plugin update is
- Compare the configuration files in the JAR to a saved copy of those from the previous jar
- Stop the server
- Make any adjustments to the active configuration
- Update the plugin
- Start the server

BlueMap does not include the default configuration files in the JAR, so the process is more complicated than it needs to be:
- Stop the server
- Move the active configuration files, elsewhere
- Update the plugin
- Start the server; stop the server
- Save a copy of the generated configuration files, elsewhere
- Compare the generated files to the previously generated files
- Make adjustments to the temporarily-moved active configuration files
- Move the updated active configuration files back into plugins/BlueMap/
- Start the server

**Describe the solution you'd like**
Include the default configuration files in the JAR.

**Comment by TBlueF** [comment]
The configuration files **are** in the .jar file here: `BlueMap-1.4.2-spigot.jar\de\bluecolored\bluemap\` 
or you can just get them from here: 
https://github.com/BlueMap-Minecraft/BlueMap/tree/master/implementations/spigot/src/main/resources/de/bluecolored/bluemap
:)

Also i **always** describe all important config-changes in the "Updating from {version}" section in the update-description, if there are any ^^

**Comment by SlimeDog** [comment]
_Mea culpa._ My search script wasn't looking for .conf, even though I know the four file names. It does now. Thanks.
