### ISSUE TITLE
Map file save location

### ISSUE THREAD

**Issue by L33B0B** [BlueMap-Minecraft/BlueMap#185]
**Is your feature request related to a problem? Please describe.**
Would or is it already possible to save the map files onto a different hard drive?

**Describe the solution you'd like**
Would like to save map files onto a seperate hard drive to save on disk I/O and space to help improve the performance of the overall minecraft server.

**Comment by TBlueF** [comment]
Yes thats already possible! :)
You can change the path to where bluemap saves the files in the `render.conf` (the `webroot` config-option) .. remember to also change the `webroot` in the `webserver.conf` accordingly (they should usually point to the same directory) :)
And make sure BlueMap has read/write permissions for that new directory ^^

Consider joining the discord or r/bluemap on reddit if you need more help :)

**Comment by WoutervanderLoopNL** [comment]
@TBlueF is it possible to save it on a network location? 

like `\\nas\folder\bluemap?`

if I set that location it creates a `nas` folter in the server root directory.

**Comment by TBlueF** [comment]
@WoutervanderLoopNL its probably not possible then 🤔 
Everything that acts like a normal folder / drive in your file-system should be possible, so a mounted drive or NFS should work ..
My guess now is that a network-location is different to that, and thus will not work..
