### ISSUE TITLE
Split CurseForge project into separate Forge and Fabric projects

### ISSUE THREAD

**Issue by Kage-Yami** [BlueMap-Minecraft/BlueMap#187]
**Is your feature request related to a problem? Please describe.**
CurseForge wasn't built to handle competing mod loaders (Forge and Fabric), and so gets a bit funky these days when a mod supports both. In particular (depending on upload order, I think), the CurseForge client can download the wrong version for a given profile. For instance, it downloaded the Fabric version for me (pulling in Fabric API as well) when I'm in a Forge profile.

Thankfully, it's easy enough to manually switch the version, and then delete Fabric API, but it's a bit of a nuisance. To top it off, the CurseForge client now says there's _always_ an update, because it thinks the Fabric version is newer than the Forge version.

**Describe the solution you'd like**
I suggest splitting the CurseForge project into two separate projects, each dedicated to either the Forge or Fabric versions. This should simplify downloading and modpack maintenance of the mod using the CurseForge client considerably. (As an example, Dynmap does this.)

[_Original suggestion on Discord_](https://discord.com/channels/665868367416131594/701507290200670238/829308876520030219)

**Comment by SettingDust** [comment]
> **Is your feature request related to a problem? Please describe.**
> CurseForge wasn't built to handle competing mod loaders (Forge and Fabric), and so gets a bit funky these days when a mod supports both. In particular (depending on upload order, I think), the CurseForge client can download the wrong version for a given profile. For instance, it downloaded the Fabric version for me (pulling in Fabric API as well) when I'm in a Forge profile.
> 
> Thankfully, it's easy enough to manually switch the version, and then delete Fabric API, but it's a bit of a nuisance. To top it off, the CurseForge client now says there's _always_ an update, because it thinks the Fabric version is newer than the Forge version.
> 
> **Describe the solution you'd like**
> I suggest splitting the CurseForge project into two separate projects, each dedicated to either the Forge or Fabric versions. This should simplify downloading and modpack maintenance of the mod using the CurseForge client considerably. (As an example, Dynmap does this.)
> 
> [_Original suggestion on Discord_](https://discord.com/channels/665868367416131594/701507290200670238/829308876520030219)

I think this is a bug of CF client.

**Comment by Ludi87** [comment]
Curseforge got updated to support the different modloaders, so as long files are marked correctly for forge/fabric they should work fine now.

**Comment by TBlueF** [comment]
Sooo, i guess this can close :)
Thanks!
