### ISSUE TITLE
[Suggestion] Zoom-in/out button

### ISSUE THREAD

**Issue by samdev-7** [BlueMap-Minecraft/BlueMap#188]
**Is your feature request related to a problem? Please describe.**
Some people don't use a mouse, they use the touchpad. What gets really annoying is zooming, most touchpads allow a two-finger zoom which is just annoying and hard to perform since it's designed to scroll up and down pages.

**Describe the solution you'd like**
Add a zoom-in and zoom-out button to the webpage.

**Comment by samdev-7** [comment]
Also, some touchpads and browsers have a build in zoom option, where you can pinch two fingers to adjust the zoom. Currently what happens is it zooms the entire webpage which results in the buttons going out of the screen. Would be nice to add support to that zoom function, as multiple real-world maps supports that function.

**Comment by TBlueF** [comment]
You can use e.g. `+`/`-` on the numpad to zoom. Is that not enough?

The second suggestion about adding support for the touchpad-pinch-zoom i'd like to add! The problem i have with that currently, is that i have no way to test this, because i don't own such a trackpad ^^'

**Comment by samdev-7** [comment]
By zoming the browser window, the gui also gets zoomed, which blocks view.

Chrome also has some developer tools about simulation touchpad zoom, mabye you could look into that?

I really love BlueMap and it would be better if zooming was easier :)

**Comment by TBlueF** [comment]
> By zoming the browser window, the gui also gets zoomed, which blocks view.

What do you mean? i was not talking about zooming the browser window ^^
Not `Ctrl`+`+/-` ... just `+/-` ! :D
That's a built-in hotkey to zoom on bluemap! :)

**Comment by samdev-7** [comment]
Oh, that's great! But I am unable to use it since I do not have numbad. Would be amazing if it worked with the normal +, -

*Most touchpad users (Laptop) don't have a numpad*

**Comment by TBlueF** [comment]
hmm true! 🤔 Do you have `Ins/Home`? .. they would work too for zooming ...
Else i should probably add something on the basic keyboard as well..

**Comment by samdev-7** [comment]
I'd personally suggest the `=` for zooming in (Since pressing shift is confusing) and `-` for zoom out.

**Comment by TBlueF** [comment]
You need to consider that keyboard-layouts vary **a lot** between different countries ^^

**Comment by samdev-7** [comment]
A zoom in/out button would be easier 😊

**Comment by Toys0125** [comment]
You might look up the map api that google uses that browsers can detect that it's a map and hook into that.
[https://developers.google.com/maps/documentation/javascript/examples/interaction-cooperative](url)

**Comment by TBlueF** [comment]
Implemented with e06ff811950606c63c2bf22dd80429dd711da46d
