### ISSUE TITLE
Option to disable Free Flight Mode in Config

### ISSUE THREAD

**Issue by Exophobias** [BlueMap-Minecraft/BlueMap#189]
**Is your feature request related to a problem? Please describe.**
This feature is a problem for my server. We have events where certain builds and areas are hidden and meant to be found by players. Having a spectator view that all can access defeats that purpose.

**Describe the solution you'd like**
I would like to have an option in the BlueMap config or the web/data/settings.json to have the option to disable the free flight button.

Thanks! :)

**Comment by TBlueF** [comment]
That option is planned, 
but note that your players will then still theoretically be able to modify or trick bluemap into moving the camera underground.

**Comment by TBlueF** [comment]
Added in 1.5.5
