### ISSUE TITLE
Modern Industrialization does not render

### ISSUE THREAD

**Issue by Shalar** [BlueMap-Minecraft/BlueMap#190]
**BlueMap Version:**
*Full version including the target, e.g. `1.0.0-fabric-1.16.1`*
BlueMap-1.4.2-fabric-1.16.4

I am using:
- [ All of Fabric 3 modpack] mods (on the rendered world)
- [ ./charm-fabric-1.16.5-2.3.2.jar
./TacoCraft-1.5.1+mc.1.16.5.jar
./wild_explorer-1.3.3.jar
./Modern-Industrialization-0.3.16.jar
./traverse-3.3.2.jar
./biome-makeover-1.16.5-1.3.6.jar
./terrestria-2.2.0.jar
./TechReborn-1.16-3.8.2+build.220.jar
./appliedenergistics2-fabric-8.2.0-alpha.3.jar
./blockus-2.1.1+1.16.5.jar
./Flonters-1.1.1+1.16.2.jar
./Croptopia-1.16.4-5-FABRIC-1.3.3.jar
./battletowers-3.3.4-1.16.4.jar
./wraith-waystones-1.1.1.1.jar
./byg-1.1.7.jar
./bewitchment-1.16.5-8.jar
./sandwichable-1.2-beta5--1.16.5.jar
./wraith-croptosis-1.1.0.jar
./WoodsAndMires-1.0.4+1.16.3.jar] resourcepacks (in `config/bluemap/resourcepacks` folder)

**Description:**
*Describe the bug in full detail, including a way to reproduce it.
Sometimes a full log of your server-startup or a crash-report can be of much help!*
Dropping Modern Industrialization into the resource packs folder does not let it render the ores generated by it (and possibly other blocks.)

Does Bluemap need individual blockstate json, and model json for blocks? Looking through the jar I do not see these, like in the other mods. If this is the case is there a way to have Bluemap dump them from the client, ala DynmapBlockScan?

(I am loving this mapping mod by the way. I never realized I wanted a 3D map until I saw this; now I don't want any other map.)

**Comment by TBlueF** [comment]
Hey,

so i don't know how Modern Industrialization handles it's blocks, but BlueMap needs (as you said) the blockstate and model json's ..
MI is not providing them, so bluemap can't render the blocks.

I don't know if dumping the models from the client would be possible in this case, anyways i sadly don't have the time to make a tool that does that ^^' 
Generally speaking: I won't focus on supporting specific mods/plugins with bluemap, but rather try to create the tools and possibilities for others to create such integrations :)

Theoretically anyone can already develop a tool that generates the missing models, or even easier: just create a resource-pack with the missing blockstate.json's and model.json's for that mod manually :) 
So this is the way to go here!

Glad you like the map! <3
