### ISSUE TITLE
Optionally account for block light in culling

### ISSUE THREAD

**Issue by ChloeDawn** [BlueMap-Minecraft/BlueMap#191]
**Is your feature request related to a problem? Please describe.**
Underground structures and deep internals of surface buildings are occluded when sky light reaches 0.

**Describe the solution you'd like**
An option to include block light checks in culling calculations, to allow tiles with a block light level of more than 0 to not be culled. This would have the side effect of rendering mineshafts and strongholds, but I feel this would be a desired side-effect given the primary desired effect. The only undesired side-effect may be the rendering of lava pools. But overall this would be far more performant than rendering all "cave" tiles.

**Comment by TBlueF** [comment]
Added in 1.6.1
