### ISSUE TITLE
Toggling the Nether roof

### ISSUE THREAD

**Issue by kayvanbree** [BlueMap-Minecraft/BlueMap#195]
**Is your feature request related to a problem? Please describe.**
We build on the Nether roof on our server. At the moment (as far as I know) we can either choose to have nice rendering settings for the Nether itself, or for the roof, but not both. 

**Describe the solution you'd like**
A toggle in the frontend to show or hide the Nether roof (or some pre-configured height), so you can switch between showing the Nether itself, or its roof.

**Comment by TBlueF** [comment]
You can already achieve a similar effect by rendering 2 maps of the nether, one with roof and one without ... if you switch between those maps in the web-app, the camera should remain on the same position.

**Comment by TBlueF** [comment]
Closing this, with the above suggested solution :)

**Comment by kayvanbree** [comment]
I forgot to respond. This indeed did the trick. Thanks!

**Comment by SaiCode-DEV** [comment]
A good solution might be to use the dalight swich to swich between the with/without roof version. but no idea if this would be possibe to create
