### ISSUE TITLE
Fabric 1.14.4 wanted

### ISSUE THREAD

**Issue by ljm12914** [BlueMap-Minecraft/BlueMap#197]
I run a 1.14.4 fabric server and I don't have a chance to update its version due to lots of feature loss(in redstone and bugs😂).
Could you provide a fabric 1.14.4 version?I will definitely apperciate it.

**Comment by TBlueF** [comment]
I won't do a backport to 1.14.4 fabric, sorry..
There is just too much on the TODO, i can't start supporting old versions now :D
