### ISSUE TITLE
Hide controls / nogui mode

### ISSUE THREAD

**Issue by EnKrypt** [BlueMap-Minecraft/BlueMap#199]
**Is your feature request related to a problem? Please describe.**
Would love to have a URL with a param or flag that removes the UI controls. This is useful when embedding as a background or a static page that only live updates from a fixed position. Would love to have this.

**Describe the solution you'd like**
A URL with a param or flag that removes the UI controls from the web application. This would load the view from the position as per the URL.

**Comment by TBlueF** [comment]
I think i will not add a no-gui option to bluemap itself. I am trying to make bluemap plug-and play for simple and standard use-cases, and on the other hand extensible by developers for their special use cases and bigger servers.
And i think the latter applies to this :)

I think the best way you can archive this yourself is by cloning the [BlueMapVue](https://github.com/BlueMap-Minecraft/BlueMapVue) repository and removing the UI elements. (requires very little VueJS knowledge)
Or even use [BlueMapWeb](https://github.com/BlueMap-Minecraft/BlueMapWeb) to make a slim and simple JS-App yourself that does exactly what you want it to do :) (requires a bit more js-knowledge, you can check out [this](https://github.com/BlueMap-Minecraft/BlueMapVue/blob/master/src/js/BlueMapApp.js#L48) as an example to find out how to use BlueMapWeb)

**Comment by TBlueF** [comment]
Also: If you have questions about this, i'll be happy to answer them on our [discord](https://discord.gg/zmkyJa3) :)

**Comment by EnKrypt** [comment]
I thought you'd want to support this as it would probably yield easier marketing, but no worries.

To anyone who stumbles across this in the future, you just need to hide the element that has the `control-bar` class. I added this to index.html (checks if the page is inside an iframe)

```html
<script>
    if (window.self !== window.top) {
        window.addEventListener('load', function () {
            document.getElementsByClassName('control-bar')[0].style =
                'display: none;';
        });
    }
</script>
```
