### ISSUE TITLE
mobile support

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#2]
When I tried to connect to the mobile phone, certain movements that were only available with the mouse didn't work, and there was a big problem with it. Can mobile support be added?

**Comment by TBlueF** [comment]
I will add that on the todo, might take a while though until i get to it.

**Comment by TBlueF** [comment]
So.. 
i added this with c5485e665767af3250ee3965725b2a15cba100a4
Will be included in the next release :)
