### ISSUE TITLE
Drop the camera at the spawn position when opening a map

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#20]
Currently when you change maps, or open the website it drops you at 0,0. This works fine in some cases. In other cases it can drop the camera in a black void, with the nearest terrain a thousand blocks away or more. Dropping the camera at the world spawn would be a better solution.

**Comment by TBlueF** [comment]
Ha! I am working on this in this exact moment ^^

**Comment by TBlueF** [comment]
Closed with a56b610afb4296aef48b1e360cb89d83f1f08a6b
