### ISSUE TITLE
Add a web app manifest.json

### ISSUE THREAD

**Issue by ALiangLiang** [BlueMap-Minecraft/BlueMap#200]
**Is your feature request related to a problem? Please describe.**

Add Web App manifest.json to allow users to "install" it.

**Describe the solution you'd like**

I want my players open bluemap by click it on taskbar or desktop.

Ref: [https://developer.mozilla.org/en-US/docs/Web/Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest)

**Comment by birdhimself** [comment]
There's a [PWA plugin for Vue CLI](https://cli.vuejs.org/core-plugins/pwa.html#configuration) that generates a `manifest.json` automatically. It also generates a service worker, which might be a bit overkill (considering the map can't be used offline anyways).

Maybe [the webpack plugin webpack-pwa-manifest](https://www.npmjs.com/package/webpack-pwa-manifest) is all that's needed (haven't tried the plugin yet).

@ALiangLiang Note that in Microsoft Edge (and afaik Google Chrome as well) you can "install" any website as an app (even if it doesn't specify a manifest) by clicking on the hamburger menu in the browser and then select "Apps" => "Install this site as an app".

**Comment by TBlueF** [comment]
Implemented in 3.4
