### ISSUE TITLE
API feature to prevent listing of marker sets 

### ISSUE THREAD

**Issue by n-aspen** [BlueMap-Minecraft/BlueMap#201]
**Is your feature request related to a problem? Please describe.**
Some marker sets I'd like to create either don't need to or would be affected negatively by listing or teleporting to individual markers. 

**Describe the solution you'd like**
I'd like to be able to change some marker sets with the API so that you can't list their markers on the web page. That would remove the ability for players to view the specific markers contained inside and their ability to teleport to them on the map.

**Comment by TBlueF** [comment]
Implemented with 87c868b.
Markers can be unlisted individually.
If a marker-set only contains unlisted markers **and** is not toggleable, it will be hidden from the list as well.
