### ISSUE TITLE
Bluemap not loading anymore after adding a new marker 

### ISSUE THREAD

**Issue by braydofficial** [BlueMap-Minecraft/BlueMap#202]
### What i did / Steps to reproduce
I tried to add a new marker, which worked perfectly in the past with previous markers, but after this I get an error and can't use the web-app anymore. 

### Expected result
Marker should be added to the map and the web map should work as usual.

### Actual result
Web map isn't working anymore and the following error is shown: 
```
Error
Initialization: TypeError: undefined is not an object (evaluating 'n.iconAnchor.x')
```
Removing the added marker doesn't get the web map back as usual.

### Context
**BlueMap Version:** 1.4.2

Add more context here!
- Server is running on Spigot 1.17 Prerelease 1, which worked perfectly fine with Bluemap, even if the version is not yet supported by Bluemap until adding the marker. After adding the marker, the issue described above appeared.
- Platform the server is running on is Ubuntu Server 18.04 LTS, dedicated server
- Server is running without any mods

**Comment by TBlueF** [comment]
Pretty sure there is a missing "x" coordinate in some markers `iconAnchor`. Would it be possible for you to provide the `markers.json`?

**Comment by braydofficial** [comment]
> Pretty sure there is a missing "x" coordinate in some markers `iconAnchor`. Would it be possible for you to provide the `markers.json`?

Of course. See below. I tested it again, after I got it to work by deleting all render data and rendering the map again, but as soon as I added a marker back I get the error again.
```
{
  "markerSets": [
    {
      "id": "markers",
      "label": "Markers",
      "toggleable": true,
      "defaultHide": false,
      "marker": [
        {
          "id": "mine",
          "type": "poi",
          "map": "world",
          "position": {
            "x": 566.875,
            "y": 76.0,
            "z": -2020.617
          },
          "minDistance": 0.0,
          "maxDistance": 100000.0,
          "label": "Mine",
          "newTab": true,
          "icon": "assets/poi.svg",
          "anchor": {
            "x": 25,
            "y": 45
          }
        }
      ]
    }
  ]
}
```

**Comment by TBlueF** [comment]
@thisdudeisvegan I can not reproduce this, 
I setup a fresh Spigot 1.17 server, added BlueMap-1.4.2, rendered the spawn, checked the web-app (all fine)
then i added a `markers.json` with the exact content you just posted, and reloaded the web-app:

![image](https://user-images.githubusercontent.com/10765470/121819014-1df44400-cc8b-11eb-91df-41351f0a7cee.png)
Working fine without any error in the console.

Do you have any other ideas how i can reproduce this? :)

**Comment by braydofficial** [comment]
> @thisdudeisvegan I can not reproduce this,
> I setup a fresh Spigot 1.17 server, added BlueMap-1.4.2, rendered the spawn, checked the web-app (all fine)
> then i added a `markers.json` with the exact content you just posted, and reloaded the web-app:
> 
> ![image](https://user-images.githubusercontent.com/10765470/121819014-1df44400-cc8b-11eb-91df-41351f0a7cee.png)
> Working fine without any error in the console.
> 
> Do you have any other ideas how i can reproduce this? :)

Weird. Also, somehow your Webapp is looking different than mine, while I've also installed 1.4.2.
<img width="1456" alt="Bildschirmfoto 2021-06-13 um 21 10 48" src="https://user-images.githubusercontent.com/55672814/121819178-06698b00-cc8c-11eb-96bf-42f194abde7c.png">
<img width="2240" alt="Bildschirmfoto 2021-06-13 um 21 12 31" src="https://user-images.githubusercontent.com/55672814/121819196-14b7a700-cc8c-11eb-9dca-b684073a29ee.png">

**Comment by TBlueF** [comment]
Ah, you have the old web-app :)
You probably updated BlueMap without deleting the `bluemap/web/index.html` *(which is mentioned in the update-notes that it is required)*.
Deleting that file will cause bluemap to update your web-app. Do that and your issue is likely solved as well :)

**Comment by braydofficial** [comment]
> Ah, you have the old web-app :)
> You probably updated BlueMap without deleting the `bluemap/web/index.html` _(which is mentioned in the update-notes that it is required)_.
> Deleting that file will cause bluemap to update your web-app. Do that and your issue is likely solved as well :)

Oh yes, this fixed the issue. Thank you very much!
