### ISSUE TITLE
Ability to list current icon files in the webroot with the API

### ISSUE THREAD

**Issue by n-aspen** [BlueMap-Minecraft/BlueMap#204]
**Is your feature request related to a problem? Please describe.**
Currently, I'm calling `createImage()` on every icon I'd like my plugin to be able to use every time the plugin starts. I'm doing this so that I have the current path of the image store in a hashmap and can guarantee that all of the images in my config folder have been moved to the webroot. I feel like this incredibly inefficient and is preventing me from selectively notifying users of when **new** icons are added since I never know what's already in the webroot. 

**Describe the solution you'd like**
I'd like to be able to list all of the images that are in a directory. Ideally, this directory would be isolated to just the images folder and would require the use of a subfolder before searching and creation to help prevent overlap between plugins making use of the images folder.

**Comment by TBlueF** [comment]
Added with API 1.7.0

**Comment by TBlueF** [comment]
Implemented in 1.6.2
