### ISSUE TITLE
Holographic Display Animations 

### ISSUE THREAD

**Issue by ErythroCraft** [BlueMap-Minecraft/BlueMap#205]
Hi.

I have an Future request about Holographic Display Animation on map.

So, I hope you can give an update to create full custom holographics over mapping.
My idea is to setup the map for WG, ESSX, Towny and PlotSquared with placeholders to see
regions, towns, plots and infos about the map that is allowed.

Why?

I testet the red colored regions and plots. That looks not good.

For example:
This new idea and maybe your future can set holographic displays over an city
createt by users to see shops or plots there have ratings.

On an far far future the displays are clickable on the web page.

**Comment by TBlueF** [comment]
@ErythroCraft Hey,
Unfortunately i have no idea what it is exactly that you have in mind.
Can you maybe elaborate your idea, maybe even with an image/scribble/mockup as an example? :)

*(If it helps, you can also try to explain it in german ;) )*

**Comment by ErythroCraft** [comment]
Vielen Dank.

Ich werde morgen etwas Ausarbeiten.

**Comment by ErythroCraft** [comment]
Moin.

Als erstes müssen noch ein paar updates gemacht werden.

1. Die texturen von [ grass_path ] und [grass_path_top] heißen jetzt [ dirt_path ] und [ dirt_path_top ]

2. In der Sidebar der online map ist der button [settings > reset all settings]
  - An dieser Stelle müssen nicht nur die setting zurück gesetzt werden, sondern auch der Cache.
  - Dabei sollte die map neu geladen werden, um alte map tiles zu entfernen
  - Einen button [ rest map tiles ] habe ich nicht gefunden.

Um meine Idee zu Entwickeln benötigt euer plugin im idealen fall eine reset funktion, die es dem Betracher erlaubt,
die gespeicherten map tiles im chache zu leeren ohne gezwungen zu sein den kompletten browser cache zu löschen.

**Das wär auch hilfreich, beim betrachten der map einem Spieler beim bauen zuzusehen.**

**Comment by ErythroCraft** [comment]
![Bild_2021-06-20_121343](https://user-images.githubusercontent.com/76217862/122670186-f4727580-d1c0-11eb-8e19-5a62c829ada1.png)

Die rot markierte Zone ist die neue map. Alles um der roten Zone herum, ist eine alte map die nicht automatisch resettet wird.

**Comment by TBlueF** [comment]
Hey, es gibt bereits diesen Button:
![image](https://user-images.githubusercontent.com/10765470/122670300-95613080-d1c1-11eb-9a43-e11c9cb271bc.png)
der genau das macht was du beschreibst. 

Wenn du Hilfe brauchst/fragen zu BlueMap hast kannst du gerne auf unserem (englischsprachigem) Discord fragen. Hier auf GitHub wäre es super wenn wir bei einem Issue beim Thema bleiben könnten.

Hier geht es um deinen Vorschlag zu "Holographic Display Animations" zu dem ich weiter nachgefragt habe was du damit meinst :)

---

Hey, there is already such a Button:
![image](https://user-images.githubusercontent.com/10765470/122670300-95613080-d1c1-11eb-9a43-e11c9cb271bc.png)
which is doing exactly what you just described.

If you need help with BlueMap or have any questions, please ask them on our (English-speaking) Discord. On GitHub it would be awesome if we could stay on-topic of the Issue.

This Issues topic is your suggestion for "Holographic Display Animations" where i was asking you to elaborate :)

**Comment by ErythroCraft** [comment]
https://user-images.githubusercontent.com/76217862/122670749-df4b1600-d1c3-11eb-88b4-07b51fe08d5e.mp4

**Comment by ErythroCraft** [comment]
> @ErythroCraft Hey,
> Unfortunately i have no idea what it is exactly that you have in mind.
> Can you maybe elaborate your idea, maybe even with an image/scribble/mockup as an example? :)
> 
> _(If it helps, you can also try to explain it in german ;) )_

Du hast selber Angeboten auf deutsch zu schreiben.

**Comment by TBlueF** [comment]
Ich habe angeboten auf Deutsch zu schreiben, aber nicht das Thema zu wechseln ^^

**Comment by ErythroCraft** [comment]
Ist mir schon klar. Jedoch ist das Teil des Themas.

Soll ich jetzt noch zwei issuses öffnen?
Dann lösche ich die Nachrichten hier und füge Sie nochmal mit meinen Englischkenntnissen ein.

**Comment by TBlueF** [comment]
Nein, okay dann erklär bitte das ganze Thema auf einmal, damit ich das Ganze verstehe :)

**Comment by ErythroCraft** [comment]
Mache ich.

Es geht darum, dass Grundstücke, die mit Towny und WordGuard erstellt wurden, in Flächen angezeigt werden.
Weil sich bei eurem Plugin jedoch die Flächen sehr stark verschieben, habe ich die Idee die Flächen
durch holografische Displays zu Ersetzen.

Also, an Stelle der Flächen erscheint ein Display [wie Beispielsweise bei HolographicDisplays].
Dieses Plugin hat im Prinzip schon alles was es braucht, um mit Hilfe von PAPI oder MVDW 
jegliche Infos zu setzten.

Somit wäre es Möglich, dass geänderte Werte, wie Auktionen, Grundstücksbezeichnungen, aktuelle Kriege,
Shop Infos, Spieler Informationen und so weiter als schwebende Schrift (entweder als mous-hover, left-click oder permanent) 
automatisch aktualisiert werden. Der Server Owner entscheidet dann in welcher Art auch immer die HPs erscheinen.

Nehme ich aktuell Bezug auf Towny in Kombination mit PlotSquared (WorldGuard), so Überlagern sich die Flächen 
und es entstehen eine eine Masse an Farbenfrohen Quadraten welche die 3DMap unkenntlich machen.

Deshalb ist es erst einmal Notwendig, das 3 Dinge Funktionieren.
1. Die Texturen
2. Die Aktualiesierung der Map (Automatisch)
3. Das anclicken einzelner Blöcke (Aktuell mit mindestens 4 Blöcken Versatz)

Der Nächste Schritt wäre dem zu Folge das Anpassen der Konfigurationsdatei und das erstellen eines extra Ordners für das Editieren der Infos, die auf der Map zu sehen sind.

Wenn nun eine Stadt einen Krieg anfängt oder ein Spieler sein Haus verkaufen möchte, müssen diese Infos automatisch geupdatet werden.

Normalerweise mache ich das schritt für schritt. 
Weil es sich gezeigt hat, dass meine Ideen die meisten Leute überfordern.

**Comment by TBlueF** [comment]
Okay.

Erstmal ein paar Infos vorweg:

1. BlueMap updated die Map automatisch wenn die Welt sich erweitert. Wenn die Welt sich aber komplett ändert / neu-generiert wird, muss man die map selbst erst löschen, und kann sie dann neu-generieren. Das geht mit `/bluemap purge <mapid>`. Das kann man möglicherweise automatisieren, ist aber nicht immer gewollt. Wenn das jemand automatisieren möchte, kann der BlueMap's [API](https://github.com/BlueMap-Minecraft/BlueMapAPI) verwenden und das tun :)

2. BlueMap aktualisiert die Map automatisch. (Funktioniert am besten in den neuesten versionen 1.5.+) Man muss nur mit dem [Update Map] button den Browser-Cache "leeren". Damit die neuen Map-Tiles auch geladen werden.
BlueMap aktualisiert (auch ohne den cache-button) alle 10 Sekunden die Marker neu.

3. Das anklicken einzelner Blöcke in der Map sollte bereits einwandfrei funktionieren.

Außerdem:
- BlueMap hat einige verschiedene Arten an Markern
  - [Region-Marker](https://bluecolored.de/bluemap/#acrana:224:39:1756:222:-0.88:0.54:0:0:perspective) (die flachen die sich aufgrund ihrer festen höhe im 3D-Modus zu verschieben scheinen.)
  - [Extrude-Marker](https://bluecolored.de/bluemap/#acrana:181:63:-328:66:-0.6:0.84:0:0:perspective) (3D-Marker die als dreidimensionaler "Kasten" auch die y-Ache abdecken
  - [Line-Marker](https://bluecolored.de/bluemap/#acrana:142:63:-278:66:-1.81:0.26:0:0:perspective) (Einfache, anklickbare Linien)
  - [POI-Marker](https://bluecolored.de/bluemap/#acrana:187:71:-212:20:-2.01:0.86:0:0:perspective) (Ein beliebiges anklickbares Icon)
  - [HTML-Marker](https://bluecolored.de/bluemap/#acrana:-54:46:3389:149:-0.15:0.59:0:0:perspective) (Ein beliebiges HTML-Element das irgendwo auf der Map platziert werden kann.
  
  Die HTML-Marker kommen einem "Holographischen Display" doch auch schon sehr nahe, oder? :)
  
- Die Marker kann man manuell in der [`markers.json`](https://github.com/BlueMap-Minecraft/BlueMap/wiki/Markers) konfigurieren, oder mit BlueMaps API und einem eigenen Plugin.
- Sämtliche Marker Kann man mithilfe von BlueMap's [API](https://github.com/BlueMap-Minecraft/BlueMapAPI) und einem eigenen Plugin automatisiert und beliebig aktualisieren.

Kannst du damit nicht schon genau das erreichen was du möchtest? :)

**Comment by ErythroCraft** [comment]
Okay.

Leider muss ich sage, dass ich die neueste Version verwende.
Alle drei Punkte funktionieren nicht!
Schau dir bitte das Video oben an.

Da ich jetzt davon ausgehe, dass ihr euer Plugin nicht selber testet,
sondern davon ausgeht, dass es funktioniert. 
Dann kann ich auch nicht davon ausgehen, dass meine Ideen umsetzbar sind.

Ich deinstalliere das Plugin und steige wieder auf Dynmap um.

Dennoch vielen Dank für die Antworten.
LG

**Comment by ErythroCraft** [comment]
!reopen

**Comment by ErythroCraft** [comment]
!reopen

**Comment by TBlueF** [comment]
Can you please explain why you have reopened this issue?
