### ISSUE TITLE
Lighting issue in End-Dimension

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#206]
If the sections directly above some blocks are empty and not present in a chunk, then bluemap assumes a sunlight of 15 which is correct in the overworld, but wrong in the end and the nether dimensions. Resulting in weird lighting issues.

![image](https://user-images.githubusercontent.com/10765470/123231928-f433ec00-d4d8-11eb-8bee-0f743520516c.png)

**BlueMap Version:** 1.5.4 - Minecraft 1.17

**Comment by SulpherStaer** [comment]
I'd like to add that these lighting issues also mess up the overview map

![image](https://user-images.githubusercontent.com/5037244/131076200-bf234492-e726-4868-84f8-9b2b4932a653.png)

The light spots you see, are the light bugs.

When zoomed in, its supposed to look like this.

![image](https://user-images.githubusercontent.com/5037244/131076272-d0dd1900-f750-42cb-b8e4-339085c9ff86.png)

**Comment by TBlueF** [comment]
@SulpherStaer I am assuming you are using the Snapshot-Version (1.6.0)? That version has a different, known bug right now which causes this.
But that has nothing to do with this issue :)

**Comment by TBlueF** [comment]
Fixed in 1.6.1
