### ISSUE TITLE
Marker Removed via API doesn't remove from web without a reload

### ISSUE THREAD

**Issue by drakmirv** [BlueMap-Minecraft/BlueMap#207]
### What i did / Steps to reproduce

Used BlueMap-Signs to create a marker and it appeared on the web map
Destroyed the Sign
Marker.json file came back down without the marker (API seems to have updated the break properly)

### Expected result
Web should have removed the marker from the list of markers.

### Actual result
Web still showed old marker in list, an update map fixed it.

### Context
Version: 1.5.5
Commit: 05f8f60695b8ebf8460d571a86da711666b03dc5 (true)
Implementation: bukkit
Minecraft compatibility: 1.17.0 (1.17.0)
Render-threads: 6
Available processors: 8
Available memory: 8192 MiB

Spigot: 1.17
This server is running CraftBukkit version 3162-Spigot-f773da8-b121d3b (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by TBlueF** [comment]
Fixed in 1.6.2
