### ISSUE TITLE
Blank Page when OpenGL doesn't initialize

### ISSUE THREAD

**Issue by drakmirv** [BlueMap-Minecraft/BlueMap#208]
### What i did / Steps to reproduce
Attempted to view the demo site and/or Blue map on my server
Three.js failed to initialize OpenGL (chrome flags were messed up)

### Expected result
See an error presented explaining what happened (versus having to examine console)

### Actual result
Errors appeared in the console, but the website was "empty"

This initially left me to think the demo site was down or the map didn't work versus pushing me to fix my browser. 

### Context

Version: 1.5.5
Commit: 05f8f60 (true)
Implementation: bukkit
Minecraft compatibility: 1.17.0 (1.17.0)
Render-threads: 6
Available processors: 8
Available memory: 8192 MiB

Spigot: 1.17
This server is running CraftBukkit version 3162-Spigot-f773da8-b121d3b (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by TBlueF** [comment]
Implemented in 3.4
