### ISSUE TITLE
Mouseover coordinates

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#21]
DynMap has this feature where it will show you the coords of where your mouse currently is. This can be a very useful feature for quickly getting the coords of a place. Can BlueMap have something similar?

**Comment by TBlueF** [comment]
How should this look like?
We already have the coordinates above that can't really be used for this.
Maybe a tool that you can activate and then use it to get informations on your mouse-pointer?

**Comment by Katrix** [comment]
Some sort of tool sounds like a nice solution

**Comment by Katrix** [comment]
Closing this as you can get the coords on click now
