### ISSUE TITLE
Coordinates are centered around 1 block

### ISSUE THREAD

**Issue by twboom** [BlueMap-Minecraft/BlueMap#210]
### What i did / Steps to reproduce
The coordinate system is centered around one block. 

### Expected result
In the middle of the world there should be a 2x2 square between (0,0) and (-0,-0). This is how it works in Minecraft.

### Actual result
There is a (0,0) block for the (0,0) block in MC itself, however, the (-0,-0) block in MC is the (-1,-1) block on BlueMap. This issue is of course also for the other two blocks of the square around (0,0).

### Context
**BlueMap Version:**  
`1.4.2-fabric-1.16.4` (from the file name)

I think this is not a deal-breaking issue, but still.

**Comment by TBlueF** [comment]
> In the middle of the world there should be a 2x2 square between (0,0) and (-0,-0). This is how it works in Minecraft.
@twboom 

No it's not :)
If you read coordinates in F3 you need to always round **down** to get the blocks integer-coordinates.
0.3 -> 0
-0.3 -> -1

E.g. using the commands 
```
/setblock 0 3 0 minecraft:blue_wool
/setblock -1 3 0 minecraft:red_wool
```
ingame, will result in 2 blocks exactly next to each other:

![image](https://user-images.githubusercontent.com/10765470/124113047-4477f480-da6b-11eb-9cb0-8bda490e74c8.png)

meaning that bluemap's coordinates are correct, right? :)
