### ISSUE TITLE
Add marker set commands and ability to create a marker in a given set

### ISSUE THREAD

**Issue by drakmirv** [BlueMap-Minecraft/BlueMap#211]
**Is your feature request related to a problem? Please describe.**
The create marker command only puts the new marker into a set named "markers".  While we can hand edit the "markers.json" file, it would be more convenient to be able to add/remove markers into a given set.

This likely also requires a command to manage marker sets as well.

**Describe the solution you'd like**
Add an optional parameter to marker create to specify the id of the marker set
Add tab complete for this parameter
Add a marker set create command to create new marker sets
Add a marker set list command to list marker sets
Add a marker set delete command to delete marker sets
Add a marker set edit command to edit marker sets (otherwise renaming a set would require delete/create which would destroy existing markers)

**Comment by TBlueF** [comment]
I am currently not sure how to handle this.
My overall opinion on this is that handling markers should mainly be done manually using a config, or via BlueMap's API.

The reason for that is compatibility between spigot/fabric/forge/sponge implementations ..
E.g. adding commands for marker-sets is one thing, the next step would be adding commands for all other marker-types and such. For that, to make it user-friendly and useable, pure text-commands are not sufficient in my opinion.

For example to create a Region-Marker you would need to select a region somehow. The best way to do this is with some kind of selection-tool (item) and world interactions, maybe even with particle-effect marking your current selection. And that is all stuff that would need to be implemented for each spigot/fabric/forge/sponge separately. Wich would cause big problems and differences between the implementations.

The better solution would be for BlueMap to further expand its (Marker-)API (which is definitely planned already), and then an extension-plugin that is using BlueMap's API to add commands for adding and managing Markers and Marker-Sets. This plugin then would be platform dependant, e.g. only available for Spigot-based servers. And maybe there would be another mod doing a similar implementation for forge.

**Comment by TBlueF** [comment]
I'll close this with the above reasoning and since i will likely move in the other direction and make markers purely configuration and 3rd-party-plugin based.
