### ISSUE TITLE
Timeouts and loading issues

### ISSUE THREAD

**Issue by HonorGamerHD** [BlueMap-Minecraft/BlueMap#212]
### What i did / Steps to reproduce
Installed bluemap, set it up for all maps, preloaded chunks with chunky and rendered tons of chunks.

### Expected result
webapp should load "instantly" without errors.

### Actual result
524 error(timeout), loading issues like blackscreen and nothing is happening until another reload, endless loading for some reason.

### Context
**BlueMap Version:**
`BlueMap-1.5.5-spigot`

Optional:
There are no errors, no low tps/performance issues, just the fact that it doesnt load correctly. 
Using latest paper build(git-Paper-71), also installed Bluemap skins, townyblue and bluemap essentials.
Host machine: dedicated server, 6 cores @ 3,9ghz boost up to 4,2ghz, 64gb ram(up to 16gb useable for mc server), only nvme ssd storage, server is running in a docker container. Container never had such connection issues. Connection to the map gets redirected with a apache2.4 proxypass:

```
ServerName map.servername.eu
ProxyPass / http://127.0.0.1:8123/
ProxyPassReverse / http://127.0.0.1:8123/
```

TCP port is forwarded and working, i used dynmap before but its uninstalled now.

Thanks for help, i hope thats enough information for you.

**Comment by HonorGamerHD** [comment]
Seem to work fine with external webserver, maybe an issue with the internal one?

**Comment by TBlueF** [comment]
Seems to be something happening rarely on some setups. I can not reproduce this on my end, but similar problems have been reported by 2 people until now.
This happens since 1.5.x

I'll probably replace the (self written) internal webserver entirely with [Undertow](https://undertow.io/). That should then fix this.

**Comment by TBlueF** [comment]
I am not happy with Undertow, so i am dropping this idea for now.
I found an issue that might have caused this issue and fixed that.
The next version (>= 1.6.1) will include this fix.
