### ISSUE TITLE
ERROR when preparing spawn area

### ISSUE THREAD

**Issue by Glucy-2** [BlueMap-Minecraft/BlueMap#213]
### What i did / Steps to reproduce

Start the server.
### Expected result

No ERROR.
### Actual result

ERROR
### Context
**BlueMap Version:**  
`1.5.5-fabric-1.17`

[latest.log](https://github.com/BlueMap-Minecraft/BlueMap/files/6757961/latest.log)

**Comment by TBlueF** [comment]
That error is not related to BlueMap.
Also please read https://github.com/BlueMap-Minecraft/BlueMap/blob/master/.github/CONTRIBUTING.md before opening an issue.
