### ISSUE TITLE
Resouce Pack color issue depending on hight

### ISSUE THREAD

**Issue by SaiCode-DEV** [BlueMap-Minecraft/BlueMap#214]
### What i did / Steps to reproduce

http://map.saicode.de/?worldname=Ignacia&mapname=flat&zoom=0&x=-32&y=64&z=-44#world:-22304:63:-28424:116:-0.19:0.49:0:0:perspective
useing that resouce pack in certain biomes
https://drive.google.com/file/d/1xCffnZJQjzB-G3-9jUwtx3GTDMU8VtQe/view?usp=sharing

### Expected result

everything should be like in the resoucepack

### Actual result

attached image, depending oh height the color gliches out

### Context
**BlueMap Version:**  
Version 1.5.5 , paper 1.17.1

![color bluemap](https://user-images.githubusercontent.com/53049957/125433611-4c1c642e-55bc-4416-a6b4-9d76456ae828.PNG)

**Comment by TBlueF** [comment]
This should be fixed in 1.6.1
