### ISSUE TITLE
[QUESTION] How to set default website language? 

### ISSUE THREAD

**Issue by RuofengX** [BlueMap-Minecraft/BlueMap#216]
**Problem**
I'm using Nginx and bluemap CLI. Bluemap didn't respect the language header sent from explorer, also I didn't know how to configure the default language.

**Describe the solution you'd like**
Add the feature that makes bluemap respect the language header and make a default language config or guide.

**Comment by EsserGaming** [comment]
It should be a feature, I would wait on @TBlueF or someone else to see your issue.

**Comment by TBlueF** [comment]
You can set the default language in `./bluemap/web/lang/settings.js`.

*(GitHub is not a place for support, please use our Discord or Reddit for that <3)*
