### ISSUE TITLE
[Featrue Request] Screenshot button

### ISSUE THREAD

**Issue by BuyMyMojo** [BlueMap-Minecraft/BlueMap#218]
**Describe the solution you'd like**
A basic button in the settings menu possibly to take a full resolution capture of what the current view is or possibly a double resolution one?

Mock-up UI:
![Example 1](https://user-images.githubusercontent.com/46948241/126021812-713e6db3-a525-46c6-a96c-898306e4851c.png)
![Example 2](https://user-images.githubusercontent.com/46948241/126021814-0ac660a9-04c4-4f11-abd8-0c3ccaad56a3.png)
![Example 3](https://user-images.githubusercontent.com/46948241/126021815-92522d68-d986-4d86-86b6-df4265e81a4e.png)

**Comment by ryantheleach** [comment]
Instead of it being a web screenshot button, I'd like to see the possibility of a screenshot happening from an ingame perspective.

E.g. if it's an area normally inaccessible by the map, a player could show off their bunker in first person mode.

**Comment by BuyMyMojo** [comment]
> Instead of it being a web screenshot button, I'd like to see the possibility of a screenshot happening from an ingame perspective.
> 
> E.g. if it's an area normally inaccessible by the map, a player could show off their bunker in first person mode.

There is a first person fly around option, if cave rendering is enabled I'm pretty sure you'd be able to fly underground and use the web screenshot button to get an image if this is added

**Comment by TBlueF** [comment]
Note: I'd prefer the Screenshot Button to be either directly above or below the "Reset Camera" Button :)

**Comment by TBlueF** [comment]
Implemented in 3.5
