### ISSUE TITLE
Add a way in the API to get the BlueMap webroot path

### ISSUE THREAD

**Issue by TechnicJelle** [BlueMap-Minecraft/BlueMap#219]
**Is your feature request related to a problem? Please describe.**
In my BlueMap add-on, [I need to access](
https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/blob/e6b497b24b69b6731d750800b6c7b874eaff09dd/src/main/java/net/mctechnic/bluemapofflineplayermarkers/main.java#L158) the `assets/playerheads/` folder to copy those images for the offline playerhead markers. This is currently done by just assuming the webroot is in the default place, but of course this can be different. Therefore, I'd like a way to request the location of the webroot from the API.

**Comment by TBlueF** [comment]
Added with API 1.7.0

**Comment by TBlueF** [comment]
Implemented in 1.6.2
