### ISSUE TITLE
make forge1.12.2

### ISSUE THREAD

**Issue by msj20080623** [BlueMap-Minecraft/BlueMap#220]
I want a forge with 1.12.2

**Comment by EsserGaming** [comment]
![image](https://user-images.githubusercontent.com/36900138/127253539-cb074624-f814-4d3e-a575-c630922a7215.png)
*From the discord server

**Comment by JosTheDude** [comment]
Development takes time and effort. Releasing new plugins/mod versions of a plugin/mod is really hard. Also, image above.

**Comment by EsserGaming** [comment]
That really isn't related but what he means is that 1.12 isn't really worth the effort back porting so many versions back. Also CLI should work any version.

**Comment by msj20080623** [comment]
I'm from China
But our country's network does not allow access to Google and cli servers

**Comment by EsserGaming** [comment]
![image](https://user-images.githubusercontent.com/36900138/127253864-27cde7cd-4e73-4733-aa3e-66d2a7ec6b92.png)

**Comment by JosTheDude** [comment]
It's not a CLI server, it's a download from the releases page from bluemap.

**Comment by EsserGaming** [comment]
Its like the plugin but its standalone

**Comment by msj20080623** [comment]
可以私聊吗：Shapaper@126.com

**Comment by EsserGaming** [comment]
bro

**Comment by msj20080623** [comment]
It seems that some people can't understand the installation tutorial because of cultural differences in different countries

**Comment by JosTheDude** [comment]
We're trying to help, please don't be rude...

**Comment by EsserGaming** [comment]
Well, just please read the announcement that I sent from the BlueMap discord. That should be enough info for you.

**Comment by msj20080623** [comment]
oh,sorry,
I didn't mean that
I'm not rude

**Comment by JosTheDude** [comment]
It alright.

**Comment by msj20080623** [comment]
![image](https://user-images.githubusercontent.com/50202273/127254631-2dc9db98-5ada-42e7-9b1b-3cf6907fd6ca.png)
ah，Even discord is blocked from our national network

**Comment by EsserGaming** [comment]
Then how are you able to access github?

**Comment by EsserGaming** [comment]
Also that's reddit not discord 🙄

**Comment by msj20080623** [comment]
Sorry, Google Translate messed up the typesetting. I read it wrong

**Comment by n-aspen** [comment]
> That really isn't related but what he means is that 1.12 isn't really worth the effort back porting so many versions back. Also CLI should work any version.

I might be wrong, but I'm fairly certain that  BlueMap1.6+ wont be supporting MC 1.12 either. You'd have to upgrade the world format, which won't work if the mods you're using haven't updated to 1.13.

**Comment by EsserGaming** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/36900138/127253539-cb074624-f814-4d3e-a575-c630922a7215.png)
> *From the discord server
@mov51

**Comment by msj20080623** [comment]
Many modpacks are 1.12.2: Sky Factory 4, stone world

**Comment by JosTheDude** [comment]
May I ask where your getting the modpacks, might assist in figuring out how to get the bluemapCLI working

**Comment by msj20080623** [comment]
Especially in the stone world, traditional 2D maps cannot be used

**Comment by msj20080623** [comment]
curseforge

**Comment by TBlueF** [comment]
Closing, since 1.12.2 will not be supported in the future
