### ISSUE TITLE
Automatic Marker Updates - Visual Outline Bug

### ISSUE THREAD

**Issue by Mark-225** [BlueMap-Minecraft/BlueMap#221]
### What i did / Steps to reproduce

1. Create a shape marker on any map.
2. Change only the shape of the marker (keep the id) and make sure the new shape has more edges than the old one.
3. Wait for the webapp to pull a new marker update from the server.

### Expected result

The new marker should be properly displayed with a complete outline.

### Actual result

Only the first X edges of the updated marker have an outline (X being the amount of edges on the previous shape).
After a browser reload, the outline is displayed properly again.

### Context
**BlueMap Version:**  
`1.5.5-spigot`

#### Before/original shape:
![bugreport - before](https://user-images.githubusercontent.com/35063645/127327006-a3ed1ed1-b085-4a68-90a0-70d47cb9219d.png)
#### After/updated marker:
![bugreport - after](https://user-images.githubusercontent.com/35063645/127327176-4b33cd46-5c42-43a6-a7dc-4aeb6b1b6c11.png)

**Comment by TBlueF** [comment]
Fixed in 1.6.2
