### ISSUE TITLE
Multiverse nether/end maps

### ISSUE THREAD

**Issue by Toucan-Sam** [BlueMap-Minecraft/BlueMap#223]
Sorry to revive this. Appear to be a few existing threads in #112 and #109?

### What i did / Steps to reproduce
Added worlds via multiverse including nether and end maps.

### Expected result
Bluemap should render the new maps.

### Actual result
Bluemap only renders overworld.

### Context
**BlueMap Version:** `1.5.5`
**Server type:** `paper-1.17.1` (`git-paper-133`)

Server is paper based (above) from a docker container [itzg/minecraft-server](https://hub.docker.com/r/itzg/minecraft-server)

World was added directly via Multiverse-Core. Multiverse-Portals is also installed to link the worlds.

Full list of plugins:
BetterSleeping3, BlueMap (obviously), DiscordSRV, Essentials, Floodgate, Geyser, GriefPrevention, LuckPerms, Multiverse (Core, Inventories, Portals), PlugMan, ServerRestorer, VoidGen, WorldEdit

### Config files (as gists)
BlueMap: [render.conf](https://gist.github.com/Toucan-Sam/7e242f3113248b3327f7533e2a6f5523)
Multiverse-Core: [worlds.yml](https://gist.github.com/Toucan-Sam/6fccd59d2fd8d4daff37434c1a59bf82)

### Things I've tried
I've tried deleting the BlueMap cache entirely.
I've tried adjusting the roof height (though I just used the one from the BlueMap 'world' example.
I've tried to force render the world (/bluemap render 1.17_nether)

More than happy to attach any other logs/configs/etc. Don't run a big server and easy enough to back up if you want me to try anything.

**Comment by TBlueF** [comment]
Nether and end have a dimension-subfolder
`DIM-1` (nether) and `DIM1` (end). You will need to add those to render nether/end dimensions.

E.g.:
```yml
# 1.17_nether
{
  id: "1.17_nether"
  name: "1.17 (Nether)"
  world: "1.17_nether/DIM-1"
  #...
}
```

---

> GitHub is not a good place to get support. If you have a question or need help with configuring BlueMap, please consider joining our discord :)

**Comment by Toucan-Sam** [comment]
How dare you be so responsive, accurate, and helpful!?

Only reason I raised it here is because I saw existing issues for the same thing and assumed it hadn't been fixed.

Thank you. :)

**Comment by JosTheDude** [comment]
We also offer support on the BlueMap discord with the community and Blue helping out.
Invite link:https://discord.gg/zmkyJa3
If you want support for other stuff, you can always join the discord, not needed but still lets everyone help out :D
