### ISSUE TITLE
Cake is not rendered properly

### ISSUE THREAD

**Issue by combe15** [BlueMap-Minecraft/BlueMap#224]
### What I did / Steps to reproduce
Place a cake in the world, update the map render.

### Expected result
Cake sides to render.

### Actual result
Cake sides did not render

### Context
Version: 1.5.5
Commit: 05f8f60695b8ebf8460d571a86da711666b03dc5 (true)
Implementation: bukkit
Minecraft compatibility: 1.17.1 (1.17.0)
Render-threads: 10
Available processors: 12
Available memory: 3072 MiB

![image](https://user-images.githubusercontent.com/11339091/127561806-6c960d3d-362f-4736-b434-7661ed9d95fe.png)

**Comment by PikaMug** [comment]
This should be high priority because cake.

**Comment by TBlueF** [comment]
Added to #145, closing this in favor of that issue :)
