### ISSUE TITLE
Powder Snow cauldron does not render proper color

### ISSUE THREAD

**Issue by combe15** [BlueMap-Minecraft/BlueMap#225]
### What i did / Steps to reproduce
Place a cauldron down and fill it with powder snow.

### Expected result
Expected the snow in the cauldron to render white.

### Actual result
Snow in the cauldron rendered with green color

### Context
Version: 1.5.5
Commit: 05f8f60695b8ebf8460d571a86da711666b03dc5 (true)
Implementation: bukkit
Minecraft compatibility: 1.17.1 (1.17.0)
Render-threads: 10
Available processors: 12
Available memory: 3072 MiB

![image](https://user-images.githubusercontent.com/11339091/127562637-3227bf58-69a7-4c89-a209-3306a4ccc959.png)

**Comment by TBlueF** [comment]
Already fixed in latest snapshot ;)

**Comment by TNTUP** [comment]
Slimey Cauldrons!

**Comment by TBlueF** [comment]
Fixed in 1.6.1
