### ISSUE TITLE
Warped sign does not render in webapp

### ISSUE THREAD

**Issue by combe15** [BlueMap-Minecraft/BlueMap#227]
### What I did / Steps to reproduce
Place a warped sign down, then view in web app

NOTE: Oak signs work as expected and the `Update Map` has no effect, as the signs were well before some of the other block placements, therefore, the render is up to date.

### Expected result
Sign placement should render

### Actual result
Sign placement did not render

### Context
Version: 1.5.5
Commit: 05f8f60 (true)
Implementation: bukkit
Minecraft compatibility: 1.17.1 (1.17.0)
Render-threads: 10
Available processors: 12
Available memory: 3072 MiB

![image](https://user-images.githubusercontent.com/11339091/127749241-39bd9af3-2d96-45c7-ae9d-528014440a3e.png)
![image](https://user-images.githubusercontent.com/11339091/127749293-831ea279-398d-4176-8b1d-2ea63a07fc63.png)

---

![image](https://user-images.githubusercontent.com/11339091/127749260-f8f4858c-3d7d-4781-aed0-069fa12930a8.png)
![image](https://user-images.githubusercontent.com/11339091/127749271-af97047b-0d16-46df-97bf-de25385e39b8.png)

**Comment by TBlueF** [comment]
Fixed in 1.6.1
