### ISSUE TITLE
Render distance seems to not load new tiles

### ISSUE THREAD

**Issue by EsserGaming** [BlueMap-Minecraft/BlueMap#229]
### What i did / Steps to reproduce
Set low-res distance to 10000
### Expected result
To load the 10000 render distance
### Actual result
Loaded a smaller area
### Context
**BlueMap Version:** 1.5.5

**Video** below explains the issue:
https://user-images.githubusercontent.com/36900138/128287398-661fa04a-1a7d-4eb9-8ed0-05a80ac89921.mp4

**Comment by TBlueF** [comment]
Well..
Your map isn't bigger then that .. so it can't load a bigger area ^^'

**Comment by EsserGaming** [comment]
🙃
