### ISSUE TITLE
[Feature request] Add Cubic Chunks support

### ISSUE THREAD

**Issue by GeekCornerGH** [BlueMap-Minecraft/BlueMap#230]
**Is your feature request related to a problem? Please describe.**
I was trying to make a Cubic Chunks server, but chunks does not appear.

**Describe the solution you'd like**
I want to see the chunks like on a vanilla world. Can you do it please? Thank you

**Comment by TBlueF** [comment]
Cubic chunks support will not be added. Cubic chunks make your world practically infinite in the Y-axis which makes them impossible to map the way bluemap does it. Sorry ^^
