### ISSUE TITLE
Unable to load custom dimentions from datapacks

### ISSUE THREAD

**Issue by kruthers** [BlueMap-Minecraft/BlueMap#236]
### What i did / Steps to reproduce
- Install a datapack that adds a custom dimention
- Added the world to `render.conf`
- Set the world's location to `world/dimensions/{namespace}/{dimension_name}` (the location of the region files)

### Expected result
The world to appear in the maps list and to render in.

### Actual result
Get the error: `java.io.IOException: There is no world with this folder loaded: ` in console and the map does not show, when the world's location is set to just `world` it will show in the maps bar and players will show, but wont render.

### Context
**BlueMap Version:**  
`1.6.0-spigot-1.17.1`

Was tested in spigot 1.17.1, paper-1.17.1-142, and purpur-1.17.1-1334 all with the same results

**Comment by TBlueF** [comment]
Should be fixed in 1.6.2
