### ISSUE TITLE
Modded chests are not rendering

### ISSUE THREAD

**Issue by FrostBird347** [BlueMap-Minecraft/BlueMap#238]
### What i did / Steps to reproduce
Rendered a chunk with a modded chest in it

### Expected result
The chest to be visible

### Actual result
The chest was invisible, but the block can still be selected

### Context
**BlueMap Version:** 1.5.5-fabric-1.17
**Platform:** MacOS, Fabric 1.17.1

**Comment by Seercat3160** [comment]
Tile entities are not currently supported, with some vanilla ones being manually added with resources

**Comment by FrostBird347** [comment]
Is it possible to render these modded chests as regular chests through a resource pack?

**Comment by Seercat3160** [comment]
I don't know how, but if you join the Discord server I'm sure someone could help you.

**Comment by FrostBird347** [comment]
Somebody there previously mentioned copying and modifying the JSON [here](https://github.com/BlueMap-Minecraft/BlueMap/tree/master/BlueMapCore/src/main/resourceExtensions/mc1_16/assets/minecraft/models/block/chest).
