### ISSUE TITLE
Modded resources breaks the rendering

### ISSUE THREAD

**Issue by Rafii2198** [BlueMap-Minecraft/BlueMap#240]
Using `BlueMap-1.6.0-forge-1.16.4` on `Forge 36.2.0`
Also present on `BlueMap-1.5.5-forge-1.16.4`

I used the wiki page to install the missing textures from mods (i.e putting the mod jar into the resources folder and deleting data folder) but whenever I do that, it completely messes up the textures on the map like all of them are randomized 
![obraz](https://user-images.githubusercontent.com/26695327/131002304-0483c548-877c-4f66-a955-4ce1e2d55edd.png)
The weird thing is also that there is sometimes one or two chunks that render correctly.
I don't know if it is a bug in the mod or I am misunderstanding something

**Comment by TBlueF** [comment]
This is likely due to your browser caching some old tiles.
Please use the `Update Map` button in the web-app if you see such textures :)

If you need more help with this, please visit our discord server or subreddit, since GitHub is not a good place for support.
