### ISSUE TITLE
Icon is registered but dissapears when updating its location

### ISSUE THREAD

**Issue by mmuziek** [BlueMap-Minecraft/BlueMap#243]
### What i did / Steps to reproduce
add a marker and give it a label and a icon.
then update the same marker again without those (since they havent changed...) 
marker is gone never shown but is still registered.
See image for clarification : https://prnt.sc/1qwcnw8

### Expected result
Icon shows as it was just the location updated

### Actual result
icon is gone...

### Context
1.6.0 beta (api and plugin)

**Comment by TBlueF** [comment]
As discussed on discord, you were creating a new Marker, instead of updating it. Which means the actual result is the expected one.
So i am closing this issue :)
