### ISSUE TITLE
[Question] Display size on the map

### ISSUE THREAD

**Issue by Joshua2504** [BlueMap-Minecraft/BlueMap#245]
Hello,

only a small area of the map is shown as sharp image (probably 8x8 chunks or something), everything around it is blurred until you move the map around.

Can this be configured? I didn't find anything on this in the config files.

Joshua

**Comment by Joshua2504** [comment]
I found it. There is a setting on the site itself "Render Distance"

is there a way to set a default value?

**Comment by TBlueF** [comment]
There is currently no way to set the default value.
Please use our Discord or Reddit for support. GitHub Issues are meant for something else :)
