### ISSUE TITLE
freeze/pause rendering dynamically 

### ISSUE THREAD

**Issue by Hafer-Nil** [BlueMap-Minecraft/BlueMap#246]
Please consider freezing / pausing map updates depending on a config-given threshold of online players, e.g.
freeze-threshold <n> means that rendering of map updates pauses as long as <n+1> or more players are online.

Reason: Especially for small to very small MC servers the background rendering of maps has an impact to server performance. To handle this, admins could adjust the load of their servers.

**Comment by TBlueF** [comment]
The latest snapshot (1.6.2) already has this feature :)
