### ISSUE TITLE
Bluemap removing custom biomes in worlds

### ISSUE THREAD

**Issue by svdgoor** [BlueMap-Minecraft/BlueMap#247]
### What i did / Steps to reproduce
Install any datapack that uses custom namespace + biome name for biomes in a world
Create a world and generate it somewhat (flying around suffices)
Notice that in your f3 debug screen there is a custom `namespace:biome` instead of `minecraft:biome` on the left top.
Stop the server
Install bluemap
Start the server + accept file download in conf.conf (why the .conf file extension instead of like yml or json that normal people use?)
/bluemap reload
bluemap starts generating the map
custom namespace:biome around spawn & chunks a bit further out are almost immediately reverted back to their underlying minecraft:biome name.

### Expected result
Namespaces are not reset. 
Bluemap generates the map with custom colors for leaves & water etc. (optional, prefferred).

### Actual result
Bluemap reset the custom namespaces & biome ids; see reproduction steps

### Context
**BlueMap Version:**  
BlueMap 1.6.3
Purpur git-Purpur-1382

Also:
There are no errors in the console strangely enough. I would expect bluemap to notice there's a different biome namespace.

**Comment by TBlueF** [comment]
Bluemap does never write into world-files .. it only reads them. It actually always opens world-files only with read-access-rights.
**So there is no way that bluemap is removing custom biomes from your world.**

If bluemap encounters a biome that it doesn't know, it will treat it internally as an ocean biome (i think ... or plains, not sure rn)
that's why you don't see it rendered.
There is already an issue for adding support for rendering custom biomes correctly: #156

**Comment by TBlueF** [comment]
> why the .conf file extension instead of like yml or json that normal people use?

The config language used is [`HOCON`](https://github.com/lightbend/config/blob/main/HOCON.md) .. it's being used by many already and the [Sponge](https://www.spongepowered.org/)-Community are making it the new standard. I agree with their decision and thus bluemap is using it as well :)

"Normal" people are boring anyways ^^

**Comment by TBlueF** [comment]
@CocoTheOwner Can you link me your datapack that adds the custom biomes?

**Comment by svdgoor** [comment]
It's a datwpack generated by the custom world generator plugin I contribute to.
The name of the plugin is Iris and it can be found [here](https://github.com/volmitsoftware/iris). Make sure to compile it with `shadowJar` instead of `build`. Follow the tutorial on the wiki [here](https://docs.volmit.com/iris/getting-started).
It reboots your server once after it generated the datapack.

You can also use any other arbitrary datwpack that makes use of custom namespace, it should result in the same behaviour.
Thank you for your time.

**Comment by TBlueF** [comment]
@CocoTheOwner I am not able to reproduce your issue.
I followed your steps closely, but even after fully rendering the map and several additional restarts, the biome is still correct ingame. *(While BlueMap renders the default biome, as expected.)*

![image](https://user-images.githubusercontent.com/10765470/135766211-20fd5562-fedb-4c1d-bc20-4a7586c0fc9d.png)

Is there any other way i can reproduce this?

**Comment by svdgoor** [comment]
Hey, thanks for checking it out.
Interesting that you're not seeing the same behaviour.
I will try to record the steps I take to achieve the same result tomorrow or somewhere next week.
Hope it is alright to keep this open until then.
Thanks for spending the time, Coco

**Comment by TBlueF** [comment]
I will reopen this when you found a way to reproduce it :)
