### ISSUE TITLE
Reorganize config structure

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#249]
Reorganize the config structure, to make it easier and more intuitive:
- a subfolder for map-configurations where each map has it's own config file
  - adding a new map = adding a new config file
  - the name of the config file will be used to create the map's id
  - new `marker` section where static markers can be defined for a map
- new `webapp.conf` which includes settings only for the webapp
  - add more webapp-settings like min-max zooms and render-distances, turning on and off buttons and features
- remove `render.conf`

**Comment by Foorcee** [comment]
It would be handy if the configurations can create from the API. So that you can dynamically add and remove worlds. So a single world can be re-rendered when it has been unloaded.

**Comment by TBlueF** [comment]
Implemented in 2.0
