### ISSUE TITLE
Adding support for Custom Blocks and obj models?

### ISSUE THREAD

**Issue by Dockter** [BlueMap-Minecraft/BlueMap#25]
I'm curious if you're planning on adding support for custom blocks AND those custom blocks using obj models?

**Comment by TBlueF** [comment]
Adding custom blocks in the resourcepack-format is already possible and described here: https://github.com/BlueMap-Minecraft/BlueMap/wiki/Configuring-mods
This excludes obj-models though..

I have no experience with the obj format and how it is used within some minecraft mods, but i think it should be feasible to implement some support. However that is not very high on my priority right now ^^
