### ISSUE TITLE
support for fabric 1.18 snapshots

### ISSUE THREAD

**Issue by PortableGames** [BlueMap-Minecraft/BlueMap#250]
add support for snapshots eg. 21w44a for fabric servers

**Comment by TBlueF** [comment]
Why did you close this? :)
Support for the latest minecraft-version is definitely something that should be added ^^

**Comment by PortableGames** [comment]
well my website is basically just a snapshot map of the server via bluemap ... planetcraft.cz .. and I've kind of stopped hoping that it ever will be .. so I closed it down and started redesigning all the links on the onlinemap

**Comment by PortableGames** [comment]
@TBlueF realistically the official 1.18 will come out before you add support for snapshots .. so the next request will be to add support for 1.19 snapshots 😎

**Comment by TBlueF** [comment]
Well, support for snapshots in general is indeed not the highest in priority. Mostly since stuff still can change..
I am trying to be on-time with the final releases :)

**Comment by PortableGames** [comment]
@TBlueF Could you give me your discord? or add me PortableGames#3564

**Comment by TBlueF** [comment]
@PortableGames BlueMap has a discord-guild on which you can find me as well: https://discord.gg/zmkyJa3 ;)
