### ISSUE TITLE
Use Brotli instead of Gzip

### ISSUE THREAD

**Issue by birdhimself** [BlueMap-Minecraft/BlueMap#253]
**Is your feature request related to a problem? Please describe.**
Considering that [Brotli is supported by every major browser these days](https://caniuse.com/brotli) you should consider using it instead of Gzip. In my tests, JSON generated by BlueMap compressed around 20-30% smaller with Brotli compared to Gzip. This saves a lot of space storing the map and a lot of bandwidth serving the map.

**Describe the solution you'd like**
Enable Brotli compression to replace Gzip compression by default (or make it configurable). Existing Gzip files should either be unzipped and compressed again with Brotli as some sort of migration, or the map should re-render again (both are fine probably).

**Comment by TBlueF** [comment]
The problem with brotli compression is that browsers only accept brotli from an encrypted connection. By default BlueMap-Maps are `http`. 
There is already a fork that implemented brotli: https://github.com/NikitaCartes/BlueMap/tree/feature/brotli
And adding brotli-compression as an option is also already on the [TODO](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true). It will not be default tho :)

**Comment by BuIlDaLiBlE** [comment]
I'm very much interested in this as I'm using a proxy server with TLS anyway.

**Comment by chocological00** [comment]
Could it make sense to support plain uncompressed tarball as an option? Btrfs supports transparent compression in the filesystem layer, so I can make the choice of compression algorithm independent from browser support. However, this works much better with small number of large files, rather than large number of small files, so tarball could be useful here.

**Comment by FinlayDaG33k** [comment]
> I'm using a proxy server with TLS anyway

Most likely, you can use the proxy server to re-compress it as Brotli (not ideal but it should work).  

What I personally did is use no compression with an external webserver (Bluemap puts it on a MySQL server and an external webserver gets it from there).
Then just let the external webserver handle compression.  
It does take a bit more resources so you'll have to think for yourself whether it's worth it.
You could move the external webserver + MySQL on a completely different box to not have your Minecraft server deal with it (and disable the built-in webserver completely).  
That also means your map will remain available while your server goes down (eg. maintenance) but is a more complex setup (I'd be willing to write a guide on this if demand is there).

Please do note that png files don't always compress that well.
![afbeelding](https://github.com/BlueMap-Minecraft/BlueMap/assets/13424273/c0d33e15-82c4-4922-bbe1-946b0d619e91)
![afbeelding](https://github.com/BlueMap-Minecraft/BlueMap/assets/13424273/02387ac8-17fa-42fe-9fce-22e0d18e6e04)

I would agree that the option for Brotli in the plugin itself would be nice but it can be achieved right now as well, just... with some extra steps.

**Comment by TechnicJelle** [comment]
With the new BlueMap 5 release, there is now the possibility to install BlueMap Native addons.
Brotli support was made as one such addon, by Blue himself!
https://github.com/BlueMap-Minecraft/BlueMapBrotli

**Comment by TBlueF** [comment]
welp .. thanks for reminding me to close this :D
