### ISSUE TITLE
Offline Server Skins

### ISSUE THREAD

**Issue by P5ina** [BlueMap-Minecraft/BlueMap#254]
**Is your feature request related to a problem? Please describe.**
No skins on offline servers.

**Describe the solution you'd like**
Please, add SkinsResorter support.

**Comment by kencinder** [comment]
Bluemap doesn't support any other plugin, that is up to other plugins or 3rd party addons.

https://www.spigotmc.org/resources/bluemap-skins.90284/?__cf_chl_jschl_tk__=pmd_2Q3lHodIcrdY16PalrZagszrfdA_4RLRbUYSpLhPNQQ-1635394225-0-gqNtZGzNAjujcnBszQv9

**Comment by P5ina** [comment]
BlueMap Skins doesn't works on 1.17

**Comment by TBlueF** [comment]
There will neither be any built-in support for offline-mode servers, nor built-in support for other plugins.

There is also this 3rd-party plugin that claims to do what you need, maybe that works: https://www.spigotmc.org/resources/bluemapofflineskinsupport.91486/
