### ISSUE TITLE
3D player models.

### ISSUE THREAD

**Issue by BirbEXE** [BlueMap-Minecraft/BlueMap#255]
**Is your feature request related to a problem? Please describe.**
nope 

Why do you want this feature
Just to add some more detail around players 

**Describe the solution you'd like**
My suggestion is to try and implement an option which would show players as their Minecraft models when close up.
I see this causing multiple issues, especially with performance, so this should be disabled in config by default.

I just thought it might be a cool feature to fit in with the 3D style, but I see it being quite resource intensive, unless you implement something like Optifine's smart animations. Give me your thoughts <3

**Comment by TBlueF** [comment]
This is a duplicate of #95, so i will close this one again :)
It's planned, but low prio right now.

**Comment by BirbEXE** [comment]
Great, thanks 
Didn't see the other issue open, apologies.
