### ISSUE TITLE
API for displaying plugin claims / area markers

### ISSUE THREAD

**Issue by lurr** [BlueMap-Minecraft/BlueMap#258]
It would be nice to be able to define, either through integration with specific mods, or an API, a way to display "claims" from plugins such as [GriefDefender](https://github.com/bloodmc/GriefDefender/) and other similar plugins.

This could be abstracted away into an Area marker, similarly to what the Dynmap API has currently.

**Comment by TBlueF** [comment]
https://github.com/BlueMap-Minecraft/BlueMapAPI/
Pretty sure GriefDefender even already supports BlueMap, and should display its claims there :)

**Comment by lurr** [comment]
Ah, sorry! Missed the `ShapeMarker`. Thanks for pointing that out :+1:
