### ISSUE TITLE
Plugin Integration

### ISSUE THREAD

**Issue by untuned** [BlueMap-Minecraft/BlueMap#26]
This map is a great alternative to Dynmap, but I'd like for there to be integration features.

Plugins which could be added:
- Worldborder
- GriefPrevention
- FactionsUUID
- Lands
- Residence
- WorldGuard
...and others.

**Comment by TBlueF** [comment]
I don't know if i will add all those plugins myself, but i **will** add an API that makes it easy for others to integrate them. The API will include area-markers with multiple shapes, points, lines and tool-tips, so there should be a lot to work with :)

**Comment by Tyrasuki** [comment]
Out of curiosity, on the [live demo](https://bluecolored.de/bluemap/#acrana:257:1732:0:312.15:0.01:73) there is a "marked area" called Town. Is this something a plugin is required for? or is this natively included with BlueMap out-of-the-box?

**Comment by TBlueF** [comment]
@tyrasuki You can do that manually by editing/creating the file `bluemap/web/data/markers.json`.
Example: https://github.com/BlueMap-Minecraft/BlueMap/wiki/Markers

**Comment by Tyrasuki** [comment]
Ah, wasn't aware of that. Thanks!

Might be a cool idea to add a command in-game to mark a "radius" rather than a single POI, but I'd guess I'll need to open a new thread for that ;P
