### ISSUE TITLE
[Suggestion] VR Support over Browser

### ISSUE THREAD

**Issue by XCraftTM** [BlueMap-Minecraft/BlueMap#262]
Hey, this might sound a bit weird but just listen to this idea.

I have my VR Headset (Oculus Quest 2) for a while now and some often times i am using Google Earth VR.
Would it be possible to add the functionality to use the move around option for VR?

Reason for this, is Simple. I like to explore Minecraft Worlds in VR but maybe some People have a VR Headset but there is not native Minecraft VR Support for this Standalone Headset, also their PC is not the Best for Minecraft VR. So what if People could look around the map of the World in VR and have the best Time of their life. 

And how it should work just add like a button at the top right of the browser or in the left menu with the Option VR Mode. I know for sure that in the Quest 2 Browser there are VR Games that run over the Browser.

It could be hard to test it. But some People like me can test it. So if you need any help(if you will do it) i am always there to help you.

React with any Emojis if you like this idea...

**Comment by TBlueF** [comment]
A VR-option is a cool Idea that has been around for a while already.
I have nothing against adding a VR Button to BlueMap's menu to enable a way to look at the world using a VR-Headset.

This would of course have the same limitations as the Spectator-Mode: No collisions, so no walking around.

There a two reasons however, why i will not work on this in foreseeable future:
- **I don't own a VR-Headset** - Developing this is only feasible if i can extensively test what i am doing :D Without a VR-Headset, there is no good way for me to test the feature and thus i can not work on it.
- **Low-Priority** - Even if i would own a VR-Headset, this feature would be very low on the priorities for me. There are a lot of important Todo's on the [TODO-List](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true) which I feel like have a higher priority right now :)

For those reasons, i will close this Issue for now.
However i would consider accepting a ***(well designed)*** PR with this, if someone else decides to implement this feature!
