### ISSUE TITLE
The map does not render below Y=0 

### ISSUE THREAD

**Issue by Rafii2198** [BlueMap-Minecraft/BlueMap#263]
Tittle is pretty much self explanatory. Probably happens to above Y=256 but couldn't test.
Basically the extended Y levels in 1.18 are ignored.

BlueMap: v1.7.2 for 1.18 Fabric

**Comment by TBlueF** [comment]
Please provide more info about how to reproduce your issue. *([Contribution Guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/.github/CONTRIBUTING.md))*
I tested the extended world-heights and they worked fine for me :)

Keep in mind that BlueMap doesn't render caves below a configured height by default.

If you need support please visit our [discord](https://discord.gg/zmkyJa3)

**Comment by Rafii2198** [comment]
Oh, I thought the default height for 1.18 would be changed as vanilla changed them, but setting it manually fixed the issue.
