### ISSUE TITLE
Towny Borders support

### ISSUE THREAD

**Issue by TheFlyingCrocodile** [BlueMap-Minecraft/BlueMap#264]
just the ability to see the towny plugins towns and nations similar to this project (https://github.com/TownyAdvanced/Dynmap-Towny)

it would be wonderful if this is easily possible as we would love to use bluemap on our server instead of dymap

**Comment by TBlueF** [comment]
BlueMap does not add native support for other plugins, it provides an API on which other plugins can extend on.

There is https://plugins.mcgsoft.eu/mcg-bluemap-essentials/
and https://github.com/Hafixion/TownyBlue
Both claim to add support for Towny :)
