### ISSUE TITLE
Black playerhead icon

### ISSUE THREAD

**Issue by henrikx** [BlueMap-Minecraft/BlueMap#265]
### What i did / Steps to reproduce

Installed Bluemap as normal. Proxied by nginx and Cloudflare.
### Expected result

Player should show their skin avatar head as their icon on the map.
### Actual result

Player's playerhead icon is black.
![image](https://user-images.githubusercontent.com/10342989/144877379-4e4833ea-203d-4012-aa67-9f8502acc323.png)
![image](https://user-images.githubusercontent.com/10342989/144877419-9b48a1b2-8af0-4b7f-9216-d01a397bf528.png)

This only happened with one single player of ours with UUID `e094991a-810b-4b52-bda5-78e9fd8e98d4`
I already tried to delete their respective PNG in the `web/asserts/playerheads` folder. The player also tried to change to the default Steve-skin also after deleting the old PNG file. There have been several server restarts for the duration of this issue. Also the downloaded PNG file looks correct.
### Context
**BlueMap Version:**  
```
Version: 1.7.2
Commit: 79b6319ec5e36e19d547d73d83eb474c14548f85 (true)
Implementation: bukkit
Minecraft compatibility: 1.18.0 (1.18.0)
Render-threads: 2
Available processors: 4
Available memory: 8000 MiB
```

Minecraft Version 1.18
Paper version:
```
This server is running Paper version git-Paper-54 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: b4a77a8)
You are running the latest version
Previous version: git-Paper-36 (MC: 1.18)
```

There is nothing relevant in the logs about this issue.

**Comment by henrikx** [comment]
Here is a link to the playerhead as served by Bluemap (looks correct)
https://map.mrgreengaming.com/assets/playerheads/e094991a-810b-4b52-bda5-78e9fd8e98d4.png

**Comment by henrikx** [comment]
The issue seems to have been caused by CloudFlare's cache not updating.

**Comment by TBlueF** [comment]
Great issue tho! I whish everyone would do it that detailed and well formatted :) 👍

**Comment by henrikx** [comment]
Actually, the Cloudflare cache was only partially the issue.
It updated the playerhead when the player changed skin back from Steve, and now his playerhead is black again (including the corresponding PNG in the filesystem). This was probably the error that caused his cached playerhead to be black in the first place.

**Comment by TBlueF** [comment]
So one thing that might be the cause of this is that your player's skin seems to be in the (very) old skin-format. BlueMap currently just supports the new skin-format.
If your player updates their skin to be in the new skin-format, then bluemap will likely display it correctly :)

**Comment by henrikx** [comment]
That was the issue 😄 
Thanks for the help.
