### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by HenrikoMagnifico** [BlueMap-Minecraft/BlueMap#266]
**Is your feature request related to a problem? Please describe.**
I want to embed Bluemap on my website, but Wix (and most other website builders) don't support embedding HTTP web pages, only HTTPS. Which makes it impossible to embed Bluemap.

**Describe the solution you'd like**
HTTPS support for Bluemap so that it can be embedded on websites like my own!

**Comment by TBlueF** [comment]
Duplicate, see #132
