### ISSUE TITLE
LiveMap in Browser only displays "Status:OK"

### ISSUE THREAD

**Issue by appollon41** [BlueMap-Minecraft/BlueMap#267]
### What i did / Steps to reproduce
Just installed it and configured it as it is meant to be, reloaded, and rendered the map. (Hoping I haven't done any mistake)

### Expected result
Expected to have access to the LiveMap, using IP:PORT or dns_linked_url:PORT.

### Actual result
Just having a white page just saying: "Status:OK"

### Context
**BlueMap Version:**  
- BlueMap-1.7.2-spigot.jar
- Using a paper 1.18-9 version, which seems stable with every other compatible plugins. Server seems to be running on a Debian (not the owner of it, it's an hoster that provides open ports so we can use plugins like Bluemap, DynMap or JSONAPI etc), with 20go of DDR4 allocated, 6 cores, and 100 Go of storage.
- The world has been generated with a datapack that teleports a player every x blocks every x ticks, which generates the map after several hours, so it's a vanilla like generation. The render is finished.
etc..
- Configuration seems to be correct.

Also:
- Screen attached, in chrome navigator.
![issue](https://user-images.githubusercontent.com/16938618/145430434-87abf155-701b-4dee-99b5-b4b7532e9b98.png)

**Comment by TBlueF** [comment]
That response can not originate from bluemaps webserver. It has to originate from some other webserver/some other programm on your server. Make sure you are actually connection to bluemaps webserver and there is nothing else running on that port.

**Comment by TBlueF** [comment]
If you need support with this please visit our [Discord](https://discord.gg/zmkyJa3). GitHub is not a good place for support :)

**Comment by appollon41** [comment]
Thank you for the quick answer, port seemed to be unavailable, even if I was told it was. Have a nice day.
