### ISSUE TITLE
Usage On Shared Hosting

### ISSUE THREAD

**Issue by LakesideMiners** [BlueMap-Minecraft/BlueMap#269]
I am trying to get this working on a budget plan of BisectHosting, I do not have shell acesss to it, only mulitcraft. I connect to the server either via the free subdomian that they give me, or via the IP and then a port. I have not been able to get BlueMap to work as it just times out when I try to get to it, 
I have tried following the same instrucions they give for DynaMap, which was working for me. by using the subdomain and port, but, that is not working for BlueMap.
Is there somthing im missing?

**Comment by LakesideMiners** [comment]
(gah sorry hit enter too soon, give me a moment)

**Comment by TBlueF** [comment]
Hey!
Sorry, but if you need support, please visit our [Discord](https://discord.gg/zmkyJa3). 
GitHub is not a good place for support :)
