### ISSUE TITLE
1.18 server list feature

### ISSUE THREAD

**Issue by NolanSyKinsley** [BlueMap-Minecraft/BlueMap#270]
Minecraft 1.18 enabled players to stop servers from listing their name in their online players list for privacy reasons. I think it would be ideal to extend this option to your map plugin and if a player has that option enabled, it shouldn't show them on the server's live map. Of course this should also be configurable by server owners as several server play types would be hindered by, or be given an unreasonable advantage by, such a setting.

**Comment by TBlueF** [comment]
This will not be implemented. If this is needed it can be achieved by a 3rd-party plugin using BlueMap's API.
