### ISSUE TITLE
Load biome info from datapacks

### ISSUE THREAD

**Issue by PortableGames** [BlueMap-Minecraft/BlueMap#272]
try to load biome-infos from datapacks for correct display of block color on map

![Screenshot_20211206-182005](https://user-images.githubusercontent.com/89090940/145711269-8fae342d-7bb9-4b4b-873e-8f1ae5379111.png)

used datapack: https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/

**Comment by PortableGames** [comment]
I found this can be used as a temporary solution: https://github.com/StrangeOne101/Datapack-Bluemap-Generator

**Comment by PortableGames** [comment]
![Screenshot_20211221-102743](https://user-images.githubusercontent.com/89090940/146906015-4b9df0ca-989e-4aac-abb7-3a9cc05d9341.png)

**Comment by TBlueF** [comment]
Closing this, as it is a duplicate of #156
