### ISSUE TITLE
Ability to query markers in game by id

### ISSUE THREAD

**Issue by macbrayne** [BlueMap-Minecraft/BlueMap#276]
**Is your feature request related to a problem? Please describe.**
Even though there is a way of creating, listing and removing markers in game there's currently no way of querying the coordinates or the name of markers without accessing the web server.

**Describe the solution you'd like**
`/bluemap marker query <id>` returning an output similar to `<label or id> at <coordinates rounded to full blocks>`

There are some formats which can be directly imported into some mini maps, however they are not standardized making implementing them possibly more time consuming as well as less useful for players not using that mod compared to a "pretty" version.

**Comment by TBlueF** [comment]
BlueMap will likely move away from built-in marker-commands.
This is explained here: https://github.com/BlueMap-Minecraft/BlueMap/issues/211#issuecomment-879784008
With that in mind i will not implement further marker commands into bluemap directly :)
