### ISSUE TITLE
WebGL & CSSless mode

### ISSUE THREAD

**Issue by LKD-PIX** [BlueMap-Minecraft/BlueMap#277]
**Is your feature request related to a problem? Please describe.**
You can't access the webMap on older devices or ones not supporting webgl

**Describe the solution you'd like**
Would be cool to have a Java Script mode without css and webgl that only shows the poly map.
Useful for Devices or People with really old browsers, could optionally be a different url.

Example usage would be javaFX webengine, or older phones
obligatory comparison to dynmap: it works on JavaFX and my old windowsphone

**Comment by TBlueF** [comment]
This would mean creating a completely second map and web-app, since currently literally everything depends on WebGL.
BlueMap is a 3D-Map. So supporting devices that don't support 3D is kind of out of scope ^^
