### ISSUE TITLE
Missing word after purging map

### ISSUE THREAD

**Issue by FaintLocket424** [BlueMap-Minecraft/BlueMap#278]
### What i did / Steps to reproduce
I ran /bluemap purge world

### Expected result
"If you don't want this map to render again after the purge, use /bluemap freeze world first!"

### Actual result
"If you don't this map to render again after the purge, use /bluemap freeze world first!"

### Context
**BlueMap Version:**  
Version: 1.7.2
Commit: 79b6319ec5e36e19d547d73d83eb474c14548f85 (true)
Implementation: fabric-1.18
Minecraft compatibility: 1.18.1 (1.18.0)
Render-threads: 14
Available processors: 16
Available memory: 4096 MiB

<!-- 
Add more context here!
It's just missing the word "want".

Also:
![image](https://user-images.githubusercontent.com/76170255/147368681-11337755-08f3-41c6-bdb7-362f14e0411b.png)

**Comment by TBlueF** [comment]
(4e7deb2562aaeb7efab551e199d5ed6024bddae8)

**Comment by TBlueF** [comment]
Fixed in 2.0
