### ISSUE TITLE
Feature: Right click to tilt should zoom.

### ISSUE THREAD

**Issue by ryantheleach** [BlueMap-Minecraft/BlueMap#279]
**Is your feature request related to a problem? Please describe.**
Trying to use right click to tilt is awkward at heights where tilting is restricted. 

**Describe the solution you'd like**
If tilting is required to be restricted, then right click and drag should zoom as well as tilt, instead of restricting tilt.

**Comment by TBlueF** [comment]
I'll add this to the TODO to test it, but i don't know if this can be implemented without breaking other controls or creating a really weird control-feeling..

What would you expect to happen if you change the angle back? Should it zoom out again, or stay zoomed in?

**Comment by ryantheleach** [comment]
In the same action I would expect it to zoom out.

If released, act as normal.

It's likely to be weird, but less weird then nothing.

**Comment by ryantheleach** [comment]
I had an example of a different map that did similar and felt natural, but I can't find it currently.

It would basically be the inverse of what zooming out currently does if in an angled state.
