### ISSUE TITLE
Better console handling

### ISSUE THREAD

**Issue by untuned** [BlueMap-Minecraft/BlueMap#28]
Console just shows the in-game message.
![](https://untnd.me/qahsSBnzC)

**Comment by TBlueF** [comment]
What exactly would you like to see improved?

I think the biggest problem you have is that your console does not support the colors. However, many consoles do support colors and then it looks more like this:

![image](https://user-images.githubusercontent.com/10765470/77762690-34888e00-703a-11ea-99d3-12871267951f.png)

I can improve the controls to prioritize and cancel a task, so they can be done via console..
Or i can try to remove all colors, i would need more feedback if a lot of people have this color-problem on the console for this.

**Comment by untuned** [comment]
It's part of AMP, it doesn't support colors AFAIK. It uses the `--no-log-colors` option, maybe BlueMap can detect this and change the command output in console?

**Comment by TBlueF** [comment]
@untuned that should be job of spigot/paper/sponge/forge or whatever software handles the console output, since i am only sending response messages using the API..
Plugins don't have access to.. and should not use run-arguments i think..

**Comment by TBlueF** [comment]
Actually i take it back, just checked a spigot version and noticed that this is actually a bug ^^
I will fix that, thanks for the report @untuned :)

**Comment by TBlueF** [comment]
Fixed with 0816529f25ba993f9f9c5672a95428ae2c494bec
