### ISSUE TITLE
Respect collisions for free-flight mode

### ISSUE THREAD

**Issue by ThisIsTenou** [BlueMap-Minecraft/BlueMap#282]
**Is your feature request related to a problem? Please describe.**
Whilst the freeflight mode provides exceptional opportunities to discover the map from a browser, it doesn't respect collisions, eg you can fly through stuff.
This leads to users being able to find hidden bases, explore caves and mine systems they've never been to etc.

**Describe the solution you'd like**
An option to toggle collisions on a per-map-basis, so that users cannot fly through blocks/doors etc.

**Comment by TBlueF** [comment]
This is sadly not feasible.
The reasoning & explanation for this can be found here: https://github.com/BlueMap-Minecraft/BlueMap/issues/108#issuecomment-770389943
