### ISSUE TITLE
CLI app does not keep the same world UUIDs after restarts

### ISSUE THREAD

**Issue by Nestu14** [BlueMap-Minecraft/BlueMap#283]
### What i did / Steps to reproduce
Start rendering a map with Bluemap-CLI
Restart Bluemap-CLI

### Expected result
Configured worlds keep the same UUID

### Actual result
Configured worlds get a new UUID

### Context
**BlueMap Version:**  
`1.7.2-cli`

I know world UUIDs are platform dependant but in case the platform does not provide the UUID, the config should at least keep the one on the web-app settings.json file.

**Comment by TBlueF** [comment]
Fixed in 2.0
