### ISSUE TITLE
Clicking on different maps of the same world does not bring to the startPos

### ISSUE THREAD

**Issue by radiant-ai** [BlueMap-Minecraft/BlueMap#284]
### What i did / Steps to reproduce
I have a render.conf set up like this; note the same world for two different "maps". Actually there are a lot more cities, but I include only one for the reference:
```
maps: [
        {
		id: "spawn"
		name: "spawn"
		world: "world"
		startPos: [-275, -60]
		minX: -1275
		maxX: 725
		minZ: -1060
		maxZ: 940
		
		skyColor: "#7dabff"
		ambientLight: 0.1
		worldSkyLight: 15
		removeCavesBelowY: 59
                caveDetectionUsesBlockLight: false		
		renderEdges: true
		useCompression: true
		ignoreMissingLightData: false
	}
	{
		id: "city1"
		name: "city1"
		world: "world"
		startPos: [-2470217, 2541734]
		minX: -2470717
		maxX: -2469717
		minZ: 2541234
		maxZ: 2542234
		
		skyColor: "#7dabff"
		ambientLight: 0.1
		worldSkyLight: 15
		removeCavesBelowY: 59
                caveDetectionUsesBlockLight: false		
		renderEdges: true
		useCompression: true
		ignoreMissingLightData: false
	}
]
```
In browser I click on maps `spawn` or `city` it switches between the maps, but it does not reset the camera position to the specified `startPos`.
### Expected result
I expect my camera to be centered on spawn point or a city on map selection in browser.

### Actual result
It just switches the map name in the URI without setting the `startPos` as the view position.

### Context
**BlueMap Version:** `BlueMap-1.7.2-spigot.jar`
**Browser**: `Chrome is up to date Version 97.0.4692.71 (Official Build) (64-bit)`
**OS and web-server**: integrated web server running on localhost on Windows 11

**Comment by TBlueF** [comment]
That's an intended feature actually. With that you are able to make "multiple views" for a single world and can switch between both, without it changing your position in the world. 

E.g. nether with / without roof

Your issue seems to be more like that you can't select multiple regions that you want to render. To have them on one map and e.g. switch between them using markers .. And that feature is on the TODO somewhere :)
