### ISSUE TITLE
Render file data is extremely huge

### ISSUE THREAD

**Issue by radiant-ai** [BlueMap-Minecraft/BlueMap#285]
### What i did / Steps to reproduce
I render same HUGE map (2b2t style) in different places (settlements) and use boundaries to make renders with a size of 1000x1000.

### Expected result
I expect to get renders small in size on my drive.

### Actual result
My renders are HUGE in size (20GiBs+ for a 400x400 render)

### Context
**BlueMap Version:** `BlueMap-1.7.2-spigot`

My render config that produces 200GiBs+ of data:
https://paste.gg/p/anonymous/cf7c0251d3454b7c8881d1d2b7f27928

**Comment by TBlueF** [comment]
I might have accidentally removed the boundary-check for the render-queue/region-file-processing, and it is rendering empty files for the whole world -> TODO: check that

**Comment by TBlueF** [comment]
Fixed in 2.0
