### ISSUE TITLE
Render player's head block

### ISSUE THREAD

**Issue by Shapaper** [BlueMap-Minecraft/BlueMap#287]
有许多服务器在玩一个叫做Slimefun的插件，他不需要客户端装对应mod，插件的的机器都是通过玩家头颅实现的，我希望可以像箱子一样，提出个临时的渲染方式
Many servers are playing a plug-in called slimefun. They don't need the client to install the corresponding mod. The machines of the plug-in are realized through the player's head. I hope to propose a temporary rendering method like a boxheadhead
![X}(T$}18J$5UY{}%7T42LRW](https://user-images.githubusercontent.com/88654772/151921277-aaa69e12-8562-4c53-a6f7-4fe447accfc4.png)

**Comment by Shapaper** [comment]
额

**Comment by Shapaper** [comment]
emm

**Comment by Shapaper** [comment]
five months ago

**Comment by TBlueF** [comment]
And it will take many more.
See the [TODO list](https://github.com/BlueMap-Minecraft/BlueMap/projects/1#card-79577741) for an idea of what i am working on and the priority of this issue.

BlueMap is OpenSource, if you need this faster, do it yourself :)

**Comment by TBlueF** [comment]
Closing in favor of #145
