### ISSUE TITLE
Markers disappear when one marker is removed until a reload

### ISSUE THREAD

**Issue by TechnicJelle** [BlueMap-Minecraft/BlueMap#289]
#### With the BlueMapOfflinePlayerMarkers addon
1. Log in to the server with account A.
2. Log back out.
3. Log in with Account B. On the map, you'll see one black and white playerhead of player A and one colour playerhead of player B.
4. Log back out with Account B.
5. Once you log back in with either account, you'll see that (after the few seconds it takes for markers to update) the black and white marker for that account is removed from the map. **But you'll also notice that the marker of the other account has also disappeared!** If you check `markers.json`, though, you'll see that the marker is still in there, like it should be. If you reload the BlueMap webpage, the marker shows up again like it should.

#### With the PlayerWarps plugin
1. Make a warp with `/pwarp set hello`.
2. Move to a different location and make another warp with `/pwarp set world`. You'll now see two ℹ️ markers on the map.
3. Remove a marker with `/pw remove hello`
4. You'll now see that not only the marker for "hello" disappears, but both markers have vanished!

### Expected result

I expect only the marker that is removed (through my code) to disappear.

### Actual result

Instead of all markers (in that set? I haven't been able to confirm if all markers disappear or only the ones in that particular set.) to disappear.

### Context
**BlueMap Version:**  
`Version: 1.7.2`
`Commit: 79b6319ec5e36e19d547d73d83eb474c14548f85 (true)`
`Implementation: bukkit`
`Minecraft compatibility: 1.18.1 (1.18.0)`
`Render-threads: 14`
`Available processors: 16`
`Available memory: 1024 MiB`

This is an issue I have only reproduced using my plugin BlueMapOfflinePlayerMarkers, but I don't think it's an issue with that, because the markers.json file itself is always still correct. I'll update this issue with more info once I've tested other BlueMap addons too.

Edit: I have managed to confirm this happening with the PlayerWarps plugin too.

This issue doesn't happen with BlueMap's own built-in marker commands.

**Comment by TBlueF** [comment]
Should be fixed in 2.x .. please reopen if the issue persists :)
