### ISSUE TITLE
maybe the text of wiki has a error

### ISSUE THREAD

**Issue by QKDV** [BlueMap-Minecraft/BlueMap#290]
https://bluemap.bluecolored.de/wiki/webserver/NginxProxy.html#bluemap-on-a-subdirectory-of-your-website

```
  location /map/ {
    proxy_pass http://127.0.0.1:8100/;
```
that cannot be run on my server
the error of web is 404

```
  location ^~ /map {
    proxy_pass http://127.0.0.1:8100/; 

```  
this can be run

i dont know why

### Context
**BlueMap Version:**  
`1.0.0-fabric-1.16.1`

**Comment by TBlueF** [comment]
Which setting works for you depends on the rest of your nginx config. The setting in the wiki is an **example** of how it could work, but you'll have to adapt it for your setup. Which you did 👍 but it's not an error in the wiki :)
