### ISSUE TITLE
Texture alpha is not rendered correctly sometimes

### ISSUE THREAD

**Issue by BuyMyMojo** [BlueMap-Minecraft/BlueMap#295]
### What I did / Steps to reproduce
Create a powered repeater, redstone torch or comparator

### Expected result
Render correctly

### Actual result
Two pixel transparent section on all lit redstone torch objects

### Context
1.7.2-cli

Windows 11

Minecraft 1.18.2 + fabric

Resource pack is `mattbatwings` pack from YouTube, attached here because download requires joining the discord
[MattPack1.18.zip](https://github.com/BlueMap-Minecraft/BlueMap/files/8174887/MattPack1.18.zip)

Recordings:
- [Repeater](https://files.buymymojo.net/tjwoup2aagiv.gif)
- [Torch](https://files.buymymojo.net/tsx6mi2pf5i7.gif)
- [Comparator](https://files.buymymojo.net/nhpuo31jkl82.gif)

**Comment by TBlueF** [comment]
The lit-redstone-torch texture in that resource-pack has two pixels left and right that seem to be somehow differently stored than the other pixels .. this seems to confuse the shader.
My guess would be that this [if-statement](https://github.com/BlueMap-Minecraft/BlueMapWeb/blob/aa4cf7285d191ae8da58e0c62dd9d586f586a1b3/src/map/hires/HiresFragmentShader.js#L50) in the shader is not triggering for some reason.
Needs more testing.
