### ISSUE TITLE
More small-scale map

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#3]
We already know that it can be scaled down to smaller scales.
However, my server found it needed to be scaled down to see the map properly.
I wish there was a more powerful number (e.g. between 5000 and 8000) than the current 2000 (the number written in the plugin's address). (If applied directly to a link, it will not load all maps, only the size optimized for 2000)

(Sorry, Google Translate)

**Comment by TBlueF** [comment]
There are currently 2 scales.. the hires-models of your minecraft world and the lowres flat tilegrid that  you can see if zoomed out.
To make a more zoomed-out view, a third scale is needed.
I might try to add that in the future.

**Comment by ghost** [comment]
thank you :D

**Comment by djytw** [comment]
I think it's better to add a 2d overview as the 3rd scale, since it's hard to distinguish height from that scale

**Comment by henrikx** [comment]
What is the status of this? This is currently the most requested feature by the players on my server.

**Comment by TBlueF** [comment]
@henrikx This issue is vaguely prioritized in the [TODO-List](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true) .. There is a lot of stuff that needs to be done first, before i can start working on this issue

**Comment by henrikx** [comment]
> @henrikx This issue is vaguely prioritized in the [TODO-List](https://github.com/BlueMap-Minecraft/BlueMap/projects/1?fullscreen=true) .. There is a lot of stuff that needs to be done first, before i can start working on this issue

Thanks! I'll keep the off-topic discussion brief, but I wanted to say you did a great job with this plugin. Thanks again for your hard work.

**Comment by TBlueF** [comment]
Implemented with 3.0
