### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by whes1015** [BlueMap-Minecraft/BlueMap#301]
How do I create a map backup and record the changes in the terrain

**Comment by TBlueF** [comment]
GitHub is the wrong place for support, please join us on [Discord](https://discord.gg/zmkyJa3) or [Reddit](https://www.reddit.com/r/BlueMap/), we will be glad to help you there :)
(https://github.com/BlueMap-Minecraft/BlueMap/blob/master/.github/CONTRIBUTING.md)
