### ISSUE TITLE
Use Skin Restorer's player skins on offline servers

### ISSUE THREAD

**Issue by DavidCZ2051** [BlueMap-Minecraft/BlueMap#302]
[Skin Restorer mod](https://github.com/Suiranoil/SkinRestorer) is a server-side mod that allows players to have skins on an offline server.

It would be nice if BlueMap could use the SkinRestorer's player heads instead of the Steve/Alex heads. The skins are stored in `config/skinrestorer` in a JSON file. This could also be used in #95 for the full player skin.

I think offline servers would really appreciate this feature :)

**Comment by Chicken** [comment]
Won't be added to BlueMap, but we have addons for that.
https://www.spigotmc.org/resources/bluemapofflineskinsupport.91486/
and
https://www.spigotmc.org/resources/bluemap-skins.90284/

edit: so far these addons are spigot only, somebody gotta make a fabric/forge/whatever versions
