### ISSUE TITLE
Dose the forge version work with 1.18.2 server side?

### ISSUE THREAD

**Issue by VirtualGaming1** [BlueMap-Minecraft/BlueMap#304]
I just want to ask and I did check in the search before posting and did not see any but I am woundering if the current Forge version work with 1.18.2?

**Comment by TBlueF** [comment]
[BlueMap-1.7.2-forge-1.18.1](https://www.curseforge.com/minecraft/mc-mods/bluemap/files/3634499) does work on 1.18.2, yes.
But please keep Quesions on Discord or Reddit, GitHub issues are not for support :)

**Comment by VirtualGaming1** [comment]
Thanks for a quick answer!
