### ISSUE TITLE
Quark Chests not appearing in rendered map

### ISSUE THREAD

**Issue by michele-grifa** [BlueMap-Minecraft/BlueMap#305]
### What i did / Steps to reproduce

- Install Quark Mod
- Put Quark jar in resourcepacks folder
- Render The map
- Quark Chests not appearing

### Expected result
Quark Chests should be rendered.

### Actual result
No blocks are rendered instead of the chests, as if they weren't there

### Context
**BlueMap Version:** 1.7.2-forge-1.18.1
**Minecraft Version:** 1.18.2
**Quark Version:** 3.2.357
**Forge Version:** Forge 40.1.0

### The Render
![Schermata del 2022-05-28 10-51-27](https://user-images.githubusercontent.com/33720244/170818533-45472dc3-8564-4c79-9144-d04f6a84df69.png)

### In-Game
![photo_2022-05-28_11-00-05](https://user-images.githubusercontent.com/33720244/170818588-2220b8d3-d719-40ef-9967-7ac659261a01.jpg)

**Comment by TBlueF** [comment]
Chests in general are Tile-Entities and their Models are defined in Code. For vanilla-chests (and signs etc.), bluemap provides a resource-pack that adds those models in resource-pack format, so BlueMap can read it. For quark-chests and other tile-entities that are added by modes, you can do the same thing. 
But, BlueMap will not include those resources for anything other than vanilla Blocks :)

**Comment by michele-grifa** [comment]
Is there any guide or tips on how to do this?

**Comment by TBlueF** [comment]
Basically any Guide on ResourcePacks with custom Block-Models will do most of it ... anything else you can ask about, in our [Discord](https://discord.gg/zmkyJa3) :)
As reference, this is the Resource-Pack that is builtin to BlueMap and provides chests and other tile-entities for vanilla-minecraft: https://github.com/BlueMap-Minecraft/BlueMap/tree/master/BlueMapCore/src/main/resourceExtensions/mc1_18
