### ISSUE TITLE
Resource Packs cause Bluemap crash

### ISSUE THREAD

**Issue by laolarou726** [BlueMap-Minecraft/BlueMap#306]
### What i did / Steps to reproduce

+ Add a resource pack to the config folder
+ Reload Bluemap using ```/bluemap reload```
+ Error shows

### Expected result

+ Bluemap successfully reload

### Actual result

<img width="927" alt="image" src="https://user-images.githubusercontent.com/25716486/171049356-666d222e-7124-4b11-91b4-c87d9a5ffe97.png">

### Context
**BlueMap Version:**  
`BlueMap-1.7.2-fabric-1.18`

**Comment by TBlueF** [comment]
Will be fixed with https://github.com/BlueMap-Minecraft/BlueMap/issues/129

**Comment by laolarou726** [comment]
Got it! Thanks!

**Comment by TBlueF** [comment]
Closing this. Has been fixed long ago, looks like i missed this issue.
