### ISSUE TITLE
Lighting bug next to chunk border

### ISSUE THREAD

**Issue by roxandtol** [BlueMap-Minecraft/BlueMap#311]
### What i did / Steps to reproduce
Empty chunk next to a chunk with stuff

### Expected result
Everything lit up uniformly

### Actual result
Lighting bug

### Context
**BlueMap Version:**  
`1.7.3-spigot`

- Ubuntu 22.04 LTS
- 1.18.2 server
- Purpur
- Using Pufferpanel to host it

Also:
![img](https://cdn.discordapp.com/attachments/751804128749027421/988928457905950771/unknown.png)
![img](https://cdn.discordapp.com/attachments/751804128749027421/988928458275037244/unknown.png)

**Comment by TBlueF** [comment]
Possibly related or similar: 
![image](https://user-images.githubusercontent.com/10765470/196997913-2ede6816-1754-499b-a564-6143b7fcbbb1.png)

**Comment by GuillaumeFX** [comment]
Same problem here :

![Image](https://user-images.githubusercontent.com/77529874/197183453-8f0ddb2e-8a8a-4468-b0bc-607e2e8a46e6.png)

**Comment by TBlueF** [comment]
@GuillaumeJeu nope, that's something different, this looks like the lighting is actually wrongly calculated there by minecraft ... try placing/breaking a block there to fix :)

**Comment by GuillaumeFX** [comment]
Okay, thanks ^^

**Comment by TBlueF** [comment]
Fixed with faa6965df3322365fc92dde074b793dae11f18da and ad4ae53672bbbdc756b45c25698a8c53b6fce9ae
