### ISSUE TITLE
[Feature] BungeeCord Support

### ISSUE THREAD

**Issue by CJYKK** [BlueMap-Minecraft/BlueMap#313]
**Is your feature request related to a problem? Please describe.**
No, this is just a feature request.

**Describe the solution you'd like**
If you have multiple servers in your BungeeCord network, you can install BlueMap on each server and use a Web Server together, where you can view the map for each server (just like Plan).

Thank you :-)

**Comment by TBlueF** [comment]
Already planned and being actively worked on :)
See: #138 and #80

**Comment by CJYKK** [comment]
> Already planned and being actively worked on :) See: #138 and #80

Oof, I diden't see that. Thank you!
