### ISSUE TITLE
Export the world to a static site for visiting

### ISSUE THREAD

**Issue by Ranzeplay** [BlueMap-Minecraft/BlueMap#314]
My server is shut down at night, and I wonder if there's a way to export the map that my friends can view on a browser when the server is down?
Maybe we can export the map as a static website?

**Comment by TBlueF** [comment]
Basically just host the map with an external webserver that keeps running when the server is down..
 https://bluemap.bluecolored.de/wiki/webserver/ExternalWebservers.html

If you have more questions about bluemap or need further support, please join our Discord :)
