### ISSUE TITLE
Mod Texture Show Problem

### ISSUE THREAD

**Issue by silverfox0000** [BlueMap-Minecraft/BlueMap#315]
### What i did / Steps to reproduce
1. Install **Mekanism** with **Mekanism Additions**
2. Place random color  of plastic
3. Render

### Expected result
View plastic of placed color

### Actual result
Viewed green plastic

### Context
**BlueMap Version:**
`1.7.3-spigot-1.16.5`

- The used os and platform: Linux, Bukkit + Forge (ArcLight) **P.S With Forge Mod The problem not has gone**
- The world was been generated by mods
- The Assets of mods are loaded by BlueMap

### Screenshots

In web: https://i.imgur.com/nWTzO9q.png
In game: https://i.imgur.com/0M33Rlr.png

**Comment by TBlueF** [comment]
Those blocks are likely "tinted" in their special color.
You'll have to configure that tint so the color is correct, see: https://bluemap.bluecolored.de/wiki/customization/Mods.html#block-colors-config

If you need help with this, please visit our [discord](https://discord.gg/zmkyJa3) :)
