### ISSUE TITLE
Disable coordinates

### ISSUE THREAD

**Issue by wiselder** [BlueMap-Minecraft/BlueMap#319]
Is there a planned option to disable coordinates in any form in a web application?
This will be useful for servers with /gamerulereducedDebugInfo true

**Comment by TBlueF** [comment]
There is no such option planned, no.
You can with some JS-Knowledge clone the `BlueMapVue` repo and easily remove them yourself..
Ofc it will still always be easy to get the coordinates with a simple js-command in the browser-console.

If you have further questions about this, please visit us on our [discord](https://discord.gg/zmkyJa3) :)
