### ISSUE TITLE
Error with texture-cropping on some java versions

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#32]
https://gist.githubusercontent.com/kencinder/1dd34ed1d06ab3fe6ada840053db214f/raw/c29df251eff8861c7e1a3004c161018440201373/gistfile1.txt

**Comment by TBlueF** [comment]
Should be fixed with the latest version..
@kencinder maybe you can test this?.. And reopen it if the error persists :)

**Comment by kencinder** [comment]
I checked my logs since updating and I'm not seeing any errors related to this.
