### ISSUE TITLE
BlueMap fails to load any maps!!!

### ISSUE THREAD

**Issue by etzabo** [BlueMap-Minecraft/BlueMap#321]
I keep trying to render my 1.12.2 world with no mods, but BlueMap keeps telling me the render threads are idle! How rude! Even when I force-render the world, it keeps those dang diddly render threads cold! Needless to say, BlueMap is being quite uncouth! I've prepared a moving picture demonstration here: https://drive.google.com/file/d/168THFOQRBoST45kPSswU5TT856SUHW6b/view?usp=sharing

**Comment by Seercat3160** [comment]
I suggest that you join the Discord server if possible for support on using BlueMap, it's much easier to communicate that way than GitHub issues.
Here's the link: https://bluecolo.red/map-discord

**Comment by etzabo** [comment]
I figured it out. I'm running 1.12.2. I'm crying currently.

**Comment by TNTUP** [comment]
1.12.2 isn't supported, not sure what version supported that, iirc Bluemap 1.5.5 or lower, idk

**Comment by NikitaCartes** [comment]
Latest release that can be run on 1.12.2 servers https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v1.5.5
