### ISSUE TITLE
Add SQLite support

### ISSUE THREAD

**Issue by oddlama** [BlueMap-Minecraft/BlueMap#322]
**Is your feature request related to a problem? Please describe.**
I was excited to try the new SQL storage backend, but noticed that BlueMap unfortunately doesn't support the SQLite driver. It seems to require a MySQL compatible dialect, which renders the SQLite driver unable to process its requests.

**Describe the solution you'd like**
I'd like to propose adding SQLite support to BlueMap. Especially for Minecraft related use-cases, SQLite should be close to the ideal database, due to natually low request concurrency and the benefits it gains from in-process mapping and its simplicity. See [this HN thread and the linked article](https://news.ycombinator.com/item?id=29727707) for a more profound explanation of why it should be considered for "small-scale" (<100TB) databases.

Thank you for this awesome plugin!

**Comment by InoryS** [comment]
I also want SQLite, a small fast SQL server would be better than file storage, and we don't have to worry about using too many resources. 

The existing MySQL servers in the network are usually designed for high-performance services, which will cause them to use a lot of resources, and may even be multi-node high-availability services. 

Not to mention that BlueMap's gzip-compressed data can easily exceed 35GB (10k x 10k world). BlueMap data can be regenerated at any time, so we don't need to consider high availability and seriously no need to backup them, we also don't need super high performance.

It seems a bit wasteful to host BlueMap data on an existing MySQL  server, and it seems even less cost-effective to set up a separate MySQL server for BlueMap. Not just resources, but the work it takes to manage a MySQL server, SQLite requires almost no administration.

So I think SQLite is a good choice.

**Comment by TBlueF** [comment]
No convincing needed, this will be added, it's on the Todo ;)
