### ISSUE TITLE
Shape Markers not Rendering correctly

### ISSUE THREAD

**Issue by Angeschossen** [BlueMap-Minecraft/BlueMap#323]
### What i did / Steps to reproduce
```
                shapeMarker = ShapeMarker.builder()
                        .shape(new Shape(vector2ds), height)
                        .label(label)
                        //.minDistance(125)
                        .maxDistance(Double.MAX_VALUE)
                        .build();

                markerSet.getMarkers().put(id, shapeMarker);
```

### Expected result
They should always display.

### Actual result
They're only visible when the map is blurry (not fully rendered).
Once the chunks start rendering, the markers disappear. 

### Context
BlueMap version 3.3
git-Paper-111 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 02831e3)
No mods.

**Comment by TBlueF** [comment]
I am guessing they just hide behind the terrain .. so adding `.depthTestEnabled(false)` to the markers should fix your issue :)

**Comment by Angeschossen** [comment]
That was it, thanks! Do POIMarker's support html?

**Comment by TBlueF** [comment]
No, they don't .. only the `detail` or `html` from the other markers can have html in it .. the `label` can't ^^
