### ISSUE TITLE
Import markers from DynMap

### ISSUE THREAD

**Issue by girugamoz** [BlueMap-Minecraft/BlueMap#332]
**Is your feature request related to a problem? Please describe.**

I'm using both DynMap and BlueMap and I want to import existing map markers from DynMap into BlueMap.

**Describe the solution you'd like**

I created a basic [converter](https://girugamoz.github.io/minecraft/convert-map-markers/): If you think this could be useful to others, too, then feel free to link to it. Feedback welcome.

**Comment by TBlueF** [comment]
Very cool! I'll add that to the list of 3rd-party tools in the [wiki](https://bluemap.bluecolored.de/wiki/customization/3rdPartySupport.html) and in our [discord](https://discord.gg/zmkyJa3) :)

**Comment by TBlueF** [comment]
added :)
