### ISSUE TITLE
[Incompatible ?] with C2ME - BlueMap is fully black

### ISSUE THREAD

**Issue by xR4YM0ND** [BlueMap-Minecraft/BlueMap#333]
When generating new chunks the console gets spamed with:

"No Config Info was present"

[latest.log](https://gist.github.com/SpigotDE/8a1d74ee2c82f1479e7195d7f07b4684)

Fabric 1.19.2

**Comment by TBlueF** [comment]
Based on your logs, BlueMap looks like it's running fine.
You'll need to ask the C2ME-Devs about the "No Config Info was present" error, to me it doesn't seem like there is a connection between BlueMap and that error at all.

If your map is fully black, please check out this FAQ: https://bluemap.bluecolored.de/wiki/FAQ.html#q-i-have-a-black-map--a-lot-of-the-map-is-missing

And if you need more support, you can visit us on our Discord: https://discord.gg/zmkyJa3

**Comment by xR4YM0ND** [comment]
### First Problem ( Config save with Texteditor Atom )
When i save your configs with the texteditor "Atom" this happens: "No Config Info was present"

### Second Problem ( Concurrent Chunk Management Engine & Bluemap incompatible ? )
Blue Map loads up normally , all fine, but when i add the mod C2ME it stops rendering somehow.

https://www.curseforge.com/minecraft/mc-mods/c2me-fabric

I think C2ME is incompatible with BlueMap. Pls try this for yourself

**Comment by syorito-hatsuki** [comment]
I tested some week ago 1.7.3 Bluemap with C2ME and it worked. Later I will try it with new 3.3V

**Comment by TBlueF** [comment]
I just tested it..
![image](https://user-images.githubusercontent.com/10765470/187211931-e05ba205-4513-4bd5-903a-1a7f77f075dd.png)
It works fine.

And as i already said, the `No Config Info was present` message is **not from BlueMap**.

**Comment by syorito-hatsuki** [comment]
> 

With `c2me-fabric-mc1.19-0.2.0+alpha.8.2` and `BlueMap-3.3-fabric-1.19`
![image](https://user-images.githubusercontent.com/33298273/187212230-99511a41-3345-4770-b725-f5cbb0a646a4.png)
All right

**Comment by xR4YM0ND** [comment]
damn ok, i try it again and let the server load even longer, hopefully it works.

**Comment by xR4YM0ND** [comment]
For all of you out there that have the same problem:

I've changed C2ME's config "chunkStreamVersion = 3"  , dont do this with BlueMap installed.

Delete the C2ME config, start up and it should work
