### ISSUE TITLE
error while starting websetrver 

### ISSUE THREAD

**Issue by nimex16** [BlueMap-Minecraft/BlueMap#348]
08.10 21:43:44 [Server] [INFO] [BlueMap] Loading textures...
08.10 21:43:45 [Server] [INFO] [BlueMap] Baking resources...
08.10 21:43:45 [Server] [INFO] [BlueMap] Resources loaded.
08.10 21:43:45 [Server] [INFO] [BlueMap] Initializing Storage: 'file' (Type: FILE)
08.10 21:43:45 [Server] [ERROR] [BlueMap] Error while starting the WebServer!
08.10 21:43:45 [Server] [INFO] java.net.BindException: Address already in use
08.10 21:43:45 [Server] [INFO] at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
08.10 21:43:45 [Server] [INFO] at sun.nio.ch.Net.bind(Net.java:552) ~[?:?]
08.10 21:43:45 [Server] [INFO] at sun.nio.ch.Net.bind(Net.java:541) ~[?:?]
08.10 21:43:45 [Server] [INFO] at sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643) ~[?:?]
08.10 21:43:45 [Server] [INFO] at java.net.ServerSocket.bind(ServerSocket.java:386) ~[?:?]
08.10 21:43:45 [Server] [INFO] at java.net.ServerSocket.<init>(ServerSocket.java:273) ~[?:?]
08.10 21:43:45 [Server] [INFO] at de.bluecolored.bluemap.common.webserver.WebServer.start(WebServer.java:75) ~[BlueMap-3.4-spigot.jar:?]
08.10 21:43:45 [Server] [INFO] at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:203) ~[BlueMap-3.4-spigot.jar:?]
08.10 21:43:45 [Server] [INFO] at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[BlueMap-3.4-spigot.jar:?]
08.10 21:43:45 [Server] [INFO] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-"fc9ee65"]
08.10 21:43:45 [Server] [INFO] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-"fc9ee65"]
08.10 21:43:45 [Server] [INFO] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-"fc9ee65"]
08.10 21:43:45 [Server] [INFO] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
08.10 21:43:45 [Server] [INFO] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
08.10 21:43:45 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
08.10 21:43:45 [Server] [INFO] [BlueMap] Loaded!

**Comment by Chicken** [comment]
Hey, issues are for reporting bugs. Our Discord server is for support. But in this case you've used a port for BlueMap that's already in use by another program. Perhaps you used the same port as the Minecraft server? Try again with a different one.
