### ISSUE TITLE
Bluemap purge not working when chunks are deleted

### ISSUE THREAD

**Issue by Notoriousi** [BlueMap-Minecraft/BlueMap#356]
### What i did / Steps to reproduce
I had a full bluemap rendered and decided it was time to "purge" chunks using external programs. I deleted a lot of chunks and then decided to run a couple /bluemap purge command for each map. All chunks that were deleted weren't (fully?) purged, only the ones that remained got purged and updated.

### Expected result
I expected all old (no longer existing) chunks to be purged too.

### Actual result
Only chunks that still exist got purged.

### Context
Bluemap version:
`BlueMap-3.5-fabric-1.19.jar`
Using SQL storage
Map example: http://map.pandara.org/ (zooming in and out shows interesting results)

**Comment by TBlueF** [comment]
@Notoriousi Did you press this button:
![image](https://user-images.githubusercontent.com/10765470/198902313-57478e41-cb70-424a-99f8-43168d4fa7ed.png)

No weird artifacts for me, on that map :)

**Comment by Notoriousi** [comment]
Well, oops! I really thought I had, but after pressing it issue does indeed not prevail. Sorry for the issue report!
