### ISSUE TITLE
Hidden marker blocks interaction with visible

### ISSUE THREAD

**Issue by NejakejTomas** [BlueMap-Minecraft/BlueMap#358]
### What i did / Steps to reproduce
I created two POI markers with label at the same location but with different show distance. One had **max** distance 99 and the other one had **min** distance 100.

### Expected result
I expected both of them to be clickable.

### Actual result
Only one can be clicked. When map is zoomed out/in and the other one is visible, then it cannot be clicked. Seems random which one it is.

### Context
**BlueMap Version:**
`3.5-fabric-1.19`

It seems like one is blocking click action to the other because it has opacity set to 0 and is not "gone". Also this does not only happen to markers with same coordinates but every time one is invisible in front of each other (although is is harder to notice because that is generally not the way markers are placed)

This bug removes the ability to place two "details" of a marker at the same location with different zoom

**Comment by TBlueF** [comment]
Fixed in 45b02d9f5c8bb458153e359b3313762746fa6df5

Fix will be included in the next release :)

**Comment by NejakejTomas** [comment]
I tried building it from source but sadly is still seems not to work.

I think the issue lies in using opacity as a way to hide markers. From what I've read the solution is using also visibility (it can be "animated" to match opacity) but I don't know enough JS to fix it (and I don't know what would happen with line and extrude markers if they are using it too). I tried poking in it but sadly I can't get it to work (to be honest I can't even seem to get it to do anything different when clean build the project)

**Comment by TBlueF** [comment]
It is not only using opacity to hide the marker, the marker is now given the css-property `display: none` if the opacity is 0

I updated the demo map with the newest version: https://bluecolored.de/bluemap/#overworld:-949:60:178:43:0.09:0.63:0:0:perspective
That poi marker does exactly what you described. Its two markers on top of each other and you can click both now, based on how far you zoomed in/out :)

You can use the build provided here: https://github.com/BlueMap-Minecraft/BlueMap/actions/runs/3385838250 (Artifacts button)
Try that one, it works fine on my end :)

**Comment by TBlueF** [comment]
Also: Make sure to delete the `./bluemap/web/index.html` after you updated, so the new build actually updates your webapp ^^
