### ISSUE TITLE
Fabric Version?

### ISSUE THREAD

**Issue by NeusFear** [BlueMap-Minecraft/BlueMap#36]
Hi, this is just a quick question, have you looked at fabric api as an option for this mod? it seems like it's an up-and-coming alternative for mods/plugins like dynmap (I hope it's not against the rules to say that here lol) and so I thought it might be a cool option to allow it's use on a new and up-and-coming platform like fabric.

Anyways I know you're a busy guy probably, so it's understandable if not, but the Fabric community is always willing to help with ports and things. The architecture is pretty close to vanilla and it uses mixins for things so since you've worked with sponge, I bet it would be pretty simple to at least look into.

Thanks for considering!

**Comment by TBlueF** [comment]
Ooh, I have not had FabricAPI on my radar until now, tbh ^^'
I will definitely look into that..

**Comment by NeusFear** [comment]
Awesome! Feel free to join the fabric discord (fabricord) if you have questions or anything, they also have a wiki for things like commands and stuff. It's a really cool api and it could be the pilot branch for testing out snapshot stuff too since it updates on the day snapshots release 99% of the time

**Comment by TBlueF** [comment]
Fabric version is now working, merged and will be released with the next release :)
