### ISSUE TITLE
Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by D4rkD0me** [BlueMap-Minecraft/BlueMap#360]
### What i did / Steps to reproduce
I tried installing the plugin.

### Expected result
plugin getting loaded but it did not

### Actual result
i got an error

### Context
BlueMap Version 1.19 / 1.18 / 1.16.1

Also:
- Is there a log- or a config-file that might help? Include it.
- Maybe add a screenshot or video for illustration.

https://hastebin.com/buyexexesa.apache

**Comment by Chicken** [comment]
Hi,
according to your logs you are running on spigot but the file you downloaded is for fabric. Use the [correct version](https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v3.6/BlueMap-3.6-spigot.jar).
Also according to our [contribution guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/.github/CONTRIBUTING.md) issues are for reporting bugs. For support hop on our [Discord server](https://bluecolo.red/map-discord).

**Comment by D4rkD0me** [comment]
I'm so sorry. My bad...

Have a nice day and thank you for your fast reply :)
