### ISSUE TITLE
Chest culling issue

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [BlueMap-Minecraft/BlueMap#371]
Version: 3.7, paper-307 (1.19.2)

I've noticed this at least since 3.4, still present in the latest version. Might be related to #347.
The actual map to see the bug: https://bpnet.work/bluemap/#world:-991:74:-202:0:1.94:1.3:0:0:free
![image](https://user-images.githubusercontent.com/12040085/208337374-5c0f338c-4087-4f88-9518-7f7a6a2519af.png)

**Comment by BuIlDaLiBlE** [comment]
I've checked this again today and it seems like the issue got resolved somehow. Very weird, as at the time of creating this issue I was already on the latest version.

**Comment by TBlueF** [comment]
The models only get fixed once the region gets updated/rendered again in the new version .. so that probably happened :)
I'll close this then, thanks for reporting back!
