### ISSUE TITLE
Add support for Geyser Floodgate skins

### ISSUE THREAD

**Issue by exstrim401** [BlueMap-Minecraft/BlueMap#377]
https://docs.creepernation.net/skinapi
This SkinAPI checks for UUID and redirects either to Java or to Bedrock skin URL
Floodgate UUIDs looks like 00000000-0000-0000-xxxx-xxxxxxxxxxxx

**Comment by TBlueF** [comment]
BlueMap has an API which allows anyone to make an addon-plugin that changes the way skins are resolved.
So support for external Skin-API's this will not be implemented in bluemap itself but be the job of an addon :)

[Here](https://bluemap.bluecolored.de/wiki/customization/3rdPartySupport.html) is a list of known 3rd party addons, there is also one that adds Floodgate support :)
