### ISSUE TITLE
Black web screen - followed FAQ.

### ISSUE THREAD

**Issue by wolfopera** [BlueMap-Minecraft/BlueMap#380]
### What i did / Steps to reproduce

I installed the map. Upon giving it time, I noticed it had a black screen on the web browser, and I followed the installation instructions + checked the FAQ. I did the reset, I checked my port, and I checked my mod list. I don't have any of the incompatible mods listed. :(

### Expected result

I expected the web browser map to load up my map fine.

### Actual result

It gave me a black screen, and also: a command error-ish when I typed in "/bluemap debug block"

### Context
**BlueMap Version:**  
BlueMap-3.9-forge-1.18.1.jar

- The used os and platform (Windows/Linux, Spigot/Paper/Forge/Fabric/Sponge)
Forge Version.
- Has the world been generated using any minecraft-mods?
Yes. We have a mod pack called "AON: All of Nexus - Forge. 1.18.2" installed + the mod Simple Voice Chat. 
![blackscreen](https://user-images.githubusercontent.com/107643643/211045501-c676d1a1-acfa-4d22-8b8a-24e98e61bc3c.png)
![blackscreen2](https://user-images.githubusercontent.com/107643643/211045502-e55a71b4-6170-4096-8624-8fbe3b4ab6d7.png)

etc..

Also:
- Is there a log- or a config-file that might help? Include it.
- Maybe add a screenshot or video for illustration.
--> I've attached the latest server log file, just in case. 
[latest (16).log](https://github.com/BlueMap-Minecraft/BlueMap/files/10361260/latest.16.log)

**Comment by TBlueF** [comment]
Alright, so i've setup that modpack real quick to test BlueMap myself, and after spawning in a village and being attacked by a barbarian *(rude!)* ... i checked the map and it worked fine :D

![image](https://user-images.githubusercontent.com/10765470/211056679-6da2da0d-478e-429f-9bf0-c1c43652482d.png)

**However**, as you can see in this image, the "main"-overworld wasn't selected by default. BlueMap added maps for all extra dimensions that this mod added, and the main world doesn't seem to be the first one by default. So i also had a black map, until i switched to the correct map :)

You might have ran in the same issue .. have you checked if you selected the correct map? ^^

**Comment by wolfopera** [comment]
![completelyblack](https://user-images.githubusercontent.com/107643643/211059870-a2a608c8-2150-4cc7-99eb-538c35cacbc3.png)

Yes, unfortunately. :( Unless I'm just not clicking the right spot but I clicked the first "Overworld" and let it load and nothing - black screen. I don't understand. I realized that I forgot to mention that I also have Chunky & Followers Teleport Too mods! I don't know if Chunky is messing with it or not.

**Comment by TBlueF** [comment]
Yes that's what i mean .. don't click the first one but check through them each, one of them should be the correct map ^^

*(Chunky has been proven to work fine with bluemap =) )*

If that's not it, then - if possible - send me a link to your map so i can take a look and do a `/bluemap debug dump` and send the generated file to me.

Also this is not really the best place for this, so if you want to join our [Discord](https://discord.gg/zmkyJa3) we could discuss this way more efficiently there :)
*(You can also send me the file and link there if you don't want to send them publicly here)*

**Comment by TBlueF** [comment]
*(resolved in discord: map needed to finish rendering and it was the last "overworld" in the map-list)*
