### ISSUE TITLE
Offloading rendering across servers.

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#382]
**Is your feature request related to a problem? Please describe.**
Rendering 3D maps sometimes can be overwhelming for a single server, it would be nice if such task can be offloaded across different servers.

**Describe the solution you'd like**
Add features to offload rendering process to across different servers.

**Comment by TBlueF** [comment]
It can be already .. please look into BlueMaps CLI-version. By providing remote access to minecrafts world-files or rsyncing the world onto the other server, you can use the CLI-Version to render it there.
If you need support, please visit our [Discord](https://discord.gg/zmkyJa3) :)
