### ISSUE TITLE
Player head icon is default Steve after updating plugin

### ISSUE THREAD

**Issue by pelmentor** [BlueMap-Minecraft/BlueMap#384]
Hello, I started using this plugin some time ago, it's great. But after switching to 1.19.3 and updating the plugin, all player icons has become default Steve... I see all the icons in **/bluemap/web/assets/playerheads** generated from before the update and they don't get loaded up or recognised by the plugin. 
![image](https://user-images.githubusercontent.com/96078254/212769364-bbdfff28-9491-4182-bce4-420c701f709b.png)

I'm also using a plugin to generate playerheads PNGs and put it in */bluemap/web/assets/playerheads**, could it be the problem? It works fine and generates player icons as usual, but bluemap doesn't use those icons. I tried turning it off, no change. For some reason BlueMap stopped generating icons for all users (premium too). The setting to download skins is set to true.

**Comment by TBlueF** [comment]
The location where the player-images are stored changed in the latest version.. 
Did you follow the **How to upgrade** notes in the release-notes when updating bluemap?
Especially: Did you delete your `./bluemap/web/index.html` so bluemap updates the webapp?

> I'm also using a plugin to generate playerheads PNGs and put it in /bluemap/web/assets/playerheads*

This plugin will no longer work if it didn't get updated to BlueMap's latest version.

**Comment by TBlueF** [comment]
Actually, you probably did update the webapp.. (or else player markers wouldn't be showing at all) 🤔 
As i can not reproduce this, please provide more info on how to reproduce this..
Or even better: Join our [discord](https://discord.gg/zmkyJa3) so we can troubleshoot this together, more effectively :)

**Comment by pelmentor** [comment]
Hmm.. I kinda I fixed it by turning server from offline mode to online.

![image](https://user-images.githubusercontent.com/96078254/212774218-916b33de-865e-464d-96ad-82d865d1aef5.png)

**In previous versions the behavior was like this:** BlueMap would generate icons for Offline players in *playerUUID*.png format. Though it would all be Steve icons it didn't matter as another plugin I use would replace those icons with proper ones where it's not just Steve face. 

Now it doesn't generate anything for offline players nor it's trying to display what's inside playerheads folder, it defaults to Steve when offline mode is on.  
Any way to change this behavior to how it was before?

**Comment by pelmentor** [comment]
Closed, I found where player head icons are stored now (bluemap/web/maps/world/assets/playerheads). They moved it inside maps folders.

**Comment by DanielVip3** [comment]
Where are they stored in the Forge version though? I can't find them anywhere.

**Comment by TBlueF** [comment]
@alexjabka BlueMap never had working player-skin-icons if the server was in offline-mode. Neither for offline nor "premium" players. This must have been your addon all the time, no wonder it wasn't working then ^^

@DanielVip3 
Playerhead Icons are stored separately for each map in its map-folder .. or if you use sql, then in the sql-database. This is the same place for all platforms. Usually you shouldn't need to touch those tho, the API now provides a very good way to interact with them and change the skin-provider or image-generation.

If you have more questions, use our [discord](https://discord.gg/zmkyJa3) please. This is a really bad place for support :)

**Comment by pelmentor** [comment]
Thank you, I got help on discord. That addon is outdated but still works, It generates icons for offline players and puts them where bluemap stores player head icons, I just had to change the path to new one.

![image](https://user-images.githubusercontent.com/96078254/212967027-fab71cda-35af-4721-846a-b1087ca472e5.png)

I know it's 8x8 icons when bluemap makes fancy 48x48. It's ok for now.

**Comment by TechnicJelle** [comment]
@alexjabka It sounds like you're using my add-on BlueMapOfflinePlayerMarkers, which has received a lot of updayes over the past few days, making it work better with these new BlueMap versions
Please check it out :)

**Comment by TBlueF** [comment]
*( ignore jelle, he's not had much sleep and is confusing things 😋 )*
