### ISSUE TITLE
Server not Rendering anything even radius render of 10 blocks 

### ISSUE THREAD

**Issue by lifev2** [BlueMap-Minecraft/BlueMap#39]

**Comment by lifev2** [comment]
Trying to Render the earth map seems not to work even if i load the chunk

**Comment by TBlueF** [comment]
Hey, have you checked this question in the FAQ?
https://github.com/BlueMap-Minecraft/BlueMap/wiki#q-i-have-a-black-map--a-lot-of-the-map-is-missing :)
