### ISSUE TITLE
Ability to toggle default viewing mode

### ISSUE THREAD

**Issue by evilsaloon** [BlueMap-Minecraft/BlueMap#394]
**Is your feature request related to a problem? Please describe.**
I have disabled hires rendering on my BlueMap installation, and I only want the flat projection to be visible to the end user. There is a config option that disables free view mode, but the web app still defaults to perspective view, which looks wacky without the hires data.

**Describe the solution you'd like**
A config option that allows you to set a viewing mode as a default that is selected when the user opens the web app for the first time, or at least a way to disable each of the viewing modes one at a time.

**Comment by Chicken** [comment]
You can already set the default mode by adjusting the maps `start-location` setting

**Comment by TBlueF** [comment]
yee, but that resets every time you switch a map ... i have that in mind already, and i'll put this on the todo :)

**Comment by TBlueF** [comment]
Added in v5.5
