### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by spieler0** [BlueMap-Minecraft/BlueMap#397]
Im using the bluemap spigot plugin on paper 1.19.3, plugin version 3.10. In the webserver config the options for ip dont show up at all, and when adding the "ip:" and the ip after it, it gives me this error message,
![image](https://user-images.githubusercontent.com/73181561/223542647-37bdaa52-8c10-45d6-a729-cfdd5f05c0ee.png)
![image](https://user-images.githubusercontent.com/73181561/223542698-fe08036c-5034-4c09-933e-7d5a020d27ff.png)

**Comment by TBlueF** [comment]
GitHub is not a good place for support, if you need support with configuring bluemap, please visit us on our [discord](https://discord.gg/zmkyJa3) :)
Thanks!
