### ISSUE TITLE
Auto-Make blockid.json bug

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#4]
log
`[19:49:45] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Reloading BlueMap...
[19:49:45] [Thread-31/INFO] [bluemap]: WebServer closed.
[19:49:46] [pool-3-thread-205/ERROR] [bluemap]: Failed to read ResourcePack:

>  D:\Forge Sponge Server 1.12.2\.\config\bluemap\resourcepacks\blockIds.json
> java.util.zip.ZipException: error in opening zip file
> 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_231]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
> 	at de.bluecolored.bluemap.core.resourcepack.fileaccess.ZipFileAccess.<init>(ZipFileAccess.java:43) ~[ZipFileAccess.class:?]
> 	at de.bluecolored.bluemap.core.resourcepack.fileaccess.FileAccess.of(FileAccess.java:44) ~[FileAccess.class:?]
> 	at de.bluecolored.bluemap.core.resourcepack.ResourcePack.load(ResourcePack.java:137) ~[ResourcePack.class:?]
> 	at de.bluecolored.bluemap.core.resourcepack.ResourcePack.load(ResourcePack.java:122) ~[ResourcePack.class:?]
> 	at de.bluecolored.bluemap.sponge.SpongePlugin.load(SpongePlugin.java:175) ~[SpongePlugin.class:?]
> 	at de.bluecolored.bluemap.sponge.SpongePlugin.reload(SpongePlugin.java:356) ~[SpongePlugin.class:?]
> 	at de.bluecolored.bluemap.sponge.Commands.lambda$null$2(Commands.java:118) ~[Commands.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
> 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7]
> 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.7]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> [19:49:46] [pool-3-thread-205/ERROR] [bluemap]: Failed to read ResourcePack: D:\Forge Sponge Server 1.12.2\.\config\bluemap\resourcepacks\blockProperties.json
> java.util.zip.ZipException: error in opening zip file
> 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_231]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
> 	at de.bluecolored.bluemap.core.resourcepack.fileaccess.ZipFileAccess.<init>(ZipFileAccess.java:43) ~[ZipFileAccess.class:?]
> 	at de.bluecolored.bluemap.core.resourcepack.fileaccess.FileAccess.of(FileAccess.java:44) ~[FileAccess.class:?]
> 	at de.bluecolored.bluemap.core.resourcepack.ResourcePack.load(ResourcePack.java:137) ~[ResourcePack.class:?]
> 	at de.bluecolored.bluemap.core.resourcepack.ResourcePack.load(ResourcePack.java:122) ~[ResourcePack.class:?]
> 	at de.bluecolored.bluemap.sponge.SpongePlugin.load(SpongePlugin.java:175) ~[SpongePlugin.class:?]
> 	at de.bluecolored.bluemap.sponge.SpongePlugin.reload(SpongePlugin.java:356) ~[SpongePlugin.class:?]
> 	at de.bluecolored.bluemap.sponge.Commands.lambda$null$2(Commands.java:118) ~[Commands.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
> 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7]
> 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.7]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

[19:49:47] [pool-3-thread-205/INFO] [net.minecraft.server.dedicated.DedicatedServer]: BlueMap reloaded!
[19:49:47] [Thread-60/INFO] [bluemap]: WebServer started.`

I know there might be a problem because it is automatically generated, but it doesn't seem to open file.

https://pastebin.com/LbkDxepc <- blockids.json

**Comment by TBlueF** [comment]
You put the config file directly into the resourcepack folder which is the [wrong place](https://github.com/BlueMap-Minecraft/BlueMap/wiki/Configuring-mods#installing-those-configs)
In your case, just put it here: `D:\Forge Sponge Server 1.12.2.\config\bluemap\`

**Comment by ghost** [comment]
oops, sorry
