### ISSUE TITLE
Disable `Free-flight`

### ISSUE THREAD

**Issue by thomasbnt** [BlueMap-Minecraft/BlueMap#400]
**Is your feature request related to a problem? Please describe.**
I don't want players to see undergrounds with the free-flight.

**Describe the solution you'd like**
Toggle to disable the `Free-flight` on the map.

**Comment by TBlueF** [comment]
You can already turn it off in the `webapp.conf`. 
Please use our [discord](https://discord.gg/zmkyJa3) if you need support :)
