### ISSUE TITLE
 Online map lags

### ISSUE THREAD

**Issue by Energobro** [BlueMap-Minecraft/BlueMap#401]
When scrolling, moving, even without a 3d view, the online map is still 20 fps

**Comment by TBlueF** [comment]
*"Works on my machine.."*
![image](https://user-images.githubusercontent.com/10765470/226917099-10e3a359-c8da-4537-b637-9cc2132ee277.png)

Make sure you have Hardware-Acceleration enabled on your Browser and if you use a Laptop with two GPU's then [make sure that your browser is using the HighPerformance GPU and not the PowerSaving GPU](https://helpdeskgeek.com/how-to/how-to-switch-between-dedicated-gpu-and-integrated-graphics/) :)

If you need more support on this or want to discuss it, please visit our [Discord](https://discord.gg/zmkyJa3) =)
