### ISSUE TITLE
Starting with docker will result in a black screen on the map

### ISSUE THREAD

**Issue by FDuiv** [BlueMap-Minecraft/BlueMap#402]
### What i did / Steps to reproduce

I just migrated the service from virtual server 1 to virtual server 2, but other than that the configuration is exactly the same. bluemap was perfectly fine when I ran virtual server 1. When I started in virtual server 2, the map file was no longer loading. Both servers are started with docker.

### Expected result

The bluemap web page is displayed properly
### Actual result

In bluemap's web interface, maps didn't load, except for the player's location, and subsequent investigations found that the "tiles" folder was missing
### Context
**BlueMap Version:**  
BlueMap-3.10-forge-1.18.1.jar

Add more context here!
- Linux. arclight-forge-1.18.2-1.0.9-SNAPSHOT.jar
- Has the world been generated using any minecraft-mods?
yes

Also:
Regarding logs, the plugin does not have any log files, nor does it have any log output.
![image](https://user-images.githubusercontent.com/45262140/227222046-25d45efd-e4b4-44c4-87cd-ddb0253e5b84.png)
![image](https://user-images.githubusercontent.com/45262140/227222330-9f16ed01-60bd-4ae9-992e-7beb15af2d58.png)

**Comment by TBlueF** [comment]
This is not a bug with bluemap, but an issue with your setup / migration and GitHub is the wrong place for support..
For support, please visit us on our [discord](https://discord.gg/zmkyJa3), thank you! :)
