### ISSUE TITLE
unknown black block

### ISSUE THREAD

**Issue by twseer67875** [BlueMap-Minecraft/BlueMap#404]
### What i did / Steps to reproduce
Generate maps with BlueMap-Cli and nothing more

### Expected result
The map is displayed normally

### Actual result
After zooming in on the map to a certain extent and dragging the map, there will be a black block in the center that cannot be displayed
**as shown in the video**
https://cdn.discordapp.com/attachments/465136135438598181/1091389745701068941/2023-03-31_23-47-42.mp4

### Context
**BlueMap Version:**
`BlueMap-3.12-cli`
`The maps are all original version 1.19.2 maps without any mods`

### World settings file
```
name: "分流一"
world: "/home/cocobeen/NASMount/BedrockServer/Server1/world"
sorting: 0
sky-color: "#7dabff"
ambient-light: 0.1
world-sky-light: 15
remove-caves-below-y: 55
cave-detection-ocean-floor: -5
cave-detection-uses-block-light: false
max-x: 7500
max-z: 7500
min-inhabited-time: 0
render-edges: true
save-hires-layer: false
storage: "file"
ignore-missing-light-data: false
```

**Comment by TBlueF** [comment]
You have `save-hires-layer: false` which means you will also need to turn off the hires layer from trying to load:
![image](https://user-images.githubusercontent.com/10765470/229172202-18a6e46d-7c61-4a7b-9726-38d89613cc58.png)

GitHub is the wrong place for support, if you need more help, please visit us on our [discord](https://discord.gg/zmkyJa3)
