### ISSUE TITLE
no working quark mod (Chests)

### ISSUE THREAD

**Issue by MrJorman** [BlueMap-Minecraft/BlueMap#406]
no working quark mod (Chests) 

1.19.2 Forge

**Comment by MrJorman** [comment]
It is the chests that are not displayed.

**Comment by TBlueF** [comment]
BlueMap doesn't add support for specific mods. It just tries to parse their resources and do its best to render them.
Chests are tile-entities and often don't define block-models in the usual way. Which means BlueMap won't be able to render them automatically. 
If you know how to create resourcepacks with block-models, you can add your own resourcepack that adds resources for those chests to make BlueMap render them.

If you have further questions about this, please visit us on our [discord](https://discord.gg/zmkyJa3) :)
