### ISSUE TITLE
Can you add a marker function to the map?

### ISSUE THREAD

**Issue by XinKe-Conch** [BlueMap-Minecraft/BlueMap#41]
This is a very, very good plug-in. If you can add the mark function for cmd / future fabric version, I will look forward to map update, because this will be a very good function.Thank you for bringing us such a good plugin.

**Comment by TBlueF** [comment]
There are markers in the latest version, but they are still in early development.
I added a quick [wiki page](https://github.com/BlueMap-Minecraft/BlueMap/wiki/Markers) with some information.
Better marker-management (like commands etc.) will come in future updates :)

**Comment by XinKe-Conch** [comment]
Its verrrrrry great ,  thank you
