### ISSUE TITLE
Can not check player count in the newer version

### ISSUE THREAD

**Issue by moonEEVEEXwX** [BlueMap-Minecraft/BlueMap#413]
We are using Bluemap(ver3.7) before and there is a button can check player count.
![QQ图片20230415192033](https://user-images.githubusercontent.com/78309411/232218412-1f890fa0-9b7a-48f7-898c-ee2394744123.jpg)
but when we update Bluemap to version 3.13,The button disappeared.
![QQ图片20230415192037](https://user-images.githubusercontent.com/78309411/232218438-daabd887-0448-4971-ab71-fdd3294cf30e.png)
We've tried deleted the whole webroot folder,but it wont work.

**Comment by TBlueF** [comment]
If that button is missing, then there is something wrong with your setup. 
GitHub is the wrong place for support. Please visit our [discord](https://discord.gg/zmkyJa3), there we can help you find the issue :)
