### ISSUE TITLE
On changed of compression, updated database without purge

### ISSUE THREAD

**Issue by Scot-Survivor** [BlueMap-Minecraft/BlueMap#416]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
So, currently if I were to change my compression settings for BlueMap I would have to purge my map & render again in order to apply these settings, if feasible, it would nice to be able to have this apply without a purge. 

In theory you can keep memory & space under control by updating the map tiles in the database in chunks of tiles (I.e fetch 200, tiles, compress / uncompress & then re apply) while this is happening, the map itself will likely not display correctly however this is no different than while a map is under going a render.

**Comment by TBlueF** [comment]
Out of scope -> won't implement..
There is thousands of different ways you can change storage configs, and there is no simple way to make a migration script that covers them all, also purging and rendering the map again works fine as well. So currently i don't plan on implementing such a thing, sorry ^^
