### ISSUE TITLE
You should add support or edit supported server types for Pufferfish and Purpur

### ISSUE THREAD

**Issue by ryslavy** [BlueMap-Minecraft/BlueMap#420]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Why do you want this feature

Pufferfish is fork of Paper.
https://github.com/pufferfish-gg/Pufferfish
Purpur is fork of Paper
https://github.com/PurpurMC/Purpur

**Describe the solution you'd like**

Add support or edit supported server types for These.

**Comment by Chicken** [comment]
Unless these forks of forks of forks change something they shouldn't, BlueMap should already work as-is. Listing or officially supporting the infinite number of forks of forks of forks wouldn't gain anything for BlueMap.
