### ISSUE TITLE
Changing the title does not work

### ISSUE THREAD

**Issue by Recliness** [BlueMap-Minecraft/BlueMap#423]
### What i did / Steps to reproduce

Open BlueMap/web/index.html. Change <title>BlueMap</title> to something you would like the title of the tab to be.

### Expected result

It was expected that the title of the tab would change

### Actual result

The title of the tab changed at first, but then when it actually loaded the world, it was changed to "BlueMap - \<worldname\>"

### Context
**BlueMap Version:**  
`BlueMap-3.13-Spigot`

Linux on Paper
World was generated via chunky/naturally

**Comment by sofianedjerbi** [comment]
I think you should/can change the title in language files

**Comment by TBlueF** [comment]
Correct, the title can be changed in the language files in `./bluemap/web/lang/*`.

If you need support with this, please visit us on our [discord](https://discord.gg/zmkyJa3) :)
