### ISSUE TITLE
Ctrl+Shift+Tab causes you to fall through the map

### ISSUE THREAD

**Issue by Radvylf** [BlueMap-Minecraft/BlueMap#435]
### What i did / Steps to reproduce

Use Ctrl+Shift+Tab to switch out to a different tab. When you switch back, you'll be moving downward infdefinitely unless you think to press shift.

### Expected result

Switching tabs without weird stuff happening, given that keybinds are a productivity and accessibility feature.

### Actual result

Since there was a `keydown` for shift, but the `keyup` was when I was on another tab, I kept moving down constantly until I hit shift. This is a very unintuitive solution to the problem of moving down when you're not supposed to be, so it took me many instances of this happening to realize how to stop it.

### Context
**BlueMap Version:**  
 Doesn't matter, front-end issue

Chrome 111

**Comment by TBlueF** [comment]
Closing in favor of #408 :)

**Comment by TBlueF** [comment]
> Doesn't matter, front-end issue

(fyi: the frontend change too with the bluemap versions :p)
