### ISSUE TITLE
Add config option to skip rendering specific blocks

### ISSUE THREAD

**Issue by HollishKid** [BlueMap-Minecraft/BlueMap#441]
**Is your feature request related to a problem? Please describe.**
There might be situations in which one would prefer not to render specific blocks.
In my case, pollution from the mod Pollution of the Realms, makes the map render odd in places where there is pollution. More specifically, it looks like the ground "spikes up" to the blocs of pollution, which are suspended mid-air.

**Describe the solution you'd like**
A nice and easy solution would be to add a config option that allows to "blacklist" blocks that should not be rendered.

Thanks for considering this idea and for making such an awesome mod ! :D

**Comment by Chicken** [comment]
There is a way to do this currently. It is just not simple, but not hard either. You just have to create a texturepack for BlueMap that maps the block's model to air (or empty).

**Comment by TBlueF** [comment]
You can already do that using a custom resource pack that gives those blocks an empty model :)
Just create such a resource-pack and add that to bluemap and re-render the map ^^

**Comment by TBlueF** [comment]
(i got ninjad .. lol)
