### ISSUE TITLE
Command to link

### ISSUE THREAD

**Issue by Aulberon** [BlueMap-Minecraft/BlueMap#442]
It would be nice if we could set a link of our webmap in the config and when the players use "/bluemap link" it displays a clickable link in the chat, making easier to access the map.

**Comment by TBlueF** [comment]
This is out of scope for bluemap. If you want to have custom commands with text and links, there is a [lot of other plugins/mods](https://www.google.com/search?q=custom+commands+minecraft+plugin+mod) that can do that already :)
