### ISSUE TITLE
About specifications that make it look simple like terrain when building in the air like a ceiling

### ISSUE THREAD

**Issue by FREESERVERP** [BlueMap-Minecraft/BlueMap#45]
Is the phenomenon like the one in the photo the specifications?
I would like you to improve it if you like.
![コメント 2020-05-24 083616](https://user-images.githubusercontent.com/65611276/82742484-b32f4c80-9d99-11ea-864c-0476cd510f89.png)

**Comment by TBlueF** [comment]
If i understand you correctly... this is a known issue and is already being discussed in #13 :)
