### ISSUE TITLE
Some tile/block entites not rendered

### ISSUE THREAD

**Issue by oliver408i** [BlueMap-Minecraft/BlueMap#450]
### What i did / Steps to reproduce
1. Install bluemap
2. Use /setblock ~ ~ ~ end_gateway to put an end gateway somewhere. Best if you surround it with some other block to you can better see it on the map.
3. Open the map, let it render. You cannot see the end gateway

### Expected result
I should see the end gateway like any other block

### Actual result
The end gateway is just not there. You cannot see it at all

### Context
**BlueMap Version:**  
`bukkit 3.14` (commit 16b1300ced39d7b76938599e00790d708b8e0cb1)

Purpur 1.20, overworld, no mods/plugins that would break end gateways. Just essentials and some economy stuff.

Mc view:
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/75344601/ae49a42e-c952-4ce0-8411-4685dc7d0cc1)

Bluemap view:
<img width="324" alt="image" src="https://github.com/BlueMap-Minecraft/BlueMap/assets/75344601/d9ccbe67-2ba2-4636-b09b-034f764de8fa">

**Comment by TBlueF** [comment]
Added to #145, and closing this in favor of that other issue :)
