### ISSUE TITLE
Low res layer seems to no load on firefox

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#452]
### What i did / Steps to reproduce

Open the map on firefox, (on chrome there isn't this problem)

### Expected result

See both the hires and the lowres layer

### Actual result

Being able to see only the hires layer

### Context
**BlueMap Version:**  
`3.14-spigot-1.20.1`

Client: Debian buster ARM, Firefox 102.12.0esr (64 bit),
Server: Debian buster ARM, Paper 1.20.1-32.jar

![Schermata del 2023-06-24 09-59-54](https://github.com/BlueMap-Minecraft/BlueMap/assets/37190636/76d71320-6596-476f-9d62-dcd8d60782b6)

**Comment by TBlueF** [comment]
Firefox works fine for me. 
Can you please check if there is an error in your browser-console and provide it?

**Comment by ghost** [comment]
I found something 
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Must have a compiled vertex shader attached:
SHADER_INFO_LOG:
ERROR: 0:162: 'texture' : no matching overloaded function found
ERROR: 0:162: '=' : dimension mismatch
ERROR: 0:162: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'
VERTEX

ERROR: 0:162: 'texture' : no matching overloaded function found
ERROR: 0:162: '=' : dimension mismatch
ERROR: 0:162: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'

  157: }
  158: 
  159: void main() {
  160: 	vPosition = position;
  161: 	
> 162: 	vec4 meta = texture(textureImage, posToMetaUV(position.xz));
  163: 	vPosition.y = metaToHeight(meta) + 1.0 - position.x * 0.0001 - position.z * 0.0002; //including small offset-tilt to prevent z-fighting
  164: 	
  165: 	vec4 worldPos = modelMatrix * vec4(vPosition, 1);
  166: 	vec4 viewPos = viewMatrix * worldPos;
  167: 	
  168: 	vWorldPosition = worldPos.xyz;
0:1(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
0:2(12): warning: extension `GL_EXT_gpu_shader5' unsupported in fragment shader

**Comment by TBlueF** [comment]
Make sure you have Hardware-Acceleration enabled on Firefox :)

**Comment by ghost** [comment]
It worked thanks :)
