### ISSUE TITLE
Feature request: Allow rotation in orthographic view

### ISSUE THREAD

**Issue by tomaszpieczykolan** [BlueMap-Minecraft/BlueMap#455]
Currently BlueMap supports orthographic view and calls it "flat". It is locked to only allow viewing from the top. I see no reason why it is locked. I'd love to be able to view it at an angle, so that it looks similar to Overviewer.

**Comment by TBlueF** [comment]
The reason it's locked is, that unlocking it creates a big set of issues with the cameras near/far planes, controls and map tile-loading. It doesn't work easily. Currently this is not planned to be added.

Also please read the [contributing guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/0eb12a1588c3f34fbaf29bd7c73a8a192f571f79/.github/CONTRIBUTING.md) before creating issues. This is the wrong place for feature requests, especially if they are just a couple of words long.
