### ISSUE TITLE
Feature request: add support for Chiesels&bits mod

### ISSUE THREAD

**Issue by marksista** [BlueMap-Minecraft/BlueMap#456]
Is it possible to add support for [ChiselsAndBits ](https://github.com/ChiselsAndBits/Chisels-and-Bits/)mod?

**Comment by TBlueF** [comment]
No, that's not feasible.

Please read our [contributing guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/0eb12a1588c3f34fbaf29bd7c73a8a192f571f79/.github/CONTRIBUTING.md) before creating a ticket, this is the wrong place for feature requests :)
