### ISSUE TITLE
Plans On Backporting?

### ISSUE THREAD

**Issue by XxsjrapsxX** [BlueMap-Minecraft/BlueMap#459]
Any plans for a 1.12.2 version since that is a common version due to some mods being stuck on that version as of right now. I noticed you have back to 1.14.4 so i thought i would ask

**Comment by TBlueF** [comment]
1.12.2 is pre [The Flattening](https://minecraft.fandom.com/wiki/Java_Edition_1.13/Flattening) which bluemap heavily relies on.
No plans to backport the newer versions.

The latest BlueMap version that supported minecraft 1.12.2 was [1.5.5](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v1.5.5). 
But beware: its **very** old, and no longer supported in any way.
