### ISSUE TITLE
Crash minecraft 1.16

### ISSUE THREAD

**Issue by OkilSaber** [BlueMap-Minecraft/BlueMap#461]
### What i did / Steps to reproduce

I installed the mod using cruse forge launcher on minecraft 1.16.5 and Forge v36.2.34 I tried the mod release 3.16 and 3.15

### Expected result

The game to launch and the mod to work.

### Actual result

I got this error:
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/54351241/d2877bf1-bafe-4a68-85b1-ee0b2993fa4f)
And here are the log files:
[latest.log](https://github.com/BlueMap-Minecraft/BlueMap/files/12217894/latest.log)
[crash-2023-07-31_19.57.58-fml.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/12217897/crash-2023-07-31_19.57.58-fml.txt)

### Context
**BlueMap Version:**  
minecraft 1.16.5 and Forge v36.2.34 I tried the mod release 3.16 and 3.15

Windows 11, and here is a list I also have installed:
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/54351241/c716d844-4c4b-4229-9cb9-e28d4744a7ad)
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/54351241/6b686f96-7b14-4e7d-985c-a0c39fa9fbbc)

**Comment by TechnicJelle** [comment]
BlueMap is meant to only be installed on servers, not clients, which you're attempting to do now. (It does usually work, though, but no official guarantees are given)

The problem you're experiencing here is related to the fact that BlueMap requires Java 11 or higher to run, while you're using Java 8.
So to make this work, you should update your Java version.

**Comment by OkilSaber** [comment]
I have searched how to install JRE 11 but I can't find it. I only found JDK 11 and requires ton register on oracle and that register process requests wayyy too many personal informations. Do you have a link please or something?

**Comment by TechnicJelle** [comment]
https://adoptium.net/en-GB/temurin/releases/?version=11

**Comment by TBlueF** [comment]
Current minecraft launchers come packed with its own Java version, which makes it hard to use a different java-version than intended on the client. You are using the curse-forge launcher, so you will need to see yourself if it is possible to use a custom java version with that.
