### ISSUE TITLE
Compile Failure MC 1.16.5 Forge 36.2.39

### ISSUE THREAD

**Issue by Khan8615** [BlueMap-Minecraft/BlueMap#462]
### What i did / Steps to reproduce
Installed a Linux Minecraft 1.16.5 server with the latest Forge 36.2.39 boots fine.
Stop it.
Install mod & boot.

### Expected result
To boot/compile normally so that it would generate the config files to set up etc.

### Actual result
Compile failure resulting in a complete server crash.
It complains that the Java Runtime was compiled in an incompatible version. 

[22:10:47] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to load class de.bluecolored.bluemap.forge.ForgeMod
java.lang.UnsupportedClassVersionError: de/bluecolored/bluemap/forge/ForgeMod has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### Context
Java 8
BlueMap-3.16-forge-1.16.5.jar
Forge 1.16.5 - 36.2.39
Linux

Crash Report.
[crash-2023-08-02_22.10.48-fml.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/12247264/crash-2023-08-02_22.10.48-fml.txt)

**Comment by TechnicJelle** [comment]
BlueMap requires Java 11 or higher to run, while it seems like you're using Java 8.
You should install Java 11 and try it with that.

**Comment by Khan8615** [comment]
MC 1.16.5 requires java 8 to run sooo.. How exactly? When its ran inside a docker on linux that sets the java versions based on game versions. xD

I'll have to update the docker egg to allow it..

**Comment by TechnicJelle** [comment]
BlueMap works on Minecraft versions as low as 1.13, while also still requiring Java 11 or higher. You should be able to run MC 1.16.5 with Java 11 just fine.
You might indeed need to edit your Docker setup to work with that.
