### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by aboodabugaza** [BlueMap-Minecraft/BlueMap#463]
hey guys this is a super blunt question
but I just downloaded bluemap, but I have no idea how to use it or even access the map.
YT videos do not provide any sort of showcase, only plugins.

Help would be appreciated, thx

**Comment by TechnicJelle** [comment]
BlueMap has a wiki full of setup instructions for all kinds of types of servers: https://bluemap.bluecolored.de/wiki/getting-started/Installation.html

If you would like more assistance, feel free to pop by our Discord server: https://bluecolo.red/map-discord
