### ISSUE TITLE
Player location in MySQL/MariaDB

### ISSUE THREAD

**Issue by FinlayDaG33k** [BlueMap-Minecraft/BlueMap#466]
### What i did / Steps to reproduce

Swap the storage from "file" to "sql" (MariaDB driver).

### Expected result

The `live/players.json` key in the `bluemap_map_meta` table to have the locations of my players.

### Actual result

The field being empty.
![afbeelding](https://github.com/BlueMap-Minecraft/BlueMap/assets/13424273/9ada5ceb-e16c-4049-bff3-4b1b120e8cb2)

### Context
**BlueMap Version:**
```
Version: 3.16
Commit: 0eb12a1588c3f34fbaf29bd7c73a8a192f571f79
Implementation: bukkit
Minecraft compatibility: 1.19.4 (1.19.4)
Render-threads: 1
Available processors: 4
Available memory: 3072 MiB
```

### Additional information
Markers from the `MapTowny` plugin load up just fine, it's just that players do not show up using an *external* webserver.  
Currently, I band-aid fix this by having `/maps/world/live/players.json` be proxied by the external webserver to the BlueMap internal server, however, I'd like to disable the internal webserver completely in the near-ish future.  
An update that places the player locations in the database rather than relying on the internal webserver would be desired.

**Comment by TBlueF** [comment]
In your `plugin.conf` is the `write-players-interval` set to anything or is it commented out?
If that is not set to anything (default) then this is expected behavior :)

**Comment by FinlayDaG33k** [comment]
This key did not exist for me (apparently, my config files were outdated - which also explains why it only used 1 render thread instead of 3).  

After updating my configs and setting the `write-players-interval` to `5` it now functions as intended.

Thanks!
