### ISSUE TITLE
Custom fluids not rendering in the map

### ISSUE THREAD

**Issue by 28Pollux28** [BlueMap-Minecraft/BlueMap#47]
Custom fluids from mods appears like pink squares on the map. Would be nice to have them rendered.
Problem seems to come from the "model":"forge:fluid" (see fluids.json below) which bluemap doesn't seem to find. That file is not in the model files from forge so I tried going around using the minecraft model for vanilla fluids (sand.json) and parsing the modified version with link to the different fluid textures of the mod into the model folder of the archive of the mod. Didn't work as well.

Hope you'll find a way ;)
Pollux
fluids.json : 
`{
    "forge_marker": 1,
    "variants": {
		"sand": {
            "model": "forge:fluid",
            "custom": { "fluid": "sand" }
        },
        "honey": {
            "model": "forge:fluid",
            "custom": { "fluid": "honey" }
        },
        "blood": {
            "model": "forge:fluid",
            "custom": { "fluid": "blood" }
        },
        "poison": {
            "model": "forge:fluid",
            "custom": { "fluid": "poison" }
        },
		"hot_spring_water": {
            "model": "forge:fluid",
            "custom": { "fluid": "hot_spring_water" }
		}
    }
}`
sand.json : 
`{
	"parent": "builtin/liquid",
    "textures": {
        "particle": "biomesoplenty:blocks/sand_still",
		"still": "biomesoplenty:blocks/sand_still",
		"flow": "biomesoplenty:blocks/sand_flowing"
    }
}`
[sand.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/4674351/sand.txt)
[fluids.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/4674352/fluids.txt)

**Comment by TBlueF** [comment]
This is about extending support for the old forge-resources format which is no longer supported since a while now.
Custom fluids can be added to bluemap in the current version using a custom resourcepack.
Closing this issue :)
