### ISSUE TITLE
[NOT-AN-ISSUE] Suggestion about PoI display behavior

### ISSUE THREAD

**Issue by Athar42** [BlueMap-Minecraft/BlueMap#470]
Hi there, a quick request here after the discussion on Discord :) 

The details "pop-in" message isn't always displayed on top of all markers, making them unreadable : 

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/44590042/c6beb501-44c4-4e63-a43a-e333fa38301d)

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/44590042/7bc0ea45-5e42-4914-885f-1705a24b19fc)

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/44590042/81a8ebf7-482d-43a9-b9ac-e3c6b90090f1)

And expected behavior would be that this pop-in message to be always displayed on top of ALL markers enabled on the map.

**Comment by TBlueF** [comment]
Sorry, but i not only hinted in the discord discussion that there is no need to post it as a suggestion, but there is also a [Community Guildline](https://github.com/BlueMap-Minecraft/BlueMap/blob/155f56e62a0ca5ad36e6307d2c6af0d87c8144cb/.github/CONTRIBUTING.md#suggesting-a-new-feature-or-change) for GitHub issues, that explicitly states not to create suggestion-issues.

So excuse me, but I'll close this again.
