### ISSUE TITLE
[FEATURE] Camera paths (tracking shots) - orbit

### ISSUE THREAD

**Issue by Hope-IT-Works** [BlueMap-Minecraft/BlueMap#473]
Hello and thank you for working on this fantastic project.

Is there a way to integrate some basic camera tracking shots? Like a basic [orbit](https://tvtropes.org/pmwiki/pmwiki.php/Main/OrbitalShot) view around a predefined path.

Optionally custom tracking shots would be great too!

Which renderer (or library) does BlueMap use? Maybe I could code a basic implementation.

Have a great day

@Hope-IT-Works

**Comment by TBlueF** [comment]
BlueMap uses the [ThreeJS](https://threejs.org/) library to display the 3d-map on the browser.
You can make a custom script (see `webapp.conf`) which hooks into bluemaps camera-controls and moves it however you like.
The [webapp code](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/BlueMapCommon/webapp/src/js/BlueMapApp.js) is a little grown and needs a rework, but you should be able to find something you can use :)
E.g. `bluemap.mapViewer.controlsManager.rotation = ??` changes the rotation of the current view .. etc.. :)
I know someone has done something similar before (can't find it right now).

If you have more questions / want to talk about this, please visit our [discord](https://discord.gg/zmkyJa3)! GitHub is not a good place for questions or suggestions ;)
