### ISSUE TITLE
The BlueMap does not load on the phone

### ISSUE THREAD

**Issue by XANT3R** [BlueMap-Minecraft/BlueMap#48]
The BlueMap does not load on the phone

![image](https://user-images.githubusercontent.com/5504000/82797303-28bd1a80-9e77-11ea-9f63-7e5b99b284ea.png)

There is only a black screen, even after a long time.

It works fine on the computer. The map is completely generated.

BlueMap version 0.6.1 worked well.

Phone: Motorola Moto E5
Browser on Phone: Google Chrome
Version BlueMap: 0.7.0-mc1.15

**Comment by Glucy-2** [comment]
I have the same problem

**Comment by kencinder** [comment]
Working fine here

![Screenshot_20200602-122553](https://user-images.githubusercontent.com/3614897/83538639-761b3680-a4cc-11ea-9be0-f7441ed8e0b8.png)

Moto G7 Plus

Just adding to this for the sake of figuring out where it does/doesn't work

**Comment by XANT3R** [comment]
> Working fine here
> 
> ![Screenshot_20200602-122553](https://user-images.githubusercontent.com/3614897/83538639-761b3680-a4cc-11ea-9be0-f7441ed8e0b8.png)

You don't have https and that's probably the point.

**Comment by kencinder** [comment]
No it's not that, it's hardware limitation, doesn't work on my daughter's older phone.

**Comment by XANT3R** [comment]
But in the older version, it worked everywhere :/ .

**Comment by TBlueF** [comment]
@RetnaX I can reproduce this on my (fairly old) phone, this is probably related to some changes i introduced in 0.7.0 to eliminate the marker-flickering (z-fighting)..
It uses an advanced webGL feature (logarithmic depth buffer) that does not work on all systems. It should fallback to the normal depth buffer if the logarithmic one is not supported, but apparently it's not doing that properly..
I'll try to fix that the next version.

**Comment by fnrcum** [comment]
Just as a sidenote, I have an S10+ with Chrome and it's not working so it's not just on older phones
