### ISSUE TITLE
Free-Flight option remains under settings when disabled

### ISSUE THREAD

**Issue by mloit** [BlueMap-Minecraft/BlueMap#482]
Disabling the `Free-Flight` option in the `webapp.conf` correctly removes the button on the main display, but the option remains in the menu under `View/Controls` in `Settings`.  

While selecting it seems to do nothing, it has no visual indication that it is not available either. It still highlights when hovered over, and changes state when clicked, suggesting it is an available option. The option should be removed from the list when disabled, or at the very least greyed out & made non-responsive when the mouse hovers over, or is clicked.

**Comment by TBlueF** [comment]
Will be fixed in the next version 👍
