### ISSUE TITLE
Strange browser bug?

### ISSUE THREAD

**Issue by FireFlyEx** [BlueMap-Minecraft/BlueMap#483]
So when I browse the map for the server I'm playing on a strange 'shadow' appears and blocks my view of whatever the 'camera' is pointing at. No idea why. I'm using the Brave browser.

BlueMap 3.14 on a Windows based Vanilla server
![bluemap-screenshot](https://github.com/BlueMap-Minecraft/BlueMap/assets/76809959/479defae-482c-4023-a056-fa201f3f3509)

**Comment by TBlueF** [comment]
Not a bug, see: https://bluemap.bluecolored.de/wiki/FAQ.html#q-my-map-disappears-when-i-zoom-in *("My map disappears when I zoom in!")*
If you have more questions about this, please visit us on our [discord](https://discord.gg/zmkyJa3) :)
