### ISSUE TITLE
Implement PDO version of the mysql.php script for more compatibillity

### ISSUE THREAD

**Issue by AlbusRex** [BlueMap-Minecraft/BlueMap#484]
I am attempting to deploy an Nginx server that uses the mysql.php for querying the database instead of proxying the integrated web server packed on the jar.
Since I chose Postgre as the backend database, the mysql.php does not work at all becuase it uses the mysqli connector.
I have looked for a "pgsql.php" file in this repository without success, to be sure I was not noticing something obvious.
I would like to know if there is some key documentation I have missed to use Postgre as the backend for the web application or, if it is possible, request the mysql.php to be rewritten using PDO to make it database agnostic.

**Comment by TBlueF** [comment]
I have no experience with PDO, might look further into this later. -> Not sure if it's feasible. 
But for now this will be low priority.

This would be an excellent Issue for a PR, if anyone has experience with this and want's to help :)

**Comment by AlbusRex** [comment]
I have opened PR https://github.com/BlueMap-Minecraft/BlueMap/pull/486
I squeezed the little php knowledge I have and got lucky.

**Comment by TBlueF** [comment]
Implemented with #486
