### ISSUE TITLE
Black chunks missing on the map.

### ISSUE THREAD

**Issue by G3VV** [BlueMap-Minecraft/BlueMap#487]
### What i did / Steps to reproduce

Simply let the map generate.

### Expected result

A full map.

### Actual result

Huge missing black chunks within the map, a force-update helped partially.

### Context
**BlueMap Version:**  
`3.17.0-spigot-1.20.1`
I've tried looking into why this is happening and I've tried all solutions including "LightCleaner" but nothing appears to work.
As mentioned, force-updating helped partially but the issue persists.

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/46306494/b097db9e-9fa1-4efb-bfb6-b02b4dbb56ef)
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/46306494/c28004d6-e3fe-4962-b9bb-f03e5e91fbf6)

**Comment by TBlueF** [comment]
Please move this to our [Discord](https://discord.gg/zmkyJa3) #support-forum, as this is most likely some issue on your end and not a bug in BlueMap. :)
We'll try to help you figure out why this happens there!

**Comment by G3VV** [comment]
Discovered directly after writing that my DDoS protection was blocking requests for the tile images. 👍
