### ISSUE TITLE
Caves rendering even with renderCaves settings to false

### ISSUE THREAD

**Issue by 28Pollux28** [BlueMap-Minecraft/BlueMap#49]
As the title says, my caves are still rendering even if the setting is set to false
![image](https://user-images.githubusercontent.com/40760287/82825730-072a5600-9eac-11ea-911c-bf1a0dc08d92.png)
Don't know if the pregeneration I'm using is the cause of the problem, but ignoreMissingLightData is not used, so that is not generating this issue.
Thx for your time 

version : 1.12.2 - 0.7.0 sponge

**Comment by TBlueF** [comment]
I assume your `ambientLight` is not at `1`, but the caves in the image are fully lit ..
Have you maybe used it previously and that are old tiles that still are rendered with `ignoreMissingLightData`? Either that or you actually have sunlight in these caves in your world, which would be really weird :D

**Comment by 28Pollux28** [comment]
ambientLight is set to 0 and this is a fresh render (I deleted all my previously made renders). I never used ignoreMissingLightData. here is the picture of the cave in bluemap : 
![image](https://user-images.githubusercontent.com/40760287/82827316-13fc7900-9eaf-11ea-8799-3a726ba93cc9.png)
and the very same cave in the world : 
![image](https://user-images.githubusercontent.com/40760287/82827361-2bd3fd00-9eaf-11ea-82ab-ec108805b919.png)
Though i set the gamerule DoDaylightCycle to true, don't know if that could be creating the problem.
It is really weird as every cave is completely lit on the map.

**Comment by TBlueF** [comment]
Can you send me a region file of your map .. preferably from that location?
I want to rule out that the light data in the world files it the problem here ^^

**Comment by 28Pollux28** [comment]
Here you go :)
the coordinates of the cave are 340 53 99
[r.0.0.zip](https://github.com/BlueMap-Minecraft/BlueMap/files/4678008/r.0.0.zip)

**Comment by TBlueF** [comment]
Soo, something is weird.. 
The light data is fine, and i rendered your region-file with 0.7.0-cli (the exact same render-logic like in the sponge version), and the caves are not being generated, and appear to be lighted correctly:
![Anmerkung 2020-05-25 181244](https://user-images.githubusercontent.com/10765470/82829342-57f17d00-9eb3-11ea-934e-b20417eea4a1.png)

**Comment by 28Pollux28** [comment]
that's weird... I'm gonna delete my previous render and render it again, to see if the issue could be resolved that way.
Ok that seems to solve the problem... Don't know why that happened...
