### ISSUE TITLE
Issue with hiding worlds

### ISSUE THREAD

**Issue by DrogazDev** [BlueMap-Minecraft/BlueMap#491]
Hey, im new to using BlueMap and i was wondering (because its nowhere to be found on the wiki) how to hide certain worlds from map. I have one main world that i want to display but other worlds like our build world etc doesn't have to be seen for the public. Is there a way to do this?

Kind Regards, Drogaz

**Comment by TechnicJelle** [comment]
There's a section on our wiki explaining this: https://bluemap.bluecolored.de/wiki/getting-started/Configuration.html#configuring-your-maps-adding--removing-maps
 :)

**Comment by TBlueF** [comment]
If there are any more questions, please use our [discord](https://discord.gg/zmkyJa3) :)
