### ISSUE TITLE
1.20.1 forge 47.2.6

### ISSUE THREAD

**Issue by Thunderrock424242** [BlueMap-Minecraft/BlueMap#493]
### What i did / Steps to reproduce
 download my modpack and it will crash

### Expected result

for it to not crash
### Actual result

it crashed
### Context
**BlueMap Version:**  
`1.0.0-fabric-1.16.1`
idk about the target but the bluemap version is 3.18

[latest.log](https://github.com/BlueMap-Minecraft/BlueMap/files/13465222/latest.log)
[debug.log](https://github.com/BlueMap-Minecraft/BlueMap/files/13465223/debug.log)

i have 2 logs

**Comment by TBlueF** [comment]
The logs you attached don't have any errors or signs of a crash ... and the bluemap version used is `BlueMap-3.18-forge-1.20.jar`
You didn't even include your modpack or any info at all.
Closing until you provide more info.
If you need support, use our [discord](https://discord.gg/zmkyJa3).
