### ISSUE TITLE
The world generated by my server via TerraformGenerator looks different for the client and BlueMap

### ISSUE THREAD

**Issue by uprial** [BlueMap-Minecraft/BlueMap#499]
Hi dear BlueMap creators.

I use TerraformGenerator v13.0.3 (https://www.spigotmc.org/resources/terraformgenerator-1-18-2-1-20-4.75132/)
and BlueMap v3.20 (https://www.spigotmc.org/resources/bluemap.83557/)
on Paper v1.20.4-379 (https://papermc.io/downloads/paper)
and seed -3420545464665791887.

I don't use any client mods.

The world generated by my server looks different for the client and BlueMap.

Specifically, the tree leaves in the client are red, but in the BlueMap, they are green. The dirt colors are different, too.

Please check the screenshots attached.
Client:
![Screenshot 2024-01-10 at 08 47 41](https://github.com/BlueMap-Minecraft/BlueMap/assets/4799195/fb0416d3-95c3-401f-9834-4126838cc145)
BlueMap:
![bluemap-screenshot (1)](https://github.com/BlueMap-Minecraft/BlueMap/assets/4799195/b682fcb0-be8c-4168-9206-4119e5ce2e3f)

**Comment by TBlueF** [comment]
TerraformGenerator is *(i think)* generating and sending custom biome-info on runtime to the clients without ever saving it, which makes it impossible for bluemap to load that info from the world-files. 

To fix this you'll need to somehow get a datapack with those custom biomes and add that to bluemaps `resourcepacks` folder.
Maybe ask the people at TerraformGenerator if there is a way to export a datapack from them?

Or alternatively manually configure the biomes like explained here: https://bluemap.bluecolored.de/wiki/customization/Mods.html#biomes-config

If you need more support, please visit our [discord](https://discord.gg/zmkyJa3) :)
