### ISSUE TITLE
Can't load mod block (automake)

### ISSUE THREAD

**Issue by ghost** [BlueMap-Minecraft/BlueMap#5]
![1213231432](https://user-images.githubusercontent.com/24382481/72340479-a162dc00-370b-11ea-9980-f20ccb59e840.PNG)
![Minecraft 1 12 2 2020-01-14 오후 8_21_11](https://user-images.githubusercontent.com/24382481/72340503-aaec4400-370b-11ea-91dd-b4455a9cea32.png)

Check file, not wrong place. but, problem all mod block.
I know there might be a problem because it is automatically generated. 
But can it happen in every block?
https://pastebin.com/LbkDxepc <- blockids.json

**Comment by TBlueF** [comment]
The config file generated in the `missing-configs` is not an "auto-generated" config but rather a log, showing you what blocks bluemap could not detect properly.
BlueMap currently **can not auto-generate** support for your mods!
Sorry ^^

**Comment by ghost** [comment]
oh... my mistake
