### ISSUE TITLE
Markers don't appear in the correct place when viewed from a mobile browser iframe

### ISSUE THREAD

**Issue by PanicRide** [BlueMap-Minecraft/BlueMap#503]
### What i did / Steps to reproduce

When viewing the map on our website, it appears in an iframe that takes up the entire window except for a header at the top. This works just fine from a desktop browser. However, on a mobile browser, the markers don't appear in the correct position, as if the map is calculating their position based on the entire browser window and not just the iframe it's in. This becomes much more obvious when zooming out as much as possible. When switching to the full screen view, the markers appear as expected.

### Expected result

The markers should appear in the correct position on the map regardless of whether the map is being displayed in an iframe or not

### Actual result

The markers are not in the correct position when view in an iframe in a mobile browser window

### Context
**BlueMap Version:**  
`BlueMap-3.20-paper`

This was tested on a Google Pixel 7 Pro using Google Chrome version `121.0.6167.101`

[Screen Capture Video Demonstration](https://panicride.s3.us-west-2.amazonaws.com/screen-20240129-134517.mp4)

For more information, or to get access to our map, you can message me here or on discord as: `panicride`

![Screenshot_20240129-141209](https://github.com/BlueMap-Minecraft/BlueMap/assets/99451581/c3e0aa90-b5d1-4a26-916f-eefd38744a1d)

**Comment by TBlueF** [comment]
I can reproduce this, but i wasn't able to find the exact cause. 
It does not happen on Firefox and Edge on the same mobile-device, so i think this is a bug with the mobile-chrome app.
There might be a workaround somewhere, but priority for this is too low for me for the time i would need to invest, so i will close this issue for now.
