### ISSUE TITLE
Error with reverse proxy nginx server

### ISSUE THREAD

**Issue by art3m4ik3** [BlueMap-Minecraft/BlueMap#505]
### What i did / Steps to reproduce

I tried to set up a reverse proxy nginx server

### Expected result

Normal operation of reverse proxy nginx server

### Actual result

The page just has a white screen, nothing more. You can see the name "BlueMap" in the page header

### Context
**BlueMap Version:**  
Version: 3.20
Commit: a0b47f1bd5ed2f3750a5a0a1bcf270c46db275cf
Implementation: bukkit (using paper)
Minecraft compatibility: 1.20.1 (1.20.0)

OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-92-generic x86_64)
Platform: git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
No mods

Configuration of reverse proxy nginx server(I hid the server's IP address)
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/114188034/02d3ed69-61d1-46e0-a8d7-082a471c1c23)

Result of reverse proxy (white screen)
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/114188034/323a0eee-dd78-4486-be4b-524d0566af96)

**Comment by TBlueF** [comment]
This is an issue in your reverse-proxy setup somewhere, not a BlueMap bug.
GitHub is not a good place for support, if you need support please use our [support discord](https://discord.gg/zmkyJa3).
