### ISSUE TITLE
Running Bluemap on localhost

### ISSUE THREAD

**Issue by rnds-dev** [BlueMap-Minecraft/BlueMap#507]
### What i did / Steps to reproduce
I rendered my local world and moved the web folder to the local server `OpenServer`. The rendering went without errors, everything is ok in the logs. Start web using `OpenServer`

### Actual result
Render is not displayed correctly.

1. Left menu working with errors:
  - human-readable names are not displayed
  - settings not load

![изображение](https://github.com/BlueMap-Minecraft/BlueMap/assets/110224805/29aa81ea-e6cf-4abc-9ef9-5e06edfdb6c2)

2. A black area appears when the map approaches
![изображение](https://github.com/BlueMap-Minecraft/BlueMap/assets/110224805/c9a9ac99-1bfd-4757-8c39-c206debffbdc)

3. Blocks are not rendering (only polygons are shown)
![изображение](https://github.com/BlueMap-Minecraft/BlueMap/assets/110224805/9feb2222-704d-4ceb-ad57-51114e98ae24)

All errors are displayed in the developer console
![изображение](https://github.com/BlueMap-Minecraft/BlueMap/assets/110224805/72c1ad20-623d-4ea4-8195-a1921092c62f)

### Context
**BlueMap Version:**
`3.20-cli-1.20.1`

**Minecraft client version:**
`1.20.3`

**OS**
`Windows`

**Browser**
Tried `Chrome` and `Firefox`

**OpenServer version**
`5.4.3`

**Comment by rnds-dev** [comment]
With built-in webserver from CLI all ok.

**Comment by TBlueF** [comment]
Please read [this](https://bluemap.bluecolored.de/wiki/webserver/) to see how to configure your external webserver correctly for bluemap.

If you need support with that, please use our [discord](https://discord.gg/zmkyJa3), as GitHub is not the correct place for support :)
