### ISSUE TITLE
Feature Request: Allow players to set their own hidden/visible settings on the map

### ISSUE THREAD

**Issue by mcbianxiao** [BlueMap-Minecraft/BlueMap#508]
English translation uses Microsoft Translator

Feature Request: Allow players to set their own hidden/visible settings on the map
-
Hello, I'm a player from China. I'm using BlueMap as the server's map on my server, and my server-side core is using Paper. I've read the contributing guidelines, but I'm sorry I can't use Discord to give you suggestions.
Due to the needs of players on my server, I also hope that in future versions, BlueMap can support players to set whether or not to display it in the map. For example, use the command /bluemap hide to hide yourself on the map, and use /bluemap show to show yourself on the map.
I would appreciate it if this new feature request could be agreed to :)

新功能请求：允许玩家自行设置在地图上的隐藏/显示
-
你好，我是一名来自中国的玩家。我正在我的服务器上使用BlueMap作为服务器的地图，我的服务端核心使用的是Paper。我已经阅读了contributing guidelines，但很抱歉我无法使用Discord给你们提供建议。
由于我服务器上的玩家需要，所以我也希望BlueMap在未来的版本中，可以支持玩家自行设置是否在地图中显示。例如使用指令/bluemap hide以在地图上隐藏自己，使用/bluemap show在地图上显示自己。
如果这个新功能请求可以被同意，我将会不胜感激:)

**Comment by TBlueF** [comment]
There are a couple of [Addons](https://bluemap.bluecolored.de/3rdPartySupport.html) which can do this already.
For example: https://github.com/TechnicJelle/BlueMapPlayerControl :)

**Comment by mcbianxiao** [comment]
ok, thank you very much

**Comment by mcbianxiao** [comment]
ok, thank you very much :)
