### ISSUE TITLE
Screenshots made from the web UI render upside down

### ISSUE THREAD

**Issue by CCF100** [BlueMap-Minecraft/BlueMap#509]
### What i did / Steps to reproduce

1. Visit bluemap URL
2. take screenshot in free-flight/spectator mode using hamburger menu option
3. Recieve upside-down screenshot
### Context
**BlueMap Version:**  
Version: 3.20-21
Commit: 2dd7a0a9c2091d3ded5a2753ac46ec0b1bf85631
Implementation: forge-1.20
Minecraft compatibility: 1.20.1 (1.20.0)
Render-threads: 1
Available processors: 4
Available memory: 8192 MiB

**Comment by CCF100** [comment]
![bluemap-screenshot3](https://github.com/BlueMap-Minecraft/BlueMap/assets/29297989/c5ec8d27-12f3-4402-912d-8f158526a9da)

It wouldn't render the screenshot in the original message for some reason...

**Comment by TBlueF** [comment]
I can't reproduce this issue, my screenshots are facing the right way. 
Which browser are you using? Is your webapp up-to-date?
