### ISSUE TITLE
Question: How to get rid of the black/pink-checkered blocks on my map?

### ISSUE THREAD

**Issue by alex4200** [BlueMap-Minecraft/BlueMap#518]
I am using BlueMap 3.20 with minecraft 1.20.4 and when rendering a map I see a lot of black/pink-checkered blocks on my map. I see that the FAQ leads points to that page: https://bluemap.bluecolored.de/wiki/customization/Mods.html 
but I am running minecraft without mods!

So how to get rid of these black/pink-checkered blocks on the rendered map?

**Comment by TBlueF** [comment]
Since you already labeled this as a "Question": Please use our [discord](https://discord.gg/zmkyJa3) for support-questions like this! :)
GitHub is not the correct place for support.
Thank you!
