### ISSUE TITLE
Entire screen flickering

### ISSUE THREAD

**Issue by localzuk** [BlueMap-Minecraft/BlueMap#522]
### What i did / Steps to reproduce
Installed BlueMap-4.1-forge-1.20.jar into the mods folder for our AMT9 modpack server.

### Expected result
Bluemap would render and load correctly in the browser.

### Actual result
The map rendered as expected, but when you visit it in the web browser, the entire map flickers constantly. I've confirmed this with other players on the server, they see the same thing in a variety of web browsers.

### Context
**BlueMap Version:** BlueMap-4.1-forge-1.20.jar

- Server is running the Forge based modpack ATM9, on Windows Server 2022, latest version 0.2.51.
- High spec server with CPU running maximum 6% utilisation (Ryzen 3800 X, 64GB RAM, 20GB assigned to the Minecraft server, 512GB NVME SSDs in RAID 1), 1Gbit internet connection.
- The world was pre-generated with Chunk-Pregenerator mod by Speiger

Video of the effect can be seen [here](https://drive.google.com/file/d/11mFHbTIsFbX9SLEg5dXm3-mhvmM2l0nz/view?usp=sharing)

The web server is currently disabled on the gaming sever as the flickering is so high frequency at times, there is a worry it could trigger a seizure. Access to the live map can be made available on request.

**Comment by TechnicJelle** [comment]
Just reuploading the video to GitHub itself, so it won't be lost if it's ever deleted from the Google Drive: 
https://github.com/BlueMap-Minecraft/BlueMap/assets/22576047/e950b929-1df8-4652-b573-4c75a489a4c8

**Comment by TechnicJelle** [comment]
This is an extremely strange issue!

Could you please list the browsers with any installed extensions of the people who are having this issue? (Including the versions, please)
And could you also include the operating systems? (Including the version/build number of it)
That way, we can try to reproduce it.

And does this happen with BlueMap 3.20 (the latest stable version at the moment)?

**Comment by localzuk** [comment]
Windows 11 23H2 (22631.3155) - Opera GX 107.0.5045.60, Microsoft Edge 122.0.2365.80, Vivaldi 6.6.3271.48. Happens with all extensions disabled.
Windows 11 23H2 (22361.3235) - Microsoft Edge 122.0.2365.80
Windows 10 22H2 (19045.4046), Microsoft Edge 122.0.2365.80
Android 14 (Samsung Galaxy S24 Ultra) - Opera GX 2.3.9, Samsung Internet 24.0.1.2, Firefox 123.1.0

I am trying swapping out for 3.20 now. Will report back once the server is back online.

**Comment by localzuk** [comment]
OK, so I've switched up to 3.20, renaming the old bluemap folders to .old and while the overworld isn't rendered (and won't be for quite a few hours I'd guess), it isn't flickering on the bit that is rendered. So, it seems the issue is in the snapshot.

**Comment by pfruh** [comment]
Same issue here, seems to be caused by the new animated textures feature of the latest snapshot.
The browser console is getting spammed with:

```
index-9d2e9578.js:3227  Uncaught TypeError: Cannot read properties of undefined (reading 'index')
    at TextureAnimation.step (index-9d2e9578.js:3227:17362)
    at index-9d2e9578.js:4164:9504
    at Array.forEach (<anonymous>)
    at MapViewer.render (index-9d2e9578.js:4164:9491)
    at index-9d2e9578.js:4164:5395
step @ index-9d2e9578.js:3227
(anonymous) @ index-9d2e9578.js:4164
render @ index-9d2e9578.js:4164
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
requestAnimationFrame (async)
(anonymous) @ index-9d2e9578.js:4164
```

**Comment by pyshcoder** [comment]
Same issue with 4.1, same errors in browser console.

**Comment by TBlueF** [comment]
The console-log helps, i think i know whats happening roughly..

**Comment by TBlueF** [comment]
Should be fixed with 6e8247a
If someone with this issue can verify that [this build](https://github.com/BlueMap-Minecraft/BlueMap/actions/runs/8375952255) fixes it, that would be great 👍

**Comment by pfruh** [comment]
Thanks, it's working perfectly now!

**Comment by TBlueF** [comment]
Awesome, closing :)
Fix will be included in the next release.

**Comment by Pleune** [comment]
Hello, I am seeing this exact same flickering, but I believe for another reason. Here is what my browser console looks like:

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/9004509/b45b9a79-41c5-438a-ac86-8080406b1a62)

Feel free to open the page up here: https://mc1map.pleunetowne.com/

It still seems to be related to animation

**Comment by TBlueF** [comment]
Your webapp is still on version 4.1 .. make sure you also update your webapp to the latest commit to fix the flickering:
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/10765470/9d8b662e-108c-45db-9beb-73ee7b3d0485)
