### ISSUE TITLE
Diagonal Fences/Walls/Windows and Eidolon Incompatibilities

### ISSUE THREAD

**Issue by autumnly24** [BlueMap-Minecraft/BlueMap#526]
### What i did / Steps to reproduce
Use Bluemap with Eidolon: Repraised and the Diagonal Blocks Series on Forge 47.2.20 (1.20.1)

### Expected result
I expected it to function

### Actual result
Many missing block textures for all fences, walls, panes, and all blocks from Eidolon.

### Version
**BlueMap Version:3.20-forge-1.20

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/83057109/69030283-466c-4a0f-8898-844d3ff31e6f)

**Comment by TBlueF** [comment]
From our discord-bot:
> BlueMap is automatically looking for mods and datapacks in your server-files. If it finds them it will try to load them and parse its resources to be able to render any additional blocks.
>
> BlueMap might not be able to parse all blocks and resources for a mod. For example, if a mod generates its resources/block-models at runtime, BlueMap won’t be able to find them in the mod.jar and will not be able to render them correctly! You might still be able to fix this by creating a resource pack for the models.
>
> Read more at https://bluemap.bluecolored.de/wiki/customization/Mods.html

You or the mods author can create a ResourcePack with alternative bluemap-compatible block-model-resources which bluemap then can load and display.

Adding support for specific mods into BlueMap directly is deemed "Out of scope" for this project and would not be feasible anyways for the vast amount of mods that exist.
