### ISSUE TITLE
Changes to the web files don't work

### ISSUE THREAD

**Issue by gyc123456-1** [BlueMap-Minecraft/BlueMap#529]
### What i did / Steps to reproduce
1. Changed/bluemap/web/index.html
2. Changed /bluemap/web/lang/settings.conf
3. Changed /bluemap/web/lang/zh_CN.conf

### Expected result
Works like what I changed

### Actual result
No difference from default value

### Context
BlueMap Version: BlueMap-4.1-paper
OS: Linux
Server Version: Paper 1.20.1

![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/69791212/0a23765e-060a-41fa-8c32-66832e5dd6a0)
![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/69791212/31cd0d80-4f34-4702-866e-5ae44cd76400)

Logs:
[webserver.log](https://github.com/BlueMap-Minecraft/BlueMap/files/14871868/webserver.log)
[debug.log](https://github.com/BlueMap-Minecraft/BlueMap/files/14871870/debug.log)

**Comment by TBlueF** [comment]
This is not a bluemap-bug, it's most likely your browser caching the old settings. 
Make sure you clear your browser-cache after you made any changes! :)
`F12` -> `Network` -> `[x] disable Cache` -> `F5`

GitHub is not a good place for support, if you need support please visit us on our [discord](https://discord.gg/zmkyJa3) :)
