### ISSUE TITLE
Framed blocks not showing up correctly on bluemap

### ISSUE THREAD

**Issue by Swoofterkitty** [BlueMap-Minecraft/BlueMap#532]
### What i did / Steps to reproduce

I placed framed blocks in the world, and then put a skin on them. Then I updated the Bluemap, and all framed blocks show up as full, unskined framed blocks.

### Expected result

I expected framed blocks to be rendered with their skin/facade on them

### Actual result

Framed blocks rendered as full unskined blocks

### Context
**BlueMap Version:**  

3.20-forge-1.20

<!-- 
Add more context here!

This is a custom forge modpack on 1.20.1

The world was generated with Terralith

Minecraft
![2024-04-13_18 43 33](https://github.com/BlueMap-Minecraft/BlueMap/assets/105351053/9d86eb6e-71fd-4c96-b1a1-67b5112de85b)

BlueMap
![framed blocks](https://github.com/BlueMap-Minecraft/BlueMap/assets/105351053/526dc3f4-c2b3-4aee-92a5-8d3be802838a)

Ask me if you need any more information, and have a good day!

**Comment by TBlueF** [comment]
BlueMap is automatically looking for mods and datapacks in your server-files. If it finds them it will try to load them and parse its resources to be able to render any additional blocks.

BlueMap might not be able to parse all blocks and resources for a mod. For example, if a mod generates its resources/block-models at runtime, BlueMap won’t be able to find them in the mod.jar and will not be able to render them correctly.

So: Automatically detecting and rendering such blocks is not feasible and I won't start manually adding support for specific mods.
It **might** be possible in the future to create addons that add support for specific mods like this,.. but that's future
