### ISSUE TITLE
Rails from the Create mod & addon that are not straight and flat don't show up on BlueMap

### ISSUE THREAD

**Issue by Chris6ix** [BlueMap-Minecraft/BlueMap#539]
### What i did / Steps to reproduce
1.Use Create and BlueMap
2.Place Rails, including curves and rails going up/down
3.Update the map using `/bluemap update`
4.Compare the ingame view with the map.

### Expected result
Every rail no matter how it's placed should show up

I have reported this to the [Create mod](https://www.curseforge.com/minecraft/mc-mods/create), but somebody said that this is a BlueMap issue and that i should report it here.
The mentioned issue in case it helps: https://github.com/Creators-of-Create/Create/issues/6472

### Actual result
Only straight and flat rails show up
This also happens with the rails from one of their addons "[Create: Steam & Rails](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)"

### Context
- BlueMap Version: `3.20-forge-1.20`
- OS: `Win 11`
- Platform: `Forge 1.20.1-47.2.21`
- Create Mod version: `1.20.1-0.5.1.f`
- Create: Steam & Rails version: `1.6.1+forge-mc1.20.1`

In Game:
![2024-05-10_15 23 24](https://github.com/Creators-of-Create/Create/assets/65610536/659685f7-14db-43a2-871c-64cf5d6d6336)
On BlueMap:
![image](https://github.com/Creators-of-Create/Create/assets/65610536/caf5de94-e45c-4eaf-94eb-a21cdef77e6d)

**Comment by TBlueF** [comment]
BlueMap is able to load block-models and textures from mod.jar's if they are provide by the mod in standard resourcepack-format.
Create does this with their normal rails and some others of their blocks where it is possible, but curved rails are unfortunately not a simple block-model and need to be generated through code on runtime. BlueMap can't load this and will never natively support these kinds of blocks.
There might be a way in the future for addons to hook into bluemap and individually add support for certain blocks/mods, but right now it's not possible :)

Closing as "out of scope".

**Comment by Chris6ix** [comment]
That's very unfortunate :/
What do you call "in the future"?

**Comment by TBlueF** [comment]
It is planned, no ETA's or promises ^^
