### ISSUE TITLE
Map has black holes when zooming in and shows no details (blocky map)

### ISSUE THREAD

**Issue by Domi1993** [BlueMap-Minecraft/BlueMap#543]
### What i did / Steps to reproduce
It works normally but then it breaks, i dont know why (we dont used the server for a time).

I tried:

1. purge all maps
2. Deleted the bluemap folder in Plugins
3. Installed the 3.21

### Expected result
The map should be normal again

### Actual result
The holes are still there (only when zooming in)

### Context
**BlueMap Version:**  
`3.21-spigot-1.19.4`
Spigot 1.19.4 server with some plugins (no mods that add new blocks)

Map-Link:
http://185.239.237.104:2738/#ueberlebinsle:-36:0:498:1500:0:0:0:0:perspective

**Comment by TechnicJelle** [comment]
You're saying your BlueMap jar version is 3.21?
When I visit your map's website, and go into the menu and click on Info, I see that it's on version 4.1-19.

You probably downgraded from BlueMap 4 to BlueMap 3 without doing a full fresh install.
To do a fresh install, make sure to not only delete the BlueMap folder in the plugins directory, but also the BlueMap folder in the root of your server. The one with the "web" folder and a Minecraft resources jar in it.

**Comment by Domi1993** [comment]
I just downloaded the latest bluemap from github, and installed it.
I dont know why on github it is 3.21 but on the webserver it is 4.1-19.
The bluemap that is running is the 3.21 (from github)

**Comment by TechnicJelle** [comment]
Try that fresh install like I suggested. It will very likely solve the issue.

**Comment by Domi1993** [comment]
Ok i try it thank you

**Comment by Domi1993** [comment]
I found the problem because I originally installed bluemap via the plugin manager from zap-hosting. I thought it was time for an update and then installed the older version (via github). I have now deleted everything and reinstalled it via zap-hosting. It seems to be working now, the maps are being created.

Then why does it have a different version when I download it from Zap-hosting?

**Comment by TBlueF** [comment]
> Then why does it have a different version when I download it from Zap-hosting?  

That's a question you'll have to ask zap-hosting ^^

If you need more support, please use our [discord](https://discord.gg/zmkyJa3) :)

Closing
