### ISSUE TITLE
[Feature Request] Not to render Netherrack and Bedrock above Y = 90 in nether

### ISSUE THREAD

**Issue by Sciroccogti** [BlueMap-Minecraft/BlueMap#55]
Currently we can only set the BlueMap not to render blocks above 90, for example. However, many servers have buildings above that height, or even above the bedrocks. So is it possible to have a feature which can make the *Netherrack* and *Bedrock* not rendered above a height, while keeping other blocks in sight?

Thanks a lot!

**Comment by TBlueF** [comment]
I have some questions here:
What if people are building with netherrack above the nether?
Whats with the various blocks that are not netherrack and bedrock? There will be floating lava / lava-pockets, quarz-ore, gold-ore, floating mushrooms on top of the nether, everything built will be floating.. This will be a mess that is really hard to look at i think.

I'd suggest to have 2 maps for your nether. One cut at about 90 to show the lower nether.. and one that is only rendering the upper bedrock layer and all that is above. And that is already possible :)

What do you think @Sciroccogti ?

**Comment by Sciroccogti** [comment]
Yeah it's quite a good idea to have 2 maps, I will try it. But it's still quite inconvenient, cause things cannot be viewed in one map, which might cut some buildings in half. 

You are definitely right on the viewpoint that the floating lava, quarz-ore or other else will be floating, but I guess the number of these blocks is quite small, and won't be a big problem.

Whatever, I'm just trying to discuss the probability of this feature. Maybe we can come up with better ideas.

Thanks for your suggestion and the awesome maps!

**Comment by TBlueF** [comment]
Closing this for now, because the use-case of this enhancement is too slim. There will be more configuration-options in future versions that might serve as a good alternative to this.
