### ISSUE TITLE
High Res Layer not showing anymore...

### ISSUE THREAD

**Issue by RosivDamotil** [BlueMap-Minecraft/BlueMap#556]
### What i did / Steps to reproduce
Zoom in to any given point on the map

### Expected result
High Res layer should appear

### Actual result
black "box" or layer appears

### Context
**BlueMap Version:** BlueMap-5.2-fabric-1.20

See screenshot:

![bluemap_bug](https://github.com/BlueMap-Minecraft/BlueMap/assets/131135083/d682e381-8e6d-4951-9ea7-0949ccd01834)

**Comment by TBlueF** [comment]
This is not a bug, but an issue with your setup.
Make sure you followed the [update-instructions](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v5.2) on the release when updating from an older version to 5.2.
Please use our [Discord](https://discord.gg/zmkyJa3) for support with this :)

**Comment by TheCrimsonLady** [comment]
For anyone else encountering this, I also had to delete the website data on the devices. Only after that, did the map work properly.
