### ISSUE TITLE
Possible incompatibility/bug with Cesium (Blank map)

### ISSUE THREAD

**Issue by masuteri** [BlueMap-Minecraft/BlueMap#557]
### What i did / Steps to reproduce

Install [Cesium](https://modrinth.com/mod/cesium)
Convert a pre-existing world or generate a world with cesium installed.
### Expected result

Map should be rendering
### Actual result

Blank map
### Context
**BlueMap Version:**  
`5.2-fabric-1.20.5`

OS: Debian 12
Server: Fabric

Cesium converts the world into a database from anvil (the .mca files). so I suspect that BlueMap does not support the format. I don't know how BlueMap works, but if it generates the map from the world files, that might very well be the reason. Note that Cesium, by default, doesn't delete the old files, which I have manually done.
BlueMap returns no errors but immediately returns `Render-Threads are idle!` when running `/bluemap` after doing `/bluemap update`

**Comment by TBlueF** [comment]
BlueMap indeed reads the world-files directly, right now adding support for Cesium worlds is not planned..
This is the first time i hear about this mod, so the demand seems to be rather small. If it increases and more people ask about it, i will consider doing something to add support :)

With BlueMap 5.2 it should be possible for any developer to create a bluemap addon that adds support for this region-type. I am willing to assist anyone trying this with advice and if necessary implement changes to make such an addon possible!

For bluemap directly however i will close this issue as not planned for now.
