### ISSUE TITLE
Marker lag

### ISSUE THREAD

**Issue by Mixarar** [BlueMap-Minecraft/BlueMap#558]
Essentially if the map has 8000+ markers, even if they are not shown, everything starts to lag. Not a bug, but rather a question/suggestion.

**Comment by TBlueF** [comment]
BlueMap's marker system is not made for huge numbers of markers.
I might be able to improve this in the future, but right now that's just not supported ^^

Closing this issue again, as questions and suggestions are meant to go into our discord :)
