### ISSUE TITLE
Add abillity for addons to create custom block-renderers in some way

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#561]
Goal: 
Make it possible for addons to add support for special blocks form mods, e.g. copycat blocks or custom tile-entities

**Comment by TBlueF** [comment]
Added in v5.5

**Comment by dawgermany** [comment]
Is there some doc already? nice feature - hope it will not only be able to support chisel but also Minecolonies(or rather the dependency structurize)

**Comment by TBlueF** [comment]
@dawgermany I haven't made any documentation for it yet, i was hoping to create an example addon but didn't get around to do it yet.

Basically when making an addon you can now depend on [bluemap-core](https://repo.bluecolored.de/#/releases/de/bluecolored/bluemap-core/5.5) and register an new [BlockRendererType](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/core/src/main/java/de/bluecolored/bluemap/core/map/hires/blockmodel/BlockRendererType.java) and then point the block-model of your custom block to your custom renderer the same way bluemap does it e.g. for [water](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/core/src/main/resourceExtensions/assets/minecraft/models/block/water.json#L2)
Or alternatively implement the [isFallbackFor](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/core/src/main/java/de/bluecolored/bluemap/core/map/hires/blockmodel/BlockRendererType.java#L63) method to use your custom renderer dynamically for certain blockstates..

The custom renderer itself is very low-level (you have control over every single vertex), but you can always copy, extend, use or delegate to the [default block-renderer](https://github.com/BlueMap-Minecraft/BlueMap/blob/master/core/src/main/java/de/bluecolored/bluemap/core/map/hires/blockmodel/ResourceModelRenderer.java).

If someone wants to try this and has some questions i am always available on our [discord](https://discord.gg/zmkyJa3) for questions and will try to explain anything that comes up around this :)
