### ISSUE TITLE
Few chunks are out of place

### ISSUE THREAD

**Issue by LuizLoyola** [BlueMap-Minecraft/BlueMap#562]
### What i did / Steps to reproduce
- Added BlueMap to a running SMP, checked out the site.

### Expected result
- The chunks to render properly.

### Actual result
- Some chunks are in the wrong place, other map mods such as Pl3xMap show them correctly.

### Context
**BlueMap Version:**
Output of `/bluemap version`

    Version: 5.2
    Commit: 21738feb69f904df5f5cf61c907c7eda67911e0c
    Implementation: fabric
    Minecraft: 1.21
    Render-threads: 2
    Available processors: 4
    Available memory: 8192 MiB

- Server running on a Minecraft Server Host, looks like docker?
- The world was generated using Chunky, but those chunks are very close to the spawn, so that shouldn't be the issue.

Screenshots:
- Top-down
  ![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/20233048/f3bec618-2e1c-442b-a6f0-235c768a65d7)
- 3D
  ![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/20233048/00346036-dd80-44f0-8e8d-392c547dd1c9)
- In-game
  ![image](https://github.com/BlueMap-Minecraft/BlueMap/assets/20233048/710fc378-6ecb-406c-b78e-2b5199bff6f2)

**Comment by TBlueF** [comment]
Have you tried to just `/bluemap purge <map>` to re-render the map? (and then pressing the `Update Map` button on the webapp)
Does it still happen then?

**Comment by TBlueF** [comment]
I am assuming a re-render solves the issue and will close this issue for now.
