### ISSUE TITLE
BlueMap Command Missing

### ISSUE THREAD

**Issue by msburgess3200** [BlueMap-Minecraft/BlueMap#564]
### What i did / Steps to reproduce

Updated BlueMap to version BlueMap-5.2-spigot.

### Expected result

BlueMap Command to work

### Actual result

Unknown Command <-- [HERE]

### Context
**BlueMap Version:**  
`1.0.0-fabric-1.16.1`
BlueMap-5.2-spigot

https://i.imgur.com/yN3CSjw.jpeg

**Comment by TBlueF** [comment]
Please use our [discord](https://discord.gg/zmkyJa3) for support with setting up bluemap correctly :)
Thank you!
