### ISSUE TITLE
Webserver says its starting but it doesn't seem to be

### ISSUE THREAD

**Issue by ProfessorShroom** [BlueMap-Minecraft/BlueMap#568]
### What i did / Steps to reproduce
Starting the server, in the terminal I get the message webserver has started but I cannot connect to the URL, running lsof -nP -i:8100 also gives no results.

### Expected result
The webserver to start

### Actual result
Nothing

### Context
**BlueMap Version:**  
`5.2-paper-1.21.0`

Add more context here!
- Ubuntu 24.04 
- No mods

Also:
- webserver.log is completely empty

**Comment by Chicken** [comment]
Please use our [Discord](https://discord.gg/zmkyJa3) for support.
