### ISSUE TITLE
Feature:Add modeling map display above the bedrock at the top of Nether world

### ISSUE THREAD

**Issue by Baldur404** [BlueMap-Minecraft/BlueMap#572]
In fact In Nether world, many players will break through the top bedrock of nether to reach above it.They build Nether High-speed Transit System and some product machine in there. but the current nether map only show the world below the top bedrock.
In my submission ,add a module perhaps a map to show the world above the top bedrock

**Comment by TBlueF** [comment]
You can change that in the map-config however you like, please use our [discord](https://discord.gg/zmkyJa3) if you need support with configuring your maps :)

**Comment by miaopan607** [comment]
> You can change that in the map-config however you like, please use our [discord](https://discord.gg/zmkyJa3) if you need support with configuring your maps :)

@TBlueF May I ask how to configure this? I'm not able to load Discord in my region. Thank you!

**Comment by TBlueF** [comment]
@miaopan607 
Open your map [config files](https://bluemap.bluecolored.de/wiki/getting-started/Installation.html#where-do-i-find), and then there is a `max-y` and a `min-y` setting in your map config where you can change which "slice" of your world bluemap will render to that map .. or remove them completely if you want it to render everything from top tp bottom *(won't be very useful for normal nether maps)*

**Comment by miaopan607** [comment]
> [@miaopan607](https://github.com/miaopan607) Open your map [config files](https://bluemap.bluecolored.de/wiki/getting-started/Installation.html#where-do-i-find), and then there is a `max-y` and a `min-y` setting in your map config where you can change which "slice" of your world bluemap will render to that map .. or remove them completely if you want it to render everything from top tp bottom _(won't be very useful for normal nether maps)_

Thank you for your answer.
