### ISSUE TITLE
my map seems to be rendered but some areas are kind of faded out/grey

### ISSUE THREAD

**Issue by neotherack** [BlueMap-Minecraft/BlueMap#575]
Hello,

I need some help on understanding the situation of my map.
It seems to be rendered but some areas are grey or dark, but if you zoom in enough you'll see terrain there.

![Screenshot_20240718_112544_Firefox](https://github.com/user-attachments/assets/e58ed148-145d-4498-ad27-7584b9f9f2a9)

Look at the second one,
![Screenshot_20240718_112613_Firefox](https://github.com/user-attachments/assets/cd4494c8-9946-4c5e-a553-de2c25ff2ef8)

 There is terrain rendered in there, but very dark.
Why? How can I fix that?

**Comment by TBlueF** [comment]
See: https://bluemap.bluecolored.de/community/FixLighting.html

Please use our [discord](https://discord.gg/zmkyJa3) for further support :)
