### ISSUE TITLE
Nether only rendering up to Y90

### ISSUE THREAD

**Issue by darkcloud784** [BlueMap-Minecraft/BlueMap#581]
### What i did / Steps to reproduce
 rendered the nether 

### Expected result
 Full map render from top of nether to bottom

### Actual result
Everything from y90 to 10 rendered but nothing else

### Context
**BlueMap Version:5.3 fabric**  
`fabric-api-0.100.7+1.21.jar`

![image](https://github.com/user-attachments/assets/da9974f6-c088-46dc-bcf8-869782d95899)

**Comment by TBlueF** [comment]
This is by design, and a configuration you can change, not a bug.
Please use our [discord](https://discord.gg/zmkyJa3) for support with configuring your maps :)
