### ISSUE TITLE
Rechiseled 1.20.1 Textures not applied properly

### ISSUE THREAD

**Issue by KreathDesu** [BlueMap-Minecraft/BlueMap#582]
When placing rechiseled blocks, the textures rendered are the texturesheet on every face instead of properly applied. I tried using a custom ressource pack but that didn't help.

![Screenshot_1](https://github.com/user-attachments/assets/66e3637a-b566-4bf7-9cb3-7aefe700f3fe)

**Comment by TBlueF** [comment]
BlueMap does not and will not support Rechiseled natively .. 
I am [working towards](https://github.com/BlueMap-Minecraft/BlueMap/issues/561) making it possible to create addons that add explicit support for mods like Rechiseled, but thats still on the TODO :)

**Comment by KreathDesu** [comment]
Alright thanks! :) Thanks for the quick answer and thanks for making this mod/plugin I am enjoying it very much ^^
