### ISSUE TITLE
[Feature] sphere marker / custom marker shapes

### ISSUE THREAD

**Issue by arvitus** [BlueMap-Minecraft/BlueMap#584]
I would really like to see a sphere marker shape in the mod. Maybe so you can set the radius of all three axes so that it doesn't necessarily have to be a sphere.

Maybe it would even be possible to add some kind of custom marker shape so you can just create your completely own shape e.g. like a pyramid. Idk how exactly that could be implemented though.

**Comment by TBlueF** [comment]
Please - as per [contributing guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/f6d39fcdb126cb3a0bbf9303cfbb3f8ed71b35c2/.github/CONTRIBUTING.md#suggesting-a-new-feature-or-change) - use our [discords](https://discord.gg/zmkyJa3) #suggestions channel for suggestions
Thank you :)
