### ISSUE TITLE
[IDEA] Allow specifying map when first accessing the webapp by just providing map name

### ISSUE THREAD

**Issue by KW46** [BlueMap-Minecraft/BlueMap#589]
Right now,the webapp by default loads the first available map.
It apparently first checks if URL hash is valid: https://github.com/BlueMap-Minecraft/BlueMap/blob/master/BlueMapCommon/webapp/src/js/BlueMapApp.js#L169 - If not, load first available map.

Now in my setup I have a static map (Skellige from TW3). At the time of writing, the only available map.
Soon there will be one or two other maps (live maps) and this map would no longer be loaded as default map (one of the live maps will be).
Now this Skellige map is used as a preview for this map; if someone would try to visit `https://bluemap.kwarde.com/#skellige` (URL provided), they would still see the live map and would have to manually select a map. (Either that or the person that added that URL to map description would have to provide a different URL, of course).
This currently is not possible because it requires the full valid url hash: https://github.com/BlueMap-Minecraft/BlueMap/blob/master/BlueMapCommon/webapp/src/js/BlueMapApp.js#L713

Cba to create a PR myself at the moment, if there's agreement on this idea (at first sight it seems like an easy update - though I barely know how this webapp works so I've no ideas what consequences of that _could_ be, haven't looked into the code that much yet -- ofc the non provides values will have to be defined at this point, but apart from that no idea).
Thought it'd be a slight quality of life feature.

**Comment by TBlueF** [comment]
Actually it's more a bug that this doesn't work rn .. it used to work like this ^^
I'll make sure to fix it for next version.
