### ISSUE TITLE
Deactivate surface collisions in Perspective mode

### ISSUE THREAD

**Issue by maximecharriere** [BlueMap-Minecraft/BlueMap#591]
Is it possible to deactivate surface collisions in Perspective mode, to have the same behaviour as in Free-Flight mode, and be able to pass through the surface?  

If not, would it be appropriate to propose a feature request on this point?  

FYI, I'm interested by this feature because I have an underground city, using tunnel networks, and it would be convenient to go underground in perspective mode to see it.

**Comment by TBlueF** [comment]
That's not possible to deactivate rn, no ... 
The problems is ... how would the camera know to which y-height you want to focus (orbit around) .. right now it uses the surface ^^

Also please use our [discord](https://discord.gg/zmkyJa3) for feature-requests and questions.. its much better suited for discussions like this than github :)
