### ISSUE TITLE
Strange cli bluemap behavior

### ISSUE THREAD

**Issue by 1271** [BlueMap-Minecraft/BlueMap#592]
I'm not 100% sure, but it seems that setting 12 threads for rendering does not increase the speed of work. It takes about the same time as with 1 or 2 threads. At the same time, the load increases according to the number of allocated threads.

I haven't tried installing the plugin because it seems like it will slow down minecraft (correct me if I'm wrong)

### What i did / Steps to reproduce
Edit config/core.conf file.
Set `render-thread-count: 12`
Set `render-thread-count: 2`

Run cli version of bluemap.

### Expected result
Speeding up rendering.

### Actual result
It seems that all threads are processing the same tile.

### Context
`BlueMap-5.1-cli.jar`
`BlueMap-5.2-cli.jar`
`BlueMap-5.3-cli.jar`

**OS**: Debian 12
**CPU**: 12 cores/24 threads
**RAM**: 16Gb
**Java**: openjdk 21.0.4 2024-07-16 LTS (adoptium)

If it's possible to enable logging like "Processing: Thread_N => chunk_N" I'd be happy to see it.
Thanks.

**Comment by TBlueF** [comment]
Works fine on my end, here is a version for you with the requested debug-logging: https://github.com/BlueMap-Minecraft/BlueMap/actions/runs/10439166509
:)

**Comment by 1271** [comment]
Thanks. Everything looks correct.
And I like this logging.
Thanks again! Maybe I just thought it wasn't working correctly.
