### ISSUE TITLE
Running as a fabric client mod?

### ISSUE THREAD

**Issue by mazylol** [BlueMap-Minecraft/BlueMap#596]
Would it be possible to run this without a server for local saves? I love the mod but it would be really cool if I did not need a server to do it. I tried downloading the fabric mod but when I ran the game no config files were generated and the commands did not appear. Is it not supported or am I just doing something wrong?

**Comment by mazylol** [comment]
So as it happens, I was doing something wrong. Still not sure if this is exactly supported but it works.

**Comment by TechnicJelle** [comment]
Installing BlueMap on the client is not officially supported. It is server-side only.
However, it does work with a bit of fiddling. If you need help setting it up, feel free to join our Discord Server :)
https://bluecolo.red/map-discord


We generally recommend using the BlueMap CLI for single-player worlds. That *is* officially supported.
