### ISSUE TITLE
Show welcome and farewell messages to players

### ISSUE THREAD

**Issue by tsingyayin** [BlueMap-Minecraft/BlueMap#602]
In Dynmap, we can specify title and subtitle for an area in config to display welcome messages for players. Can BlueMap add similar functions? For example, for Shape and Extrude Marker, if the player is within the range, a welcome message reserved in the configuration file will be sent for them, and a farewell message will be pushed when leaving. 

Similarly, for POI, HTML and line marker, can we add a design of "trigger radius" to push similar welcome and farewell messages for players when they enter or leave the trigger radius?

This is important for enhancing the experience of using marker in the game.

**Comment by TechnicJelle** [comment]
Do you have a link to a dynmap that uses this feature? So we can see for ourselves what it looks and feels like.

**Comment by tsingyayin** [comment]
[markers copy.yml.txt](https://github.com/user-attachments/files/16792316/markers.copy.yml.txt)
Here is a configuration file, which is simplified from the configuration file actually used by my server. 

Please completely overwrite the `markets.yml` file of Dynmap with its contents.

Then, enter the server. When you enter different areas(or, towns), you can see their names (in Chinese here, I have not modified them).

**Comment by tsingyayin** [comment]
That is to say, I may be inclined to think that Bluemap can try to add a function equivalent to [this interface](https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCoreAPI/src/main/java/org/dynmap/markers/EnterExitMarker.java).

**Comment by Chicken** [comment]
Feels out of scope, should be achieved by using something like WorldGuard or similar

**Comment by TBlueF** [comment]
Assuming those greeting / farewell messages are displayed ingame, then that is indeed way out of scope for bluemap. But it would be absolutely possible for a bluemap-addon to do this kind of thing :) - closing

*(Please keep suggestions in our discord, github issues are only for bugs and planned features)*
