### ISSUE TITLE
1.21.1 Fabric support

### ISSUE THREAD

**Issue by BrammyS** [BlueMap-Minecraft/BlueMap#604]
### What i did / Steps to reproduce

Tried running my docker container with MC on 1.21.1 and got an error that the fabrics version for 1.21.1 is missing.

### Expected result

I expected it to work fine, because the other clients already have support.

**Comment by TBlueF** [comment]
BlueMap 5.3 does work fine on fabric 1.21.1, please make sure you have the correct version of bluemap and fabric-api installed :)

**Comment by BrammyS** [comment]
@TBlueF The issue was that fabric wasn't set to 1.21.x on modrinth. But i see that has been fixed now (:
Thank you for fixing it! :D
