### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xXPerditorXx** [BlueMap-Minecraft/BlueMap#608]
The ability to see live block changes when placing and breaking blocks 

I don't know if it works, but PlayerBlockBreakEvent as well as PlayerBlockPlaceEvent could be used.

**Comment by TBlueF** [comment]
Not feasible, also - as per our [contributing guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/7ff993bb4b2ff27a4c0cde9382828d9e0c3f5cef/.github/CONTRIBUTING.md) - please use our discord for feature requests.
I can explain why it is not feasible on our discord if you are interested. :)
