### ISSUE TITLE
Bluemap on Docker is not detecting mod resources

### ISSUE THREAD

**Issue by InfiniteBed** [BlueMap-Minecraft/BlueMap#609]
### What i did / Steps to reproduce
Install Bluemap on Docker with cifs shares pointing to Minecraft servers

### Expected result
Mod resources would be detected, as they do when Bluemap is installed alongside the server.

### Actual result
No mod resources are detected on the Docker install, even though they are detected when installed inside a Minecraft server.

### Context
**BlueMap Version:**
`http://ghcr.io/bluemap-minecraft/bluemap:latest`

- Installation: **Docker Container with Dockge on TrueNAS host**
- Has the world been generated using any minecraft-mods? **Yes**

Also:
![image](https://github.com/user-attachments/assets/0be5605f-63a3-4282-8f42-13302016daaf)![image](https://github.com/user-attachments/assets/a3f3f5f5-a95d-442c-9d63-6bcf7ca74c5e)

**Comment by TBlueF** [comment]
BlueMap needs the mods to be able to "detect" them, the mod data bluemap needs is not saved on the world-files, so on the cli/docker version bluemap doesn't have anything available to load.
However you can put/copy your mod-jar files into bluemaps `packs` folder next to the configuration files, then bluemap will load them like it would on a server :)
If you need further support with setting up bluemap, please use our support-discord :)
