### ISSUE TITLE
Q: Is there an isometric view?

### ISSUE THREAD

**Issue by Lonskie** [BlueMap-Minecraft/BlueMap#610]
Like Dynmap, I was wondering if there is a way to switch the camera into an isometric view.

Something like the below.
![image](https://github.com/user-attachments/assets/2fa7307b-35ac-46e8-9f5b-50b697c262d2)

**Comment by TBlueF** [comment]
A: no ^^

Please use our [discord](https://discord.gg/zmkyJa3) if you need further support :)
