### ISSUE TITLE
A mod that is based on BRRP cannot recognize textures

### ISSUE THREAD

**Issue by mcbianxiao** [BlueMap-Minecraft/BlueMap#613]
### What i did / Steps to reproduce

Install mods with BRRP prepended such as Mishang Urban Construction

### Expected result

Bluemap can render this Mod's road blocks correctly

### Actual result

Bluemap can not render the road blocks of this Mod
![微信截图_20241002170047](https://github.com/user-attachments/assets/462681d6-1373-4491-a049-33328b20a40d)

### Context
**BlueMap Version:**  
BlueMap-5.3-fabric.jar  

**OS:**  
Windows Server 2016  
**Platform:**  
Fabric 0.16.0  
**Minecraft version:**  
1.21  

---

Using Microsoft Translator, if you can't understand it, let me re-explain it. Thank you.

**Comment by mcbianxiao** [comment]
I think this is because these BRRP-based mods come with very few resource files, and Bluemap can't read the resource files created by BRRP itself, which leads to such a problem

**Comment by TechnicJelle** [comment]
Indeed. BlueMap extracts the mod resources from the mod jars themselves.
If mods generate their resources at runtime, BlueMap can't access those.

You'll need to manually make a resourcepack out of these resources and give it to BlueMap.

**Comment by TBlueF** [comment]
Not sure exactly how BRRP works but like Jelle said, bluemap requires the resources in the vanilla json resourcepack format to be able to parse and render the blocks. If those resources are generated at runtime, then bluemap won't be able to retrieve them.

BlueMap won't add support for any specific mod. If there is some new format that establishes itself as a well known and much used standard, then i might think about it, but this is not the case here ^^

What you can do is you can figure out some way to export the runtime-generated resources as well as possible into a vanilla-style-resourcepack and add that to bluemaps `packs` folder, then bluemap will be able to render these blocks. :)
