### ISSUE TITLE
Way to make the map data creation offline

### ISSUE THREAD

**Issue by Logicenios** [BlueMap-Minecraft/BlueMap#616]
Hello,

I have run into an issue where i can not load the map when a network connection is not made with piston-meta.mojang.com. 
If i am not mistaken that is needed to load the texture data. Would we able to load all the textures so it could work offline ?

Thanks for your work.

**Comment by TBlueF** [comment]
Once the correct minecraft-client file is downloaded it will only log a warning but still load.
So e.g. if you are on minecraft 1.21.1 and this file `./bluemap/minecraft-client-1.21.1.jar` is present. Then bluemap will log a warning about not being able to connect to mojang, but still be able to use that file and continue loading.
You can download the client files manually (e.g. from [here](https://mcversions.net/)) if you want and put them in that folder. They need to be named exactly like the pattern above with the correct minecraft-version for your server.
Alternatively you can start bluemap once with the internet connection enabled so it downloads the needed file, and after that it should be able to start again without internet connection.

If you need more support with this, please visit us on our [discord](https://discord.gg/zmkyJa3)! :)
