### ISSUE TITLE
No auto update schedule for world#minecraft:overworld

### ISSUE THREAD

**Issue by Vaskyy** [BlueMap-Minecraft/BlueMap#618]
### What i did / Steps to reproduce

I updated from 5.3 to 5.4 and "world" `minecraft:overworld` map isn't scheduled for updates anymore.

### Expected result

Everything is loaded fine, and i can force update it with commands, it just doesnt look for updates itself anymore.

### Actual result

The other maps are working fine, as the log is telling me.
Out of 3 maps only `world#minecraft:the_end` and `world#minecraft:the_nether` are getting scheduled for updates.
`world#minecraft:overworld` doesnt auto update.

`[2024-10-23 23:42:35][INFO] WebServer started.`
`[2024-10-23 23:42:36][FINE] Started watching map 'world_the_end' for updates...`
`[2024-10-23 23:42:36][FINE] Started watching map 'world_the_nether' for updates...`
`[2024-10-23 23:42:44][FINE] Creating new SQL-Connection...`

### Context
**BlueMap Version:**  
`Version: 5.4
Commit: 074bbc3d0fd565df26c69c51c695c20543e6d50d`

Implementation: fabric
Minecraft: 1.21
Render-threads: 1
Available processors: 2
Available memory: 6144 MiB

[debug.log](https://github.com/user-attachments/files/17499209/debug.log)

**Comment by TechnicJelle** [comment]
Could you do `/bluemap maps` and send the result?

And `/bluemap debug dump` as well.

**Comment by Vaskyy** [comment]
`24.10 10:05:04 [Server] Server thread/INFO Maps loaded by BlueMap:`
`24.10 10:05:04 [Server] Server thread/INFO - world (Overworld)
`
`24.10 10:05:04 [Server] Server thread/INFO    World: world#minecraft:overworld
`
`24.10 10:05:04 [Server] Server thread/INFO    This map is frozen!
`
`24.10 10:05:04 [Server] Server thread/INFO - world_the_end (End)
`
`24.10 10:05:04 [Server] Server thread/INFO    World: world#minecraft:the_end
`
`24.10 10:05:04 [Server] Server thread/INFO - world_the_nether (Nether)
`
`24.10 10:05:04 [Server] Server thread/INFO    World: world#minecraft:the_nether
`
`24.10 10:05:04 [Server] Server thread/INFO    Last Update: 2024-10-24 10:03:34
`

Hm that with "frozen", is weird. I never did freeze any maps on purpose? As far as i remember ..

I did unfreeze it now.

`24.10 10:13:42 [Server] BlueMap-Plugin-UnfreezeCommand/INFO Map world is no longer frozen and will be automatically updated!`

Hope that was it :)

Anyways here's still the dump:
[dump.json](https://github.com/user-attachments/files/17505322/dump.json)


Thanks for the freeze hint!

**Comment by Vaskyy** [comment]
`[2024-10-24 11:00:40][FINE] Stopped watching map 'world_the_end' for updates.
`
`[2024-10-24 11:00:40][FINE] Stopped watching map 'world' for updates.
`
`[2024-10-24 11:00:40][FINE] Stopped watching map 'world_the_nether' for updates.
`
`[2024-10-24 11:00:40][FINE] Started watching map 'world' for updates...
`
`[2024-10-24 11:00:40][FINE] Started watching map 'world_the_end' for updates...
`
`[2024-10-24 11:00:40][FINE] Started watching map 'world_the_nether' for updates...
`

now works fine again! 👍

**Comment by TechnicJelle** [comment]
I'm glad to hear that! :D
