### ISSUE TITLE
Issue with the console and the "Bluemap is missing important ressources" 

### ISSUE THREAD

**Issue by Steakacher** [BlueMap-Minecraft/BlueMap#620]
Hey, I have a problem with Bluemap,

![image](https://github.com/user-attachments/assets/9e9ab072-f31d-45eb-9a6f-0142094a1228)

I downloaded many versions of the mod bluemap for my minecraft server 1.16.2
3 of 4 of them are compatible 

I followed the easiest tutorial but i'm basicly stuck at step one
When I shut down my MC server, I put the pluggin in the pluggins folders
I started my server with my start.bat

and this happened: 
![image](https://github.com/user-attachments/assets/039d8842-b2cd-4e68-a4cd-4d7944743978)

instead of this:
![image](https://github.com/user-attachments/assets/8f981bf7-3636-4d3d-8fc9-b6dcb87f9704)

I don't have the steps "Bluemap is missing important ressources", and I also haven't the steps where a new folder for the mode are creating himself on the pluggins files

**Comment by Chicken** [comment]
You have to use a newer java version, for further support please use our [Discord](https://discord.gg/zmkyJa3) as GitHub is dedicated for bug reports.
