### ISSUE TITLE
Can the Spigot version of Bluemap render items in the Forge mod?

### ISSUE THREAD

**Issue by Chun-QiuCC** [BlueMap-Minecraft/BlueMap#621]
I am running a spigot mix forge Minecraft server, Can the Spigot version of Bluemap render items in the Forge mod?

**Comment by Chicken** [comment]
Such servers are officially unsupported but technically yes.

**Comment by TBlueF** [comment]
Closing this here, If you have more questions, please use our [discord](https://discord.gg/zmkyJa3) :)
*(GitHub issues are for actual bugs with bluemap)*
