### ISSUE TITLE
How the map is formed

### ISSUE THREAD

**Issue by IvanTopGaming** [BlueMap-Minecraft/BlueMap#622]
Good time of day. I would like to ask how the url of the map piece is formed. For example, coordinates 11888 103 -11389 correspond to a piece x2/3/z-2/3.png What is the relationship between coordinates and numbers in the link. Thank you in advance

**Comment by TechnicJelle** [comment]
I recommend asking questions about how BlueMap works in [the Discord server](https://bluecolo.red/map-discord). BlueMap's GitHub issues are for actual bug reports only.

**Comment by TBlueF** [comment]
remove the `/`s and you can read it:
`x2/3/z-2/3.png` -> `x23z-23.png` -> `x23 z-23`
which is the tile-coordinate

But yeah like Jelle said .. further questions go on our discord :)
