### ISSUE TITLE
Build from source failed if use jvm 8

### ISSUE THREAD

**Issue by realyukii** [BlueMap-Minecraft/BlueMap#626]
What BlueMap version that support java 8? I tried to build from source and it fails as it's using java 8.

```
## Building BlueMapAPI ...
Java: 1.8.0_432
JVM: 25.432-b06 (Debian)
Arch: amd64

> Task :api:buildSrc:generateExternalPluginSpecBuilders FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:buildSrc:generateExternalPluginSpecBuilders'.
> Could not resolve all files for configuration ':api:buildSrc:compileClasspath'.
   > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:6.25.0.
     Required by:
         project :api:buildSrc > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.25.0
      > Dependency requires at least JVM runtime version 11. This build uses a Java 8 JVM.

* Try:
> Run this build using a Java 11 or newer JVM.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 29s
2 actionable tasks: 2 executed
```

**Comment by Chicken** [comment]
i think it was 1.7.3 that last supported java 8.... but why are you trying to build for java 8...

**Comment by realyukii** [comment]
for the reason why I stick with java 8: my friend have a phone that only able to run lower version of minecraft, thus in order to play together I have to lower the server version to match it (spigot 1.12.2)

already tried viaversion but no luck, anyway thanks for the response!

**Comment by TBlueF** [comment]
If you need to run 1.12.2: BlueMap's latest versions don't support Minecraft 1.12.2 anymore. The last version that supports 1.12.2 was [BlueMap v1.5.5](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v1.5.5)

**Comment by realyukii** [comment]
Ah yes, it works! (altho some area is black?)
![image](https://github.com/user-attachments/assets/9d3d0dc7-4f57-4c0c-9786-60847f30df9a)

**Comment by TBlueF** [comment]
If you need help or have questions please visit our [discord](<https://discord.gg/zmkyJa3>), but keep in mind that the version you are using is more than 3 years old and no longer supported. I won't fix any issues/bug with that version.
