### ISSUE TITLE
Support to handle doing more things based on cursor position on the map...

### ISSUE THREAD

**Issue by XeonG** [BlueMap-Minecraft/BlueMap#627]
Basically my first request is being able to warp my player to a position on the map... ie teleport to location.. but also if it is a differnent world that /mv tp <world name>

I'm not sure if there is a plugin for doing this but figure it must be possible somehow...

some sort guide implementation to show how it is done

or even being to warp to a location of a worldguard region other such shown markers on the map

just more utilization of the map features

**Comment by TBlueF** [comment]
There is no login-system on the webapp and it's not planned to add one, so this will not be added from bluemap directly. It might be possible to make an addon for this.

Either way this is a suggestion which doesn't belong to GitHub-Issues. Please put suggestions in our discord-suggestions channel, thank you :)
