### ISSUE TITLE
Immersive weathering leaves compatibility

### ISSUE THREAD

**Issue by Dalethium** [BlueMap-Minecraft/BlueMap#628]
### What i did / Steps to reproduce
have leave piles in a modded fabric world with immersive weathering.

### Expected result
short leave piles being rendered.

### Actual result
missing texture blocks being rendered.

### Context
**BlueMap Version:**  
`5.3-fabric-1.20.1`
eed8f79e68b053c119f88bbf358bed893a78d110

The actual block in question: https://github.com/AstralOrdana/Immersive-Weathering/blob/1.20.0-multiloader/common/src/main/java/com/ordana/immersive_weathering/blocks/LeafPileBlock.java
![brave_nhLIdpG4m0](https://github.com/user-attachments/assets/2b8e0271-cbc9-4c85-8f34-28fb1a265124)
![javaw_E5i5TepCxu](https://github.com/user-attachments/assets/75ea450a-adb6-4fa8-9caa-55a7a7071c7e)

Please let me know if I can add any more context.

**Comment by TBlueF** [comment]
BlueMap is not adding explicit support for individual mods.

BlueMap is automatically looking for mods and datapacks in your server-files. If it finds them it will try to load them and parse its resources to be able to render any additional blocks.

BlueMap might not be able to parse all blocks and resources for a mod. For example, if a mod generates its resources/block-models at runtime, BlueMap won’t be able to find them in the mod.jar and will not be able to render them correctly! You might still be able to fix this by creating a resource pack for the models.

Read more at https://bluemap.bluecolored.de/wiki/customization/Mods.html

If you have more questions about this, please use our [discord](https://discord.gg/zmkyJa3) :)

**Comment by Leonature26** [comment]
@TBlueF is there an option to skip bluemap rendering these troublesome immersive weathering blocks or any other blocks that doesn't have a texture? (Instead of showing distracting purple boxes there'd be nothing)

![Image](https://github.com/user-attachments/assets/1c48abf7-712b-41a3-ad94-da44d3af2628)

**Comment by TBlueF** [comment]
@Leonature26 Yes, you can make a custom resourcepack that does this. 
Please use our [discord](https://discord.gg/zmkyJa3) if you have further questions :)

**Comment by Leonature26** [comment]
i imagine someone has thought of removing these distracting stuff before. Is there an existing resourcepack that already does this by any chance?
