### ISSUE TITLE
Extract resources assets like model extensions into a reusable npm package

### ISSUE THREAD

**Issue by talks2much** [BlueMap-Minecraft/BlueMap#630]
Hi! Thanks for an awesome project! I saw a lot of custom block entity models created by you (like signs, chests, ...), would it be possible to extract it into a reusable system? (though I know this project doesn't seem to be a monorepo).

Howerver, I saw incredible packages like https://npmjs.com/mc-assets that maybe already do it, but I'm interestsed in finding an ideal solution that can be reused by anyone (and it seems it uses custom models created by you btw ;) as noone likes maintaining what can be maintained by someone other and simply reused later in the project. Also from what I've been told it will support resourcepacks soon once it has a feedback on how it should be implemented.

**Comment by TBlueF** [comment]
Not quite sure what you mean by this, the resources are all in a minecraft-compatible resource-pack format starting [here](https://github.com/BlueMap-Minecraft/BlueMap/tree/master/core/src/main/resourceExtensions), so if someone wants to use them, they should easily be able to .. 

But ... they are specifically made for bluemap and I don't intend to provide support and/or update them for any other purpose ^^

Anyways, as per our contributing guidelines, please put suggestions onto our [discord](https://discord.gg/zmkyJa3)s #suggestions channel. :)
