### ISSUE TITLE
How to open a web map in a browser with server ip 0.0.0.0

### ISSUE THREAD

**Issue by TON618OFF** [BlueMap-Minecraft/BlueMap#636]
I installed the Blue map plugin on my minecraft server, but the server runs on 0.0.0.0 ip and I do not know which address I should specify in the browser to open the map of my world.

**Comment by TBlueF** [comment]
You use the public ip address of your server.
Please use our [discord](https://discord.gg/zmkyJa3) for support questions, github issues are not the correct place for support.
