### ISSUE TITLE
Feature Request: Ability to set a default icon for a marker-set

### ISSUE THREAD

**Issue by reishka** [BlueMap-Minecraft/BlueMap#640]
Current behavior: 
All marker-sets that have POI markers use the same poi.svg icon

Wanted behavior: 
Allow marker-sets to define the icon that their POIs will use, and still allow the POI icon to be overridden at the marker-level. If no icon is defined, the default poi.svg is used.   

Example: 

- Marker-set "Player Bases" can use the existing poi.svg by default, but allow the set creator to define a bases.png icon; all POI markers within "Player Bases" marker-set will use the bases.png as their default instead of the poi.svg
- Marker-set "Villages" can use the existing poi.svg by default, but allow the set creator to define a villages.png icon; all POI markers within "Villages" marker-set will use villages.png as their default instead of poi.svg 

This would make for cleaner maps that differentiate POIs based upon their marker-set (much like how real-life maps will have a legend for different types of buildings), and allow for quicker visual differentiation when multiple marker-sets are visible on a map.

**Comment by TBlueF** [comment]
This is a really nice idea, however it's the wrong place for suggestions :)
Please use our [discord](https://discord.gg/zmkyJa3) #suggestions channel. Thank you!
