### ISSUE TITLE
[Feature Request] 2 Dimensional Map

### ISSUE THREAD

**Issue by NeusFear** [BlueMap-Minecraft/BlueMap#67]
# Reason
I find myself sometimes wanting a map that is only top-down as opposed to the more demanding option of walking around the world. This would be good for big maps that don't change much, or for maps that you don't want the user to know everything about aside from their location. I have an RPG server in the works and I don't want the users to be able to go to buildings in detail that they're not high enough level to reach yet for example.

# Possible Implementation
I think that using the models for the world would still be done without creating image files and as a result creating "dynmap 2" by creating a 5 layer model instead. The following list from top layer to bottom layer:

1. Above Water Transparent Layer - Transparent blocks that render above water (stained glass type stuff)
2. Water Transparent Layer - The layer Water is rendered on
3. Under Water Transparent Layer - Transparent blocks that appear underwater (stained glass type stuff)
4. Cutout Layer - The layer that has cutout blocks on it (like regular glass, trapdoors, possibly non-full blocks like fences, rails, etc.)
5. Solid Layer - The layer that has the solid blocks on it

## Explanation
The reason for including 2 transparent block layers is to combat the issue in vanilla where you can see through the water when looking through another translucent render layer block like stained glass or an entity or something.

## Execution and usage
The way I imagine this being implemented is just tracing the blocks from top to bottom until you hit a solid block, noting each of the first of every type of render layer as you go down. This way you can then create the top faces of each block in the display for the user to see.

## Conclusion
It, of course, doesn't have to be implemented in this way, but this is how I imagined it possibly being worked out.
Thanks for considering!

**Comment by TBlueF** [comment]
So, if i understand this correctly: What you are proposing sounds cool, but is **way** off from what bluemap is designed to do.
This would be a completely new project to work on. 

Also i still don't get the advantage or difference to dynmap:
What is the advantage over using "layers" over just rendering a combined image and displaying that?
Why use a 3D-model and 3D-engine if the aim is to display a 2d-map?

**Comment by NeusFear** [comment]
I guess the advantage to the use of models would be less things to be rewritten I guess. And it wouldn’t be the full block model just the top face since it’s a parametric rendering.

**Comment by TBlueF** [comment]
I'll close this, because in my opinion a "2D-Map" is out the scope of this project (a 3D Map) and since BlueMap is optimized to work with 3D-Models any implementation that tries to force a 2D-Map would be not optimized for what it does.
If someone still wants to take a shot at this, feel free to fork the repo :D
