### ISSUE TITLE
After update to 0.10.2 other plugins crash on boot

### ISSUE THREAD

**Issue by poqdavid** [BlueMap-Minecraft/BlueMap#71]
Well I just tried to update and when I booted up the server it caused other plugins to crash not sure why but it's all fine in 0.10.1

Here is the crash log
https://hastebin.com/tebojohezu.log

**Comment by TBlueF** [comment]
Oh .. okay i should not have updated bStats ..
It seems like the newer version they released causes plugins with an older version to crash .. ill downgrade it again asap *(another bugfix release ugh .. xD)* and report that to bStats.

**Comment by TBlueF** [comment]
Fixed in latest version.
