### ISSUE TITLE
Other language marker lable support

### ISSUE THREAD

**Issue by Glucy-2** [BlueMap-Minecraft/BlueMap#74]
I can't use Chinese in the marker's lable

**Comment by TBlueF** [comment]
What happens if you do? Does it give you an error of does the marker just not load?
Can you give me an exampe lable that i can copy and paste to test this?

**Comment by Glucy-2** [comment]
![image](https://user-images.githubusercontent.com/53287753/91599039-34e5d600-e998-11ea-9bcb-f651437b37b6.png)
错误的命令参数
..est world 测试<--[here]
在第34个字符处发现需要双精度浮点型：...est world <--[HERE]
在第34个字符处发现参数后应有空格分隔，但发现了紧邻的数据..est world <--[HERE]
/bluenap marker create test world 测试
- translation:

Bad command parameter
..est world test<--[here]
Found at the 34th character that a double-precision floating point type is required:...est world <--[HERE]
At the 34th character, the parameter should be separated by a space, but the next data is found..est world <--[HERE]
/bluenap marker create test world 测试

**Comment by TBlueF** [comment]
Please try `/bluemap marker create test world "测试"` .. (with 
quotation marks) that works for me .. :)

**Comment by Glucy-2** [comment]
It's OK, thanks.
Closing it.
