### ISSUE TITLE
Abillity to hide/show players on the map via command

### ISSUE THREAD

**Issue by TBlueF** [BlueMap-Minecraft/BlueMap#75]
Add a command to hide/show players on the map.

**Comment by GriffinCodes** [comment]
Please also consider adding the ability to hide via permission

**Comment by TBlueF** [comment]
Can be done using BlueMap's API and a 3rdPartyPlugin.
Won't be in BlueMap natively because of challenges with Commands in a platform-independent environment *(AutoCompletion of player-names)*

(E.g. https://github.com/TechnicJelle/BlueMapPlayerControl)

**Comment by codec-d** [comment]
just make it an option in the configs

**Comment by kargaroc** [comment]
i'm tempted to uninstall this from my server because of this
