### ISSUE TITLE
Wrong player dimension and position

### ISSUE THREAD

**Issue by Glucy-2** [BlueMap-Minecraft/BlueMap#76]
The map shows the player wushi_ is in `the end` at `3 -403` and not moving.
But the player is in the `overworld` at `9 -492` and moving.
![Screenshot_2020-08-30-16-01-28-37_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/53287753/91654430-248a4400-eadb-11ea-9c9c-5a592b5a0ef6.jpg)

**Comment by Glucy-2** [comment]
The player on the map havn't moved for over 30 minutes.

**Comment by TBlueF** [comment]
Fixed in `v1.0.0-rc3`
