### ISSUE TITLE
Add possibility to localize the web-app

### ISSUE THREAD

**Issue by Mark-225** [BlueMap-Minecraft/BlueMap#78]
The title basically says it all :D Not super important, but it would be nice to have a config setting allowing you to change the live player markerset label. The lowercase "player" label can look a bit off when you have other markersets named in a different language or all other markerset labels are capitalised.

**Comment by TBlueF** [comment]
I'd even extend this and check if a full localization config is feasible..

Edit: this will probably be scheduled after/with the web-app rewrite (#64)

**Comment by TBlueF** [comment]
Note to also add page-title and favicon to localization :)

**Comment by TBlueF** [comment]
Implemented in 1.4.1, earlier than planned :D
