### ISSUE TITLE
menu customizable in language

### ISSUE THREAD

**Issue by Blueeyestar** [BlueMap-Minecraft/BlueMap#82]
Since we offer the server in our language, we want to adapt the menu in our language as well.

So it is easier for older users who cannot speak English.

It would be great if this could still be customized

![menü](https://user-images.githubusercontent.com/35557302/92305644-7fafb100-ef89-11ea-9ee3-da8b18390a48.png)

**Comment by TBlueF** [comment]
Closing this in favor of #78
