### ISSUE TITLE
Support for Redprotect and Worldguard Regions

### ISSUE THREAD

**Issue by CloudeLecaw** [BlueMap-Minecraft/BlueMap#84]
Would be nice to be able to see optional Redprotect and Worldguard Regions like it is possible with Dynmap
![Snag_9d500b8](https://user-images.githubusercontent.com/12080017/92334089-0b5d3680-f08b-11ea-9d4d-69c6fad6abf7.png)

**Comment by TBlueF** [comment]
Hey :) 
I won't add support for any mod/plugin directly into BlueMap, but there is an [API](https://github.com/BlueMap-Minecraft/BlueMapAPI/) that can be used by any developer to create either support for bluemap, or a bridge-plugin adding the markers.
The API is already supporting region markers :)
I myself will not work on any bridge-plugins for now.

*(Also, there is already one unofficial bridge-plugin for worldguard that i know of: https://github.com/Mark-225/blueguard)*
