### ISSUE TITLE
Abort rendering in queue

### ISSUE THREAD

**Issue by olly1240** [BlueMap-Minecraft/BlueMap#86]
**BlueMap Version:** 
`1.0.0-spigot-1.16.3`

**Description:**
I accidentaly started 2 full world render on a 1.5gb world, and it's taking too long to even complete the first. I can't stop the render nor delete the other from the queue.

**Comment by TBlueF** [comment]
Use `/bluemap` while ingame and click the red `[x]` next to the render-task :)

**Comment by olly1240** [comment]
That worked! Thank you, I didn't think about ingame controls.
