### ISSUE TITLE
Could you please add a command to stop rendering the map

### ISSUE THREAD

**Issue by skycatcher** [BlueMap-Minecraft/BlueMap#87]
Sometimes I accidentally use the /bluemap render command cause the map to be re-rendered, but there is no /bluemap cancel command to cancel this mistake operation.
Could you please add the /bluemap render cancel command in the future?

**Comment by TBlueF** [comment]
You can use `/bluemap` ingame and click on the [x] to cancel a render.
I'll add a way to cancel renders from the console soon.
