### ISSUE TITLE
Address bar is hard to edit or copy

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#9]
Once the site has loaded, it's very hard to edit or copy the address bar.

**Comment by TBlueF** [comment]
Hm, maybe because it is updating the anchor every second?
What browser are you on?

**Comment by Katrix** [comment]
Firefox Nightly 74.0a1 (2020-01-13) (64-bit)

**Comment by TBlueF** [comment]
I was able to reproduce this with Firefox Nightly
It works fine with the Stable Firefox build and Chrome though.
