### ISSUE TITLE
Client-side version

### ISSUE THREAD

**Issue by v57** [BlueMap-Minecraft/BlueMap#91]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Why do you want this feature

That would be a game changer if you made a client-side version, so polygons will load from the server right into the minecraft like CWG Far Plane View does (except rendering flying objects not needed). Its ok if we have visual bugs like in browser

**Describe the solution you'd like**

Main solution is to synchronize map from the server and polygons in minecraft, cut polygons in radius of render distance/loaded chunks and remove fog (or use optifine for that). There probably would be some problems with opengl render distance and maybe far lands. But i'm 100% sure that this would be the main mod in any minecraft's modpack

**Comment by TBlueF** [comment]
So what you are describing is a client-mod that is loading the low-res tiles from an existing bluemap into your client, to extend the view-distance?
That's an interesting idea, but a completely new project. So it is out of scope on this issue tracker.

Also, if you are asking me.. I myself will not start this as a new project, sorry ^^

**Comment by v57** [comment]
Okay, thanks for your response. Can you please tell me how hard is to create a mod like that? Its ok if you're not familiar with minecraft's rendering engine if that's the main issue

**Comment by TBlueF** [comment]
I think you'd need quite a bit of experience..

**Comment by jrvgr** [comment]
https://github.com/PorkStudios/FarPlaneTwo

**Comment by FrostBird347** [comment]
I don't have the time or experience required to make such a mod and it's unlikely that somebody else who has the time and skills required would find this issue and then decide to make such a mod, but it would look amazing to have this view in game.
![view](https://user-images.githubusercontent.com/39435218/131600754-84ff5a90-832a-4620-8c67-822b47bed1b3.png)
