### ISSUE TITLE
Lag and error spam

### ISSUE THREAD

**Issue by mmuziek** [BlueMap-Minecraft/BlueMap#93]
1.1.0-spigot

I am using:
spigot > no MODS just plugins

**Description:**
When i open my map my browser console is spamming and lagging 
https://prnt.sc/upcr2j
the map shows correct but is terribly slow (google Chrome)

**Comment by TBlueF** [comment]
The error spam is perfectly normal.. tiles that are not rendered, don't have a file and therefore produce a 404 ... this is expected and the web-app handles that perfectly fine. I would hide those 404-errors but there is no possible way to do so with javascript.

The error you posted in #94 `EXT_frag_depth not supported` means that your browser does not support a WebGL feature that is needed to improve performance/visuals ... I would assume that you have [hardware acceleration](https://www.webnots.com/what-is-hardware-acceleration-and-how-to-enable-in-browsers/#:~:text=In%20your%20browser%2C%20Hardware%20Acceleration,CPU%20to%20handle%20other%20tasks.) disabled  .. which would explain the EXT_frag_depth feature missing and the terrible performance.
