### ISSUE TITLE
web-app playerlist

### ISSUE THREAD

**Issue by hornta** [BlueMap-Minecraft/BlueMap#96]
I believe it's quite hard to try and locate a player on the map. A list of online players and a "Go to player" button would maybe suffice. The list could potentially be inside the sidebar or maybe as an overlay in some corner. Or is it just stupid idea?

**Comment by TBlueF** [comment]
This would be equivalent to the playerlist for the web-app that has been suggested and added to the TODO list on discord #suggestions :)

**Comment by TBlueF** [comment]
Added with 1.4.0 :)
